### ISSUE TITLE
multiple mintUpdate.py

### ISSUE THREAD

**Issue by CrimsonGlory** [linuxmint/mintupdate#1]
The other day my pc was very laggy. I htop it and I found out this:
http://imgur.com/Xa5hf

Not sure if I have the last version of mintUpdate.py I have, so here is its code:
http://pastebin.com/LD9mCTnm
Also, from line 32 to 39 you have

[code]
try:
	numMintUpdate = commands.getoutput("ps -A | grep mintUpdate | wc -l")	
	if (numMintUpdate != "0"):
		if (os.getuid() == 0):
			os.system("killall mintUpdate")
		else:
			print "Another mintUpdate is already running, exiting."
			sys.exit(1)
[/code]

This lines are in the current code. It seems this didn't worked as planned. Maybe because it failed or took too long to kill mintUpdate.
I don't know python, but maybe instead of a 'if (numMintUpdate != "0")' it should a be 'while( commands.getoutput("ps -A | grep mintUpdate | wc -l"))'
Or maybe the problem is that the script doens't check if mintUpdate was killed succesfully.

**Comment by JosephMcc** [comment]
It has been over 5 years since this has been active.
