### ISSUE TITLE
Indicator support?

### ISSUE THREAD

**Issue by Trucido** [linuxmint/mintupdate#101]
Apologies if this is the wrong place to post this, but I LOVE mintupdate, however the obscure power users such as myself may be using other desktops without a system tray (such as pantheon, which I just got working quite well!). I'm not sure how hard this would be to implement or if it's even worth developer time to do so since all the mint default desktops support a system tray, but it might be worth looking into in the future to have both systray and indicator support.

If this might be something not-too-difficult to implement, I could give it a go if someone could point me in the right direction.

**Comment by robrobinbin** [comment]
I agree. On cinnamon 2.8 indicators are now better integrated than before. The shield png's should be replaced with flattish svg's that change colour depending on the colour of your panel. (Third party icon themes also should be able to overwrite the icons)
![screenshot1](https://cloud.githubusercontent.com/assets/8597693/12010584/153ad044-acad-11e5-9fd5-2a2c3565a453.png) ![screenshot2](https://cloud.githubusercontent.com/assets/8597693/12010589/34414c48-acad-11e5-961a-d7aa588229c5.png)
Indicators simply look nicer and more at home in a modern DE like Cinnamon (KDE, pantheon, unity,...)

**Comment by EduardDopler** [comment]
I created a set of flat themable icons for my mintUpdate version. How does it look on your theme?
Download: [mintUpdateIcons.zip](https://github.com/linuxmint/mintupdate/files/72759/mintUpdateIcons.zip)

Preview:
![mintupdateicons](https://cloud.githubusercontent.com/assets/9469003/12011321/054812a2-acc9-11e5-8b45-4e78061ef729.png)

**Comment by robrobinbin** [comment]
Thanks, those look nice (and I'll be using them). Implementing an indicator instead of a legacy status icons would provide even better integration (like automatically change colour when the cinnamon theme is changed, Clutter menu's, better KDE(?), pantheon, unity support, ...) I guess.

**Comment by EduardDopler** [comment]
@robrobinbin Would you mind testing my two commits?

**Comment by robrobinbin** [comment]
@EduardDopler Works like a breeze! (silly me first forgot to install python-appindicator). 

> Sadly, the underlying indicator library can only show a menu on click,
clicks on the icon are not customizable, and there is no signal for
double-click. Hence, in order to show the main window, one needs to
click on a menu item now.

Gee, I knew they didn't support right-click and tooltips, but it's also impossible to drop the menu all together? Because that's what I was about to suggest. Maybe remove some stuff from the menu, to draw more attention to "Open"? (like "Information" and "Preferences"?) Or maybe add a separator between open and the other options? What's your opinion?

**Comment by EduardDopler** [comment]
@robrobinbin Oh I should have mentioned the new dependency, sorry.
I like your idea and updated my commits combining your ideas; I added a seperator and removed both menu items you mentioned as they are of minor importance for most users in most situations and still accessible from the main window.

**Comment by xenopeek** [comment]
Many thanks for contributing to mintupdate. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
