### ISSUE TITLE
mintupdate doesn't start: Invalid line at line "1"

### ISSUE THREAD

**Issue by kehugter** [linuxmint/mintupdate#102]
Running `mintupdate` or `mintupdate-launcher` outputs

    Invalid line at line "1"

I could only find one similar (almost identical) unresolved issue here
http://forum.linuxmint.net.tr/index.php?topic=2230.0

Purging and re-installing mintupdate didn't work. I didn't add any _questionable PPA_ (https://github.com/linuxmint/mintinstall/issues/82#issuecomment-73022841) before the issue started yesteray.

---

Mint 17.1
Cinnamon 2.4.8

**Comment by kehugter** [comment]
The issue evolved to

    $ mintupdate
        mintUpdate: no process found
        Parsing failed with several errors.
        First error at line 1.

after some package clean-up and a reboot.

**Comment by rockyjvec** [comment]
I had the same problem.  I was able to fix it by removing:
~/.config/linuxmint/mintUpdate.conf

I guess that config file got corrupt somehow which was what caused the parse error.

**Comment by kehugter** [comment]
Brilliant @rockyjvec, that worked. I'm leaving this open for the devs to prevent the broken config file from blocking mintupdate indefinitely.

**Comment by DivineComedy11** [comment]
Just leaving a comment to say I had a similar problem on a fresh install of 17.2. Thanks @rockyjvec, your solution worked perfectly!

**Comment by anteroortiz** [comment]
Thank you @rockyjvec . Worked for me.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintupdate/commit/81fc8688692830b2a4a895b5f9bea724d999b643
