### ISSUE TITLE
Error formatting in mintUpdate's main window

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/mintupdate#107]
I think the following picture speaks for itself:

![screenshot from 2015-06-18 16 22 49](https://cloud.githubusercontent.com/assets/5564491/8233455/a9f796c2-15d6-11e5-9e26-5a0869275e8f.png)

As you can see, it directly takes the output from `apt-get update` and puts it there. At least some nicer line breaking could clean things up and make the error message a bit more comprehensible.

***
Linux Mint 17.2 RC "Rafaela" Cinnamon Edition 64bit
mintUpdate <strike>4.8.5</strike> 4.8.6

**Comment by xenopeek** [comment]
This one is solved I believe. Errors with failing to fetch repositories are displayed in a dialog window, with the error messages in a text box (too long lines are wrapped and the text box can be scrolled vertically).
