### ISSUE TITLE
Partial automatic updates

### ISSUE THREAD

**Issue by corefx** [linuxmint/mintupdate#113]
It would be great to have an option for installing certain updates automatically (update levels 1,2 and 3).

**Comment by TheDevKing** [comment]
I agree entirely. The only potential issues I could see with this are permission issues, which could probably be worked around.

**Comment by sevenskull** [comment]
That would be great OPTIONAL thing of course, specially for those migrating from Windows, and don't want to mess with this. Make it simple, for people who want it simple.
Windows does that, android does that, etc.
I personally prefer let it manual, but when i install it for others people, then tend to ignore updates, so they use outdated firefox, java, flash, etc. Which is worse than autoupdate.

**Comment by choikwa** [comment]
+1 I was looking for this feature. There is ubuntu way to set up a cron job or unattended-upgrades, but there needs to be a way to feed level and package to these. I don't know how mintupdate upgrades internally...

**Comment by turqoisehex** [comment]
I agree that it'd be convenient, but there would be issues of permissions, stability, and security. Permissions would be the smallest issue. For stability, yes you could have it set to only do level 1, but that category is usually used for items which are actually developed by the Mint crew. If you wanted, "firefox, java, flash, etc." those generally fall into category 3, and so to upgrade them would require upgrading most software most of the time. Sometimes a package should be held back, though I admit that almost all users will just update all without reading the change log or concerning themselves with possible regressions. This is Linux Mint, not Arch; we expect it to just work.

Security would be a double edged sword, but one way I can see it working would be to only do security updates, no feature updates. Regressions/bugs tend to come from feature updates as far as I've encountered, security updates tend to be safer. For security updates only, I can imagine it being fine for packages up to level 3.

**Comment by Jusix** [comment]
Automatic/Unattended security updates are very important in todays world, would be nice if you could implement that.

**Comment by NikoKrause** [comment]
Automatic updates are possible now with Linux Mint 18.2.
In the [release notes](https://www.linuxmint.com/rel_sonya_cinnamon_whatsnew.php) it says:
> Last but not least, advanced Linux users can now automate updates by writing scripts, routines or cron jobs thanks to a new CLI called “mintupdate-tool”. This tool supports all the features available in the UI, including level selection, security updates, kernel updates and blacklisting. You can use "mintupdate-tool" both to list and to apply updates.
To get started with mintupdate-tool, type "mintupdate-tool --help".
