### ISSUE TITLE
Unicode characters not displaying properly

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [linuxmint/mintupdate#114]
Specifically the `®` character

![screenshot - 07162015 - 12 33 07 pm](https://cloud.githubusercontent.com/assets/2776014/8730531/ec8b33cc-2bb6-11e5-8ed8-afbc79a8b45b.png)

..unless it's actually `Adobe? Flash? Player`?

**Comment by JosephMcc** [comment]
Is this still an issue under Mint18 with the newer mintupdate?

**Comment by xenopeek** [comment]
I tested this on Linux Mint 18 with mintupdate 5.1.0. I downloaded and installed an earlier version of adobe-flashplugin from http://archive.canonical.com/ubuntu/pool/partner/a/adobe-flashplugin/ to be able to test it.

It now shows as: `Adobe&#174; Flash&#174; Player is a cross-platform, browser-based [...]`

**Comment by Cos-mo** [comment]
See # #172

**Comment by f380cedric** [comment]
Why do not use [html.unescape](https://docs.python.org/3/library/html.html#html.unescape) on [line 1817](https://github.com/linuxmint/mintupdate/blob/eb9fa1a71977367b702046292e4fc3b6aa2afed4/usr/lib/linuxmint/mintUpdate/mintUpdate.py#L1817) for example?

**Comment by rj200** [comment]
Still a bug in current Linux Mint 18 version. Most annoying if not using English. From the recent GRUB update (system set to Spanish): "GRUB es un poderoso gestor de arranque port&#225;til. Esta versi&#243;n de GRUB est&#225; basada en un dise&#241;o m&#225;s limpio que sus predecesores y proporciona las siguientes nuevas caracter&#237;sticas:"

**Comment by f380cedric** [comment]
Cannot reproduce in Linux Mint 18.2 (mintUpdate 5.2.9)

**Comment by xenopeek** [comment]
Duplicate of #230. Fixed.
