### ISSUE TITLE
Low/no visibility of shortdesc with certain dark themes

### ISSUE THREAD

**Issue by TheDevKing** [linuxmint/mintupdate#115]
Using the theme Jet-Gray

![mintupdate-dark](https://cloud.githubusercontent.com/assets/13073977/8945423/e4d46eba-354c-11e5-869f-f45c8dee78b1.png)

It would probably be ideal to move away from hardcoded colors entirely if feasible

**Comment by JosephMcc** [comment]
This should now be fixed https://github.com/linuxmint/mintupdate/commit/e859aafaf9d1645d32a5413da0df60d33859b7d2
