### ISSUE TITLE
Cancelling a download should not be treated as an error

### ISSUE THREAD

**Issue by s3lph** [linuxmint/mintupdate#116]
When I click the "Cancel" button in the download dialog in mintUpdate, the download is cancelled as requested. Somehow, this cancelling is being treated as an error, as a window with the following error message appears:

> **An error occured**
> The following details are provided:
> 
> ```
> W: Failed to fetch http://example.com/example1.deb
> W: Failed to fetch http://example.com/example2.deb
> W: Failed to fetch http://example.com/example3.deb
> ```

I think that mintUpdate shouldn't show an error dialog in this case, even though `apt-get` may throw an error upon cancelling.

I don't know whether this is the fault of mintUpdate, Synaptic, apt-get or the combination of those that causes this behavior, but I think this should be changed.

**Comment by brennanhm** [comment]
Hi there,

This is an issue with Synaptic, not Mint Update.

You can verify this if you launch Synaptic, select some packages for installation, and then cancel the installation while it's in progress. You will see the same errors.

When the user clicks the Install button, Mint Update launches Synaptic to install the packages. Unless Synaptic offers a command line option to suppress the errors (which I couldn't find), I don't think Mint Update can prevent the error messages from being displayed.

**Comment by xenopeek** [comment]
As brennanhm detailed, this is how Synaptic handles clicking cancel in the progress window.
