### ISSUE TITLE
Window of installing of upgrade pop-ups

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mintupdate#117]
After I press upgrade, enter password - progress of downloading window pops up. Then I switch on another window, browser for example. Then, when downloads finished, window of installation progress pops up and interrupts my work. I would like this window not to be on top, when it appears, or unified with  download and installation progress in one window

**Comment by JosephMcc** [comment]
It would be nice if we could embed all of the functionality directly in the mintupdate window. It is actually separate applications being run while performing the updates though, so currently I'm not sure it's possible.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/mintupdate/issues/168
