### ISSUE TITLE
update-initramfs should be executed after a kernel upgrade

### ISSUE THREAD

**Issue by Zaharid** [linuxmint/mintupdate#118]
I had the exact same problem described here:
http://askubuntu.com/questions/613599/pm-hibernate-freezes-and-or-fails-to-resume-on-dell-xps-13-14-04-3-19-kernel

That is, the hibernate function wouldn't work after upgrading to a newer kernel. The solution there also worked for me, namely running the `update-initramfs` command with the correct parameters. I think the uuids were set properly.

**Comment by clefebvre** [comment]
That's the responsibility of the package, not mintupdate.
