### ISSUE TITLE
Select updates by type

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#119]
On connections with limited traffic I would like to be able to quickly select the security-related updates only.

**Comment by JosephMcc** [comment]
Not sure what you mean. Updates are marked by type. That is why the first column is labeled "Type" ;)

**Comment by kneekoo** [comment]
I edited the title. What I meant is I would like to be able to *select* only security updates. Right now we can either "Select All" or "Clear" the selection.

**Comment by kneekoo** [comment]
It would be cool if we could also select levels (for instance, only 1 and 2).

**Comment by clefebvre** [comment]
You can make already differentiate between visible and safe (i.e. selected by default), both for security updates and for levels.

To go further than that and let you select/deselect groups like that... that's a bit overkill and imagine how the UI would look like.

**Comment by kneekoo** [comment]
Next to the **Clear selection ** button we could have another button - **Custom selection** - that would open a drop-down with two options: regular and security updates.

It wouldn't look bad and it would allow more types elegantly, without *bloating* the UI. There's an even easier option, like having a sub-menu in **Edit** > **Custom selection** > *Toggle regular updates* and *Toggle security updates*.
