### ISSUE TITLE
Package selection gets reset if update fails

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#120]
**mintUpdate 4.9.2**

Having an unstable connection, my update failed while it was trying to get packages. Once I clicked the **Close** button on the error message window, mintUpdate displayed the updates list with all of them selected, although I only had selected a few of them.

To reproduce this issue I clicked **Clear** to deselect all the updates, then I selected one package and I clicked **Install updates**. After entering my password I disabled my network and let mintUpdate fail like you see below.

_W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/bash-completion/bash-completion_2.1-4ubuntu0.1_all.deb
  Could not resolve 'archive.ubuntu.com'_

It happened just as before: I closed the error message window and all the updates were selected.

**Comment by JosephMcc** [comment]
Could you retest this in Mint18 with the newer mintupdate?

**Comment by kneekoo** [comment]
The issue is still present.

**Comment by brennanhm** [comment]
Hi there,

When the user clicks the Install button, Mint Update executes Synaptic to install the selected packages. We can check the last entry in the apt log to see if Synaptic actually installed any of them. If so, then we need to call the refresh thread to update the list of available packages.

On the other hand, if the connection times out or the user cancels before any packages are installed, we can skip the refresh thread and change the app status to "could not install the security updates". In this case, the packages the user had unchecked would remain unchecked.

I'll submit a PR for this...

More info: If any of the selected packages were successfully installed, then the last entry in the apt log will contain the temporary file name (f.name) and the string "End-Date".
