### ISSUE TITLE
Mintupdate crashes during install

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mintupdate#122]
Several times faced crashing of mint update. The last time it crashed during installing of updates, i was tyoing in terminal `sudo apt-get install ...` then hit `TAB` several times - and mintupdate crashed.
If mintupdate gui crashes - then the whole process of update crashes?

**Comment by clefebvre** [comment]
I have to close this as there's not enough info to work on it.

Please find a cause or a way to reproduce the issue consistently.
