### ISSUE TITLE
Preferences - Update Manager changing icons breaks

### ISSUE THREAD

**Issue by ralphys** [linuxmint/mintupdate#126]
Changing icons in Preferences - Update Manager - Icons breaks if the folder where icons are stored or the icon (image) itself is renamed, moved or deleted.

![1](https://cloud.githubusercontent.com/assets/15816320/11259345/f5dfe226-8e2e-11e5-9dd4-9be5a21b42dc.png)

Logs xsession-errors:

File "/usr/lib/linuxmint/mintUpdate/mintUpdate.py", line 1210, in pref_apply
    iter = model.get_iter_first()
AttributeError: 'NoneType' object has no attribute 'get_iter_first'

...

(mintUpdate.py:2630): libglade-WARNING **: unknown attribute `swapped' for <signal>.
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintUpdate/mintUpdate.py", line 1491, in open_preferences
    prefs_tree.get_widget("image_updates").set_from_pixbuf(gtk.gdk.pixbuf_new_from_file_at_size(icon_updates, 24, 24))
glib.GError: Failed to open file '/home/[user]/Documents/update icons/updat-available.png': No such file or directory

While it is expected for the icons not to show if images have been deleted, it should at least default back to default icons. Instead, the previous image tries to be loaded, which causes icons or changes not to apply at all even if new icons are selected. Icons are there after unable to be set.

**Comment by alarangeiras** [comment]
Hi,

I've reproduced your issue and made a correction.
I've already made my pull request.

**Comment by JosephMcc** [comment]
In Mint 18 these icons will be handled by your icon theme just like any other icon.
