### ISSUE TITLE
Overlapping widgets in Kernel chooser

### ISSUE THREAD

**Issue by EduardDopler** [linuxmint/mintupdate#129]
The Kernel Chooser in mintUpdate 4.9.3.3 (and versions before) has overlapping widgets (see screenshot), at least in some localizations (German) and on a HiDPI screen with scaling factor 1.4. In prior versions, elements did not overlap yet, but the list widget showed only half an entry.
![mintupdate](https://cloud.githubusercontent.com/assets/9469003/11634532/541adf94-9d11-11e5-9313-a8bcd11eea4c.png)

As I see it, the only solution without limitting the length of the warning (or its font size) is to either
 - hide more of the text behind the expander,
 - increase the default window size (is 800x600 already…) or
 - show the text in a dialog one has to dismiss everytime when opening the kernel window. This way the window itself becomes cleaner.

**Comment by JosephMcc** [comment]
Closing this since the kernel page has seen a complete revamp for Mint18. MintUpdate as a whole has been ported to gtk3 so it will also have much better HiDpi support.
