### ISSUE TITLE
Kernel manager closes after each operation

### ISSUE THREAD

**Issue by hayounav** [linuxmint/mintupdate#130]
When installing/removing kernels through the Mint Update kernel manager window, the window closes automatically after action confirmation, once the authentication prompt pops up.

**Comment by xenopeek** [comment]
If #309 would be implemented, this issue would be less important.

**Comment by kneekoo** [comment]
Especially in driver compatibility cases, where the user have to install multiple kernels versions (4.4.x + 4.6.x + 4.8.x + 4.10.x) and test the hardware functionality later, closing the window after each install is annoying.

If reloading the window with the latest kernel information would take more effort, an alternative is to allow the multiple selection of kernels to install, so we can install them in one shot. It wouldn't directly solve the issue, but it would help.

An even better alternative would be to allow the users to mark as many kernels as they want for installation or removal, then click the **Apply** button to do everything in one step. The status bar would say "X kernels marked for installation and Y kernels marked for removal".

**Comment by gm10** [comment]
Manual multi-removal has been implemented in 5.4.2, automatic removal will be in the 19.2 release. 

Support for multi-installs has been added to the code but not the GUI for now, it wasn't considered a typical use case worth the added complexity that might in turn confuse the average user. If you need to install a large number of kernels at once you may be faster using synaptic or the command line.

Closing this for now.
