### ISSUE TITLE
UI's toolbar should be draggable

### ISSUE THREAD

**Issue by Rezonansowy** [linuxmint/mintupdate#131]
Window's toolbar should be draggable to move the program window.

**Comment by JosephMcc** [comment]
Your gtk theme should control this, not the application. I'm not on Mint at the moment to test mintUpdate but it should work when using the Mint-X theme.

**Comment by Rezonansowy** [comment]
@JosephMcc I use default theme and doesn't work. I made a mockup.
![draggable](https://cloud.githubusercontent.com/assets/6929363/12004152/98ade1da-ab42-11e5-87aa-6191a8f48dca.png)

**Comment by JosephMcc** [comment]
This now works on git master in the updated version using gtk3.
