### ISSUE TITLE
Handling APT in Linux Mint

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#134]
_This is intended as food for thought._
1. Start mintUpdate and let it download an install updates.
2. Start mintInstall and try to install something.
3. mintInstall will tell you another app uses APT: synaptic
4. mintInstall removes the Install button from the app page (although it shouldn't - **bug**)

The average user has no idea what APT or synaptic are. How can this be improved?
1. When you start APT-based mint tools, they should check if other apps use APT.
2. If other apps use APT, the mint tools should inform the user (hint bar as the mintUpdate mirror selector) that the installer system is already in use and they should wait for the existing tasks to finish before proceeding.
3. If the user doesn't read the warning and still tries to install, the same message can be displayed in a modal window.

**Other thoughts**
1. The user is informed that the application makes use of the installer system and that the application has been placed in the queue and will be installed as soon as possible.
2. mintInstall already has a queue but it has no idea that mintUpdate is doing stuff. What if it knew and it would display the installing of updates in the queue? What if you could even cancel the updates from the mintInstall queue?
3. What if this queue system would be a separate component that any mint tool or add-on would be able to access? This way, one could even write a Cinnamon applet to show the queue, its operations and even allow the user to interact with it (cancel tasks, pause the queue etc)

Your thoughts? Please share.

**Comment by gm10** [comment]
As far as it concerns mintupdate it has been addressed here: https://github.com/linuxmint/mintupdate/commit/d5f75224df9029812114c72e893f4b487da760a8

The mintinstall stuff should go into a mintinstall issue, if still relevant - the queue seems to work fine, just the lack of messaging isn't ideal.
