### ISSUE TITLE
Preconfiguring wireless regulatory domain on install

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#135]
At least when installing a new system, setting the wireless regulatory domain should be as easy as this:
> sudo iw reg set \`wget http://ipinfo.io/country -qO -\`

It would be nice if the environment variables would have the ISO 3166-1 alpha-2 code but even if it did, when you travel to other countries you need to get the info off the net. For this, an applet or a Network Manager plugin would do the job. It would be elegant if Network Manager would handle this graphically so the users can also switch countries manually if necessary, but there's [no sign of this yet](https://wireless.wiki.kernel.org/en/developers/regulatory/crda#changing_regulatory_domains).

Can this be dealt with in Mint in some form?

**Comment by JosephMcc** [comment]
I don't have much knowledge about what you are talking about here. What does it have to do with mintUpdate?
