### ISSUE TITLE
Add source info to description field

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintupdate#144]
I have quite a few PPAs and repos enabled on my system and it would be nice to know which source the update is coming from, as i may want to choose not to install it from that source. Sometimes i wonder this and open up synaptic to check, which wastes time.

**Comment by EduardDopler** [comment]
See https://github.com/linuxmint/mintsources/pull/69

**Comment by philipzae** [comment]
Somewhat relevant but not the same thing as that focused on knowing why the PPA was added (i had similar problems remembering why), while this is focused on knowing what source the update is coming from.

**Comment by xenopeek** [comment]
This has the same goal as #77, but implements it differently (adds the origin to the description instead of as a separate column).
