### ISSUE TITLE
No means of activating an already installed kernel

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintupdate#145]
If i select a row of a kernel that is present on my system, i'm only given the option to remove it and no option to change to that version.

**Comment by JosephMcc** [comment]
Looks like the same issue as https://github.com/linuxmint/mintupdate/issues/81

**Comment by philipzae** [comment]
Unfortunately it isnt the same issue.

**Comment by JosephMcc** [comment]
How is it really different? Both issues are about not being able to set the kernel to use from the settings window.

**Comment by philipzae** [comment]
Reading over it again, it does sound similar. :D
