### ISSUE TITLE
[Feature Request] Release an update that checks if user has Feb 20th backdoor installed

### ISSUE THREAD

**Issue by pizzadude** [linuxmint/mintupdate#146]
I'm not sure if this is the right place to post this, but I have an idea on how to alert users if the backdoor from Feb 20th is on their system:

Release a package to the Linux Mint repo, that is installed on everyone’s systems once they update. Once installed, it detects if the backdoor is on their system, and if it is, it displays a permanent message box asking users to reinstall.

**Comment by EduardDopler** [comment]
This was addressed in b51c5b8.
