### ISSUE TITLE
Some update manager option combinations break Auto-Refresh options

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/mintupdate#167]
When selecting the option for "Only show a tray icon when updates are available or in case of errors" and "Hide the update manager after installing updates" this seems to essentially break the users auto-refresh options.

For example, I have the option "First, refresh the list of updates after: " set to 30 minutes
I have the option for "Then, refresh the list of updates every: " set to 4 hours.

When I start my machine after 30 minutes the shield icon dutifully tells me I have updates to run, being a good user I install them immediately, let them install and thanks to my settings the update manager window goes away and the shield icon disappears. 30 minutes later, often (obviously depending on which updates are available) I get informed again I have more updates waiting.

I assume that when both of the previous options are selected (at least in my limited testing it only seems to happen with both selected) basically the update manager is completely restarting itself when updates are done installing therefore continually looping through the "First, refresh the list of ........." setting and often not reaching the "Then, refresh the list......." option.

I would argue that this shouldn't be the expected behavior.

**Comment by Cos-mo** [comment]
2 questions:

1. Which version of Mint?

2. Did there probably appear an update for the update manager itself? In this case the update manager has to re-launch itself after that.

The problem is, that reproducing the issue is very hard, as new updates in between of 30 minutes do happen very seldom.

Can you reproduce the issue if you disable the one or other settings, that you named in the first paragraph?

**Comment by brennanhm** [comment]
Hi there,

FYI: mintupdate generates a log in /tmp/mintupdate/ that records when the refreshes occur. That may help you to troubleshoot this issue.

By default, mintupdate automatically loads when the system starts. If the update policy has been set, mintupdate will do a refresh regardless of the times specified in the preferences, so the shield should show up soon if updates are available.

I tried to reproduce this issue on a fresh installation of Linux Mint 18 by doing the following:

1. Set the preferences as follows: 5 minutes for the initial refresh, 30 minutes for every refresh thereafter, as well as the two options specified in the OP's first paragraph.
2. Installed the first update (the latest version of mintupdate). As Cosmo mentioned, if mintupdate itself is updated the application will be restarted, and the initial refresh timer will be reset. 
3. Waited 5 minutes for the initial refresh to occur.
4. Installed all the remaining updates. Note that mintupdate does another refresh after updates are installed, but it shouldn't restart itself (except in the case that mintupdate is updated).
5. As per the mintupdate log, the scheduled refresh occurred 30 minutes after the initial refresh (not five minutes after the updates were installed).

[mintupdate_log.txt](https://github.com/linuxmint/mintupdate/files/475869/mintupdate_log.txt)

**Comment by imarkskinner** [comment]
I can't reproduce this anymore, so I'm going to close it.
