### ISSUE TITLE
After downloading updates, installing updates window steals focus.

### ISSUE THREAD

**Issue by BrianMoths** [linuxmint/mintupdate#168]
When you are using the update manager to install updates, and you tell it to apply updates, the updates begin downloading and a window comes up showing you the progress of the download. Then you will likely switch to something else. When the download finishes, a new window pops up and shows you the progress of the newly downloaded updates being installed. This install progress window steals focus, which is annoying, at least to me. I would prefer if the install window didn't steal focus. Instead we could just have different tray icons for the update downloading, update installing and installation complete phases of updating instead of the one tray icon for updating. Then the user can just let mintupdate do its thing until he sees the tray icon has changed to update is complete and then right click the tray icon to close the mintupdate.

**Comment by xenopeek** [comment]
Same issue as in #117?

**Comment by Yanpas** [comment]
+1

**Comment by BrianMoths** [comment]
> Same issue as in #117?

Yes, I believe it is the same issue.

**Comment by synthakai** [comment]
so, what's the progress on this? it is still bugging everybody who uses it...

**Comment by xenopeek** [comment]
Retested on Linux Mint 18.3. After clicking button to install updates I switched to another window (terminal) and mintupdate window didn't steal focus at any point during installing of the updates. Appears to be fixed.
