### ISSUE TITLE
LM 18: Size of the update policy window

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/mintupdate#170]
Users with a rather small desktop resolution - e.g. 800 x 600 pixel - can only see the policy window partially. Especially they cannot see the title bar and and not the 2 buttons at the bottom (Help & OK).

This leads for a number of newbie users to the result that they can do nothing. They only partially know how to move the window, to make these 2 buttons available.

Result: They cannot apply updates, some of them do not even know how to close the window (what does not solve the problem anyway).

Test system LM 18 64 bit Cinnamon, but this should probably not matter.

**Comment by JosephMcc** [comment]
I'd have to double check the actual size of the window but the minimum system requirement for all Mint versions is at least 1024x768. Doesn't mean it couldn't be better but a resolution of 800x600 isn't technically supported.

**Comment by Cos-mo** [comment]
1024 x 768 is far too much. We have seen a number of complaints in the forum.

The real bad thing is, that some users are stuck at this. They do not know, how to solve their problem. The result is, they do not apply the updates - they simply cannot - and they browse with an unsecure Firefox. The longer time the release time of Mint 18 is back (for Cinnamon and Mate editions now 2 months), the more vulnerabilities have accumulated in the browser (not to speak about other packages). But the browser is for those users the only way, to search or ask for help about this. I have read, that some users simply believe, that the UM does simply not work at all, because all visible elements are not clickable and there is no visual hint, that there might be at the bottom something more on the dialog.

I have missed to ask those users, what their desktop resolution actually is; my 800 x 600 example is the one, which I used for reproducing the issue. I will ask them in the future.

Despite of some other questions about the policy (I consider GitHub as the wrong place to discuss them) I consider this issue as [b]urgent[/b] and it gets worse, the longer the release date of Mint 18 is back. For Mint 18 it is obviously too late to do anything in principle (except to release a V2 of the ISO files), but for Mint 18.1 this has to get corrected.

**Comment by JosephMcc** [comment]
> 1024 x 768 is far too much. We have seen a number of complaints in the forum.

I don't want to seem rude but maybe people should actually read the minimum system requirements before they start complaining.

I'm going to mark this as a feature request since I don't believe it's a bug when it's being run on something that has been stated is unsupported.

**Comment by Cos-mo** [comment]
I also don't want to be rude. But if the computer / monitor does not provide a higher resolution, should we now tell those users in the forum, that they missed to read the blog with the release announcements? This especially in the case, where the content of the page is not so big, that the buttons could get placed further up?

Note: This is not my complaint (the resolution of my computer is far beyond the requirements), but it is a problem I came about during my Mint support in the forum.

Note also, that we came there about users, who have no idea, how to move a window via alt-key-mouse-move or alt-F7. So even if they should have read the blog, they would be lost. They are even that: newbies. Newbies (mostly coming from Windows) are used, that they see a scroll bar, if the content extends the size of a window. Here they see nothing like that and following that they assume, that there is nothing more and as the next consequence they assume a bug.

A user-friendly system like Mint should not give newbies such a barrier, especially at the very beginning - the UM stands in the beginning of the usage.

**Comment by brennanhm** [comment]
Hi there,
We can free up some space by hiding the toolbar and menu bar in the policy configuration page. We can also move the buttons higher up by adjusting the vertical alignment in the glade configuration file. I'll submit a PR for this...

**Comment by NikoKrause** [comment]
The improvement form brennanhm has been merged. Is it still an issue?

**Comment by JosephMcc** [comment]
Closing this. There are minimum system requirements listed with every release.

**Comment by Cos-mo** [comment]
> The improvement form brennanhm has been merged. Is it still an issue?

Without a release impossible to answer.

@JosephMcc 
You repeat yourself. Tell this in the form to the users, which I mentioned above.

**Comment by JosephMcc** [comment]
> Without a release impossible to answer.

Did you bother trying it? The change was merged months ago.

> You repeat yourself. Tell this in the form to the users, which I mentioned above.

I don't need to. If users want to run machines that don't meet the minimum system requirements they are going to have to learn to workaround certain things. Learn to use Alt + mouse drag for example.

**Comment by NikoKrause** [comment]
> if the computer / monitor does not provide a higher resolution, should we now tell those users in the forum, that they missed to read the blog with the release announcements? 
A user-friendly system like Mint should not give newbies such a barrier

If you buy a game on DVD or Steam there are also some System Requirements information. If you try to run it anyway on a machine, which does not meet those minimum requirements and the game lags, you have learnt an important lesson. Buy games, which are made for your machine or buy a better machine if you really want to play the game.

Windows has also minimum system requirements. I remember, when you wanted to upgrade to Windows 10, it said, "Wait a minute. We check if your system meets the requirements needed to run Windows 10." And if it didn't it said "Sorry but you can not upgrade"

I think it's a very low barrier to expect from users to read the system requirements, since it's something very essential for software (games, OS, etc). And if somebody tries anyway and run into problems, then yes, in my opinion you should tell those users that they have missed to read the system requirements. And that they can use Alt + mouse drag.
Or look for an OS, which meet your requirements.
E.g. [Linux Mint Xfce](http://blog.linuxmint.com/?p=3281)

And looking at [LM KDE anouncement](http://blog.linuxmint.com/?p=3282) it even says:
> 1024×768 resolution (on lower resolutions, press ALT to drag windows with the mouse if they don’t fit in the screen).

**Comment by Cos-mo** [comment]
> Did you bother trying it? The change was merged months ago and is in the 18.2 beta.

In this case something went quite wrong. I have set my 18.2 test system (in a VirtualBox environment) to 800 x 600 and there is still no improvement since I opened the issue. Without alt-F7 or alt-mouse drag there is no way out of this window. No scroll box, nothing else.

**Comment by Cos-mo** [comment]
@NikoKrause 

Reread my comments above, especially  the one from 30.8.16 again: There are newbies out there, who have no knowledge about moving a window with the help of the alt key. If you would do as much support as I do you would know this.

Of course we tell them how to use the alt key; at the moment there is no alternative to get them out of this display.

If I follow you and JosephMcc I would have to tell them in the forum, that this oversized window without vertical scroll bar (vertical scroll bars for content, that does not fit into a window is a quasi-standard since 30 years or so) is not a bug, but a designer decision to point the user on the hard way, that the have missed to read the release note and that their computer is not able to use Mint (although all except this silly window is actually usable). As a user with a given hardware simply possibly cannot switch the resolution so easily as I can on a virtual machine for testing, the consequence is: The developers have decided, that you have the wrong computer and you need to use another distro (or for the next 2 years LM 17.x) - or buy another computer. - My understanding for giving support is a different one.

Regarding your last part regarding xfce: I don't use it and therefore it does not make sense for me to test the current xfce beta. But I am more than astonished: Either you are right and the problem with this policy window does not exist in the xfce edition; than the consequential next question is, why don't have the other editions the same solution for the policy window? Or the policy window shows in xfce just as I see it in the Cinnamon edition, in this case your hint to xfce would be simply wrong.

**Comment by NikoKrause** [comment]
Looking at LM 18.2 right now with resolution 800x600. It's possible to change the height of the Window. And if you make it as small as possible the buttons are visible pretty good

**Comment by NikoKrause** [comment]
But what about people, who run this on resolution 640x480? There you have even more problems.

**Comment by Cos-mo** [comment]
> Looking at LM 18.2 right now with resolution 800x600. It's possible to change the height of the Window. And if you make it as small as possible the buttons are visible pretty good

I confirm. But obviously so far away from obvious, that it took a complete year, until somebody gave this solution.

Interesting observation about this: If I drag the window smaller from the top border and then move it some way up, to make the buttons visible, they are now much nearer to the policy choices and the huge empty space between them is gone. If I drag the upper window border again in the opposite direction (to give it higher height) the meaningless empty space gets back. So it appears, that there is something wrong.

> But what about people, who run this on resolution 640x480? There you have even more problems.

The 800 x 600 value is not my choice, but the result from support requests. Obviously there are computers with such a display in the wild.

**Comment by NikoKrause** [comment]
Ok I checked with Xfce. Obviously it has the same problem. Since Xfce says in its System Requirements "Graphics card capable of 800×600 resolution" that's probably an issue then. If it hasn't been for that, I probably wouldn't have looked into it.

I found a "2 character" (1 liner) solution, i.e. just changing a number in the code suffices to fix this problem. I create a PR and hope it gets merged.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintupdate/commit/45c98ac7b2821dae8d306529ae39a0d5c98a47f4

**Comment by Cos-mo** [comment]
It is closed too early. The respective update just arrived here. I have applied it with all available Cinnamon / Nemo updates and rebooted the system. Than set the display to 800 x 600. The result is exactly as before.

Specs:
Mint 18.2 Cinnamon 64 bit
Environment: VirtualBox.
