### ISSUE TITLE
Mintupdate shows html number for special characters (including accents)

### ISSUE THREAD

**Issue by f380cedric** [linuxmint/mintupdate#172]
Hi all,

I have a tiny issue with mintupdate. From mintupdate, you can have description, and sometimes, some packages have a french translation. But, accents are not correctly displayed, for example, an "é" is showed with is html number `&#233;`. Mintupdate GUI is correctly set because I have "Édition", "Tout sélectionner", etc. I think it is because the description is downloaded from upstream (ubuntu upstream?) and the encoding/decoding part is not perfectly set.

Linux Mint version: 18
Mintupdate version (from dpkg): 5.1.0

![mintupdate](https://cloud.githubusercontent.com/assets/10184070/18023954/875201a8-6c00-11e6-930c-502fc7773e38.png)

**Comment by Cos-mo** [comment]
See #114
