### ISSUE TITLE
Linux Mint 18 KDE (Sarah) x64

### ISSUE THREAD

**Issue by yura253** [linuxmint/mintupdate#177]
Icon MintUpdate version 5.1.0 is not clickable left mouse button in system tray,

**Comment by yura253** [comment]
If  installed MintUpdate version 5.0.0 - then icon is clickable left mouse button in system tray,

**Comment by hrvoojex** [comment]
If I upgrade the system via terminal, UpdateManager in systray should be synced also and not showing new updates anymore

**Comment by xenopeek** [comment]
Retested on Linux Mint 18.3. Appears to be fixed.
