### ISSUE TITLE
 History update needs an update!

### ISSUE THREAD

**Issue by johnbklyny** [linuxmint/mintupdate#179]
please add level security on each update i installed

**Comment by icarter09** [comment]
@JosephMcc can this ticket be closed? This feature is now present in the Update Manager.

**Comment by JosephMcc** [comment]
Is it? I don't see where it shows this in the history window? It could be I just missed this. I'm going to go ahead and close since it's been sitting here for almost 2 years and there doesn't seem to be any real interest.

**Comment by icarter09** [comment]
@JosephMcc Good call. I was referring to the "add level of security on each update" suggestion. I think that used to not be present on past versions, where the security level was shown for each update.
