### ISSUE TITLE
brightness control needs a fix

### ISSUE THREAD

**Issue by johnbklyny** [linuxmint/mintupdate#181]
when i scroll on my mouse all the way to "screen off" mode which i do like that feature but at times you move your mouse away you can't seem to find the brightness control when the screen is black to scroll back up on the mouse i would have to try to get it lite again by messing with my mouse with the dark "screen off" mode

**Comment by JosephMcc** [comment]
This is the place for posting issues for the mint update application only. Not really just for general issues. This is something probably best brought on the bug tracker for the desktop environment that you use.
