### ISSUE TITLE
Inform user about obsoleted kernel

### ISSUE THREAD

**Issue by xenopeek** [linuxmint/mintupdate#185]
During the life-cycle of a Linux Mint release various non-LTS kernels become available for it for enablement of newer hardware. These generally become obsoleted and unsupported before EOL date of the Linux Mint release. Right now the user is not informed in any way that these kernels are obsoleted.

I suggest two changes to mintupdate:
1. If the user is using an obsoleted kernel installed from the official repositories, display a notice in mintupdate to inform the user that their kernel is no longer supported. This could be done just like the notice displayed for changing to a local mirror (perhaps in a different color). The user could be recommended to upgrade to the next available LTS kernel, or downgrade to the previous LTS kernel.
2. The second change would be to change the View > Linux kernels dialog so it shows the support status of all available kernels. Right it shows obsoleted kernels for installation without any notice of that status. Users with hardware issues might want (for a little while, while getting support to fix it) to stay on an obsoleted kernel.

For example Linux Mint 17.2 shipped with 3.16, Linux Mint 17.3 with 3.19, and 4.2 is also available for Linux Mint 17.x releases. These kernels are obsoleted and [no longer supported](https://wiki.ubuntu.com/Kernel/Support#A14.04.x_Ubuntu_Kernel_Support). Looking ahead to Linux Mint 18.x releases the same is likely going to happen when looking a the [kernel support schedule](https://wiki.ubuntu.com/Kernel/Support#A16.04.x_Ubuntu_Kernel_Support) (e.g., early 2017 kernel 4.8 will become available for Linux Mint 18.x but it will become obsoleted and unsupported 6 months after).

Ideally a change to mintupdate for Linux Mint 18.x would be backported also to Linux Mint 17.x, given the years left on Linux Mint 17.x till EOL date.

**Comment by clefebvre** [comment]
Fully agree.

**Comment by xenopeek** [comment]
Looking at the code, I think this kinda has been implemented from Mint 18.2. When the active kernel version is from a newer release than the LTS kernel, but from an older release than the current HWE kernel, the users gets shown the current HWE kernel version as a security update. As per the rolling-HWE kernel mechanism.
