### ISSUE TITLE
Level down driver updates (here: Nvidia)

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/mintupdate#187]
Since the last Nvidia driver update for the graphics card there is a tremendous number of complaints about that driver - until a completely unusable system.

I think, that  the level system in UM is to prevent those situations. But this protection system must fail here, because the drivers are set as level 3 updates.

The description for level 3 updates (where the driver gets listed) says, that those updates are supposed to be safe. Quite obviously this is not the case. Also it seems logical, that such a hardware related software is merely supposed to give possible problems.

So I think, that it this (probably also other) drivers should be set into level 4 or even level 5. Level 3 for them lead too many users into a trap, where they are not able to come out alone.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintupdate/commit/fb10f8cff2f508e1227f4ddda72fbb9e809b407e
