### ISSUE TITLE
White font after recent update of update manager

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mintupdate#189]
Yesterday or amybe earlier mint-update was updated and now the font of the description has become white. 
![12](https://cloud.githubusercontent.com/assets/7345761/20454980/0a0f473e-ae61-11e6-8dee-609cc8c4dd8a.png)

**Comment by JosephMcc** [comment]
I'm seeing the same thing.

**Comment by monsta** [comment]
Maybe it was a theme issue? I didn't see this.

**Comment by Yanpas** [comment]
Updated to mint 18.2, can't reproduce, seems to be fixed 
![image](https://user-images.githubusercontent.com/7345761/29339198-d9e67f1a-8221-11e7-91dd-5a35de04411b.png)
Using the same mint default theme

**Comment by Yanpas** [comment]
Facing this issue again 
![image](https://user-images.githubusercontent.com/7345761/29789723-b14a0cf2-8c3f-11e7-8645-eb83943d9631.png)

Can't understand what is the reason

**Comment by Yanpas** [comment]
I've restarted app and the font is black again. I guess it's rather GTK bug than mintupdate

**Comment by JosephMcc** [comment]
This sort of thing can happen if you change themes while an application is open. Not everything will always update to the new theme until the application is restarted.
