### ISSUE TITLE
Logger prints python exception type instead of its message

### ISSUE THREAD

**Issue by dqgls** [linuxmint/mintupdate#195]
Here's a section of a log from `/tmp/mintUpdate/`:
```
12.18@16:20 ++ MintUpdate is in tray mode, performing initial refresh 
12.18@16:20 ++ Starting refresh (including refreshing the APT cache) 
12.18@16:20 ++ Auto-refresh will happen in 0 minutes, 2 hours and 0 days 
12.18@16:20 -- Exception occurred in the refresh thread: <class 'subprocess.CalledProcessError'>
```

The problem is in the way exceptions are handled in [`mintUpdate.py`](https://github.com/linuxmint/mintupdate/blob/master/usr/lib/linuxmint/mintUpdate/mintUpdate.py). Instead of simply passing `sys.exc_info()[0]` to logger some exceptions should be handled according to their specific class.

For example, in the above case of `subprocess.CalledProcessError` the info should be read from `e.cmd` and `e.output`, maybe something like this:

```
except Exception as e:
    # ...
    try:
        raise e
    except subprocess.CalledProcessError:
        error_msg = "cmd='%s' output='%s'" % (e.cmd, e.output)
    except:
        error_msg = sys.exc_info()[0]
    self.application.logger.write_error("Exception occurred in the refresh thread: " + error_msg)
    # ...
```

https://docs.python.org/2/library/subprocess.html#subprocess.CalledProcessError

**Comment by bendover22** [comment]
+1 for this error in Mint 18.1.  I believe? the red updater tray icon, or "Exception" error began a couple of months after installing LM.
Also tried changing from the default Official Repos ( main & base)  to local ones.  

Is it possible this message is related to any of the selected servers being temporarily or permanently unreachable - official, PPA or Other?

I just changed my main repo server (again) - was reported unreachable.  Re-ran Refresh and for now don't see the Exception... error, nor a red Updater tray icon.

**Comment by gm10** [comment]
I should have cleaned most/all of those up in LM19 by now as well as improved the error messaging in several cases.
