### ISSUE TITLE
'If a regression breaks something, I'll fix it'

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/mintupdate#196]
There are two problems with this text.

(1) _Who_ will fix it? I, the Update Manager? No. The intended meaning is: the user. Yet, that fact is not made very clear. The current wording will cause confusion.

(2) Some users will not know what 'regression' means. Also, it would be easy to use another word here - such as 'problem'. Given that combination of facts, surely the inference is: change the word.

**Comment by JosephMcc** [comment]
I don't know, this seems a bit like some extreme nit-picking. The first one seems pretty clear to me. For the second, regression is hardly that uncommon of word. If you don't know what it means, look it up.

**Comment by Qantas94Heavy** [comment]
I don't know whether this was deliberate or not, but the use of 'complicated' language discourages people from selecting the option unless they know what they're doing.

**Comment by ACinnamonUserInUK** [comment]
@JosephMcc 

It seems to me that the more serious problem of the two problems that I identified is the one that I numbered _1_, not the one I numbered _2_.

**Comment by JosephMcc** [comment]
For one, I wasn't the one that closed this. For another, I don't see the current wording as a problem.
