### ISSUE TITLE
If package has no description information it is displayed wrong (security bug)

### ISSUE THREAD

**Issue by mxa** [linuxmint/mintupdate#203]
A package can look like it is a different one. This might trick you into installing an update by thinking that it is for a different package.
I suspect this bug is caused by an empty description field.
Reproducible with the photoflow-git package from the [dhor/myway](https://launchpad.net/~dhor/+archive/ubuntu/myway) PPA.
Here it looks like we are updating VLC, but in fact it is the Photoflow package. VLC was the last package updated.
![mintupdate](https://cloud.githubusercontent.com/assets/1220707/22284885/87687b58-e2e9-11e6-8f1d-b08f2d8dc892.png)
![photoflow](https://cloud.githubusercontent.com/assets/1220707/22284890/8dd72ade-e2e9-11e6-980e-4c19f6e54689.png)

**Comment by mxa** [comment]
See also this bug and video https://bugs.launchpad.net/linuxmint/+bug/1639456  https://vid.me/khGr

**Comment by icarter09** [comment]
@mxa is this issue still occurring? I'm having a hard time duplicating this bug.

**Comment by mxa** [comment]
@icarter09 Sorry, can't test, I moved on to Kubuntu since.
