### ISSUE TITLE
Sizes shown are smaller than the real size

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintupdate#205]
mintUpdate 5.2.0 on LMDE2

For example, a Linux kernel is shown (in the top half of the main mintUpdate window, the list of installable updates, the Size column) as 1 MB, but Synaptic shows a Linux kernel (not the same one) as on-disk=164MB, download=34MB.  

To duplicate, you can add the following contents to /etc/apt/sources.list.d/ 
`deb http://mirrorservice.org/sites/ftp.debian.org/debian/ jessie-backports main contrib non-free`
The update currently shown is Linux kernel 4.9.2-2~bpo8+1

Updates "linux-base" and "linux-latest" are even worse, being shown as 18KB & 12KB.

**Comment by xenopeek** [comment]
These packages you mention are meta packages. Indeed those are very small as they have little files but control files for the list of their dependencies. Their sizes are correct (e.g. linux-base package size is 18KB https://packages.debian.org/jessie-backports/linux-base).
