### ISSUE TITLE
Enhancement:  Show both download-size & size-on-disk

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintupdate#206]
Clarifying download-size vs. size-on-disk would be nice.  Those could be 2 separate columns in any list view that currently has just "Size."  

Some users may be tight on disk space or may have a low-bandwidth Internet connection, so those users would like to know which size is which.  

This info is currently available in Synaptic's package properties dialog; surely mintUpdate can do this too.  If this is deemed to be more info than most non-technical users want, then one of the columns could default to not visible in the View > "Visible columns" list.

**Comment by gm10** [comment]
Was going to add this (see #504) but Clem thought this one was too niche, so it won't be happening, sorry.
