### ISSUE TITLE
Long description of multi-package update may be specific to only 1 of the packages

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintupdate#209]
mintUpdate 5.2.0 on LMDE2

Using the following in /etc/apt/sources.list.d/
`deb http://mirrorservice.org/sites/ftp.debian.org/debian/ jessie-backports main contrib non-free`

mintUpdate, in the long description of the "cups" update (in the bottom half of the window, the Description tab), shows 2 paragraphs, which are the entire long description of the "cups" package in APT.  The problem is that the 2nd paragraph is specific to the "cups" APT package & doesn't apply to the other 12 APT packages in the Linux Mint "cups" update.  

So in long descriptions, I suggest automatically checking for beginning text that is the same in the greatest number of APT packages, and showing only that text (in this case, the first paragraph).  

What I mean by "the same in the greatest number of:"  
(There may be methods already available that do this or sections of it; this is only pseudocode.  
And the pseudocode may contain bugs.  
And you probably already know what I mean anyway.  
I just want to be clear:)  
1. Find the first pair of packages whose descriptions have a common prefix (longer than some arbitrary threshold like 10 characters).  
2. Check for this prefix in all the packages.  This may cause the common prefix to get a little shorter.  
3. Any package that doesn't start with the same common prefix at all (i.e., its commonality is less than the arbitrary threshold) is put onto a different list, and doesn't cause the common prefix to get shorter.  
4.  Any package that **does** start with the current common prefix causes a count to be incremented for that common prefix.  
5. The whole process (including putting onto a different list) is repeated until all packages in the update have been checked.  Some packages might not have a common prefix with any other package.  
6.  Whichever common prefix has the highest count is used.  If there is a tie, then maybe the prefix is used whose APT package names have a common prefix that is the longest prefix string of the Linux Mint update name, and if still a tie, then whichever APT package name has one of the common description prefixes and is alphabetically first.

**Comment by dg1727** [comment]
Presumably each Linux Mint update is really "one APT package plus that package's dependencies that are at a new version in the repo."  If so, then probably you could just start with the long description from that one package, and find the shortest prefix (longer than the arbitrary threshold of 10 characters or whatever) that is in any of the other APT packages in the update.

**Comment by gm10** [comment]
#207
