### ISSUE TITLE
Issues if dependencies in installed version vs. new version are different

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintupdate#211]
mintUpdate 5.2.0 on LMDE2

Using the following in /etc/apt/sources.list.d/
`deb http://mirrorservice.org/sites/ftp.debian.org/debian/ jessie-backports main contrib non-free`

mintUpdate shows an update called "btrfs-progs" whose only APT package is listed as "btrfs-tools".  (There are a couple of other issues also, which I'll mention in a numbered list below.)  

I think many users would expect that, if the Linux Mint update name looks like an APT package name, then the list of APT packages should include a package with that name.  In this case, the list of APT packages should include "btrfs-progs," but it doesn't.  

The apparent cause is:  In APT, the new version of package "btrfs-tools" depends on package "btrfs-progs", but the currently installed version of package "btrfs-tools" did not.  

From top to bottom in the GUI:  (and no, I haven't looked at the Python code) 
1.  The update name (btrfs-progs) seems to be from the sorted list of APT package names of (the new version + dependencies); 
2.  The short & long descriptions seem to be from the new version of the currently installed APT package (btrfs-tools, whose new version is a virtual package, whose description doesn't say what the package does); 
3.  The list of APT packages seems to be for the currently installed version of the APT package (btrfs-tools).  

I think these should be changed as:  

- (1) and (2) should come from the same place.  Algorithms suggested in #207 & #209 may affect which package of a multi-package update is used for this text.  I suppose the code should first try to take (1) and (2) from a non-dependency (btrfs-tools).  The new version should be used, since the user is interested in what is about to be downloaded.  
- That can result in the description saying only, e.g., "This is a transitional dummy package," so you may want code that checks for that kind of text and, if it is found (**without** an explanatory suffix like "... for utilities for Btrfs ..."), tries to get a description from the dependencies (per #209); 
- (3) should come from the new version, not the currently installed version.  

These items seem similar to, but not the same as, #203

**Comment by gm10** [comment]
To not close this without a word after it has been pending for so long: The list displays the source package name.What you call "apt packages" is listed in the description currently (will be a separate tab in the future).
