### ISSUE TITLE
Some update names don't seem to come from anywhere

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintupdate#212]
mintUpdate 5.2.0 on LMDE2

Using the following in /etc/apt/sources.list.d/
`deb http://mirrorservice.org/sites/ftp.debian.org/debian/ jessie-backports main contrib non-free`

The following update names:  
- `llvm-toolchain-3.5`
- `pillow`
... don't seem to match any APT package names, neither in Synaptic nor in `dpkg-query --list`

mintUpdate lists those updates as consisting of the following APT packages.  Maybe the updates should be named after the following instead of the names given above:  
- `libllvm3.5`
- `python-imaging` or `python-pil`

As I noted in #211, 
> I think many users would expect that, if the Linux Mint update name looks like an APT package name, then the list of APT packages should include a package with that name.  

I'm aware that maybe the names `llvm-toolchain-3.5` and `pillow` do exist somewhere in APT and I just don't know where to look for them.

**Comment by clefebvre** [comment]
Are they the name of the source packages?

**Comment by xenopeek** [comment]
llvm-toolchain-3.5 is a source package: https://packages.debian.org/source/jessie/llvm-toolchain-3.5. pillow is as well: https://packages.debian.org/source/jessie/pillow.

Where Update Manager sees a package from a source from which multiple other packages are built, it shows all those package updates as one item and uses the source package name.
