### ISSUE TITLE
Minor layout issue in "will trigger additional changes" dialog

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintupdate#213]
mintUpdate 5.2.0

In the "This upgrade will trigger additional changes" dialog, the top listview & bottom listview are both the same height, but sometimes the top one has lots of unused space while the bottom one doesn't have enough space & uses a vertical scrollbar.  

Possible solutions:  
- If one windowpane would have blank space vertically, then that pane should be no taller than needed to show its text.  
- The panes can be laid out left-and-right instead of top-and-bottom.

**Comment by xenopeek** [comment]
This does not appear to be an issue on 5.3.2.

![Screenshot](https://i.imgur.com/aUbLF0T.png)
