### ISSUE TITLE
Display details about failed downloads with or before the continue prompt

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#215]
**Symptom:** When one or more packages can't be downloaded, mintUpdate asks the users if they want to continue the update without the missing packages.

**Problem:** Without details about the missing packages you can't even guess if updating is a good idea or not, considering some missing package could be a dependency of another, and updating might leave some programs in a dysfunctional state.

So all you can do to stay on the safe side, is to reply "No" to continuing the update. Once you answer, you get a window informing what went wrong, but at this point it's too late and you have to click "Update" and input your password again.

**Comment by gm10** [comment]
Thanks for the feedback. I don't think I've ever seen that window but it would have to be supplied by Synaptic, which is causing a number of problems. Hopefully we'll end up replacing it eventually with code we've got full control over, but until then there's nothing to be done about this one. 

That said, your described problem shouldn't be a real problem, I'd be surprised if Synaptic went ahead and installed a package without being able to meet the dependency (it's theoretically possible but the package management system doesn't allow this by default).
