### ISSUE TITLE
MintUpdate isn't updating my kernel.

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/mintupdate#217]
I have Linux Mint Xfcee 18.1.
Linux Mint default use kernel 4.4 LTS.
I changed kernel to version 4.8.
I received kernel update 4.4 series but I do not have kernel update 4.8 which I use (and I had available update for 4.8).
When I use apt, i have update kernel 4.4 but not 4.8 (apt and MintUpdate not see kernel update to 4.8).
Is It bug or feature?

I think that mintUpdate should be update my kernel linux which I use.

I attach screenshot.
http://imgur.com/a/583sg

**Comment by ewangi** [comment]
Do you have any 4.4 kernels installed at all? If so, try removing them. If not, I agree that you shouldn't be receiving 4.4 updates if you don't actually have a 4.4 series kernel installed.

**Comment by awy1076** [comment]
@pyroxar 
your image shows the update for "linux-libc-dev" to 4.4.0-67. But when you select a 4.4 kernel at boot, you will become a deja-vue, nearly the same picture except "uname -r". 
After rebooting to 4.8 you will realise that the 4.8.0.-41 is still installed.

As I noticed mintupdate suggest the updates to the current kernel selected while booting.
If kernel 4.4 is activ (have a look to "uname -r") then mintupdate updates the kernel 4.4.

**Comment by calexil** [comment]
related #219

**Comment by pyroxar** [comment]
I have no kernel 4.4. I removed them. I refresh mintUpdate and i have still kernel update from 4.4 series but I have and use only linux from 4.8 series. #bug
http://i.imgur.com/3PBVPUr.png

If i will changing kernel which i use, mint should give update for kernel chosen by me. 
Automatically removing not used kernels when i install newer?
#feature request

**Comment by awy1076** [comment]
What I forgot to write: I got the same issue. The update for "linux-libc-dev" is displayed as "Linux-Kernel 4.4.0-67"
The Update for kernel 4.8 is **not shown, but made!**

**Comment by pyroxar** [comment]
It is amazing. My linux kernel 4.8 series was updated by MintUpdate!
I had "only" purge all the others kernels and a few days later, i have update (kernel 4.8.42 was released a week ago).

MintUpdate must be better to deal with kernels.
- purge all older kernels and updating only kernels with currently used series.
#feature request

**Comment by clefebvre** [comment]
Hi,

Please try again with version 5.2.1.1.

**Comment by calexil** [comment]
@clefebvre 

while 4.8 kernels are installed no updates are received for them, instead mintupdate 5.2.1.1 recommends
4.4 kernels, somewhere mint is held back. 

![screenshot at 2017-03-23 14-54-08](https://cloud.githubusercontent.com/assets/3487071/24265231/2fab5fc6-0fd9-11e7-9cb7-fba7f9dfad34.png)

![screenshot at 2017-03-23 14-54-14](https://cloud.githubusercontent.com/assets/3487071/24265236/336191ee-0fd9-11e7-8f7b-518468265a6d.png)

**Comment by calexil** [comment]
#221 fixes some of the confusion since it shows more details about the package.

But I am pretty certain, 4.8 kernel updates are not coming through(even before I blacklisted 'linux' because of how annoying it was to be recommended 4.4 kernels constantly while on 4.8)

**Comment by Schallaven** [comment]
I am actually pretty sure that you see the "libc-dev" update there, which is not the kernel. 4.8 kernel updates are grouped _into_ this package (that way they are "hidden"). If you click on the package line look at the very bottom of the description; all including packages should be listed there - after updating mintupdate to 5.2.11 (which does not have my proposed fix from #221 it shows the very same "kernel update 4.4" in the list and the packages included are:

"Diese Aktualisierung enthält 5 Pakete:  linux-headers-4.8.0-42 linux-headers-4.8.0-42-generic linux-image-4.8.0-42-generic linux-image-extra-4.8.0-42-generic linux-libc-dev".

If I apply my fix the packages are separated like they should be.

**Comment by pyroxar** [comment]
I received update for my kernel 4.8 but this update was signed as kernel 4.4.
![screenshot_2017-04-01_12-55-34](https://cloud.githubusercontent.com/assets/23406555/24578151/0684f93c-16db-11e7-84f0-d9549d573545.png)
![screenshot_2017-04-01_12-55-42](https://cloud.githubusercontent.com/assets/23406555/24578153/0a463d4c-16db-11e7-84cb-7af79090ab4e.png)
