### ISSUE TITLE
Purge kernels rather than remove them

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintupdate#218]
At the moment, when selecting Remove for an installed kernel, the relevant kernel packages are removed from Mint but their configuration files are left.

Is there any particular reason for this behaviour, or could these packages be purged instead?

At the moment, after a long period of use along with associated upgrade and removal of kernels, there are a fair number of seemingly unnecessary residual kernel configurations left on a Mint system due to this behaviour.

**Comment by calexil** [comment]
related #217 #219

**Comment by calexil** [comment]
nice, thanks @clefebvre
