### ISSUE TITLE
mintupdate suggested kernel 4.8 update while installed kernel 4.4.0-65 was revoked

### ISSUE THREAD

**Issue by awy1076** [linuxmint/mintupdate#219]
The kernel 4.4.0-65 was only some hours on the ubuntu servers. Mintupdate suggested kernel 4.8 update and some users did not realised the little difference. So they have now 4.8 installed, which will be updated as well. 

But I am still wondering what will happen, when the kernel 4.8 will not be further supported by ubuntu. Please help to get these users informed. IMHO mintupdate could figure this out an tell them a solution.

for example one discussion:
https://forums.linuxmint.com/viewtopic.php?f=47&t=240825&hilit=kernel+4.8&sid=24284c9b49c54e2ab3ae6eec54c2b32a

**Comment by calexil** [comment]
same issue goes both ways


![screenshot at 2017-03-16 19-11-59](https://cloud.githubusercontent.com/assets/3487071/24022823/0c972c2c-0a7f-11e7-9a33-1e51569bcf48.png)

**Comment by jeremyb31** [comment]
clexil, does the 4.8 kernel remain in Update Manager if you boot into a 4.4 kernel

**Comment by calexil** [comment]
I dont have any 4.4 kernels installed

**Comment by jeremyb31** [comment]
I would actually install a 4.4.0 kernel then and try it out as 4.8.0 kernels will be unsupported July 31 of this year

**Comment by clefebvre** [comment]
Fixed in 5.2.1.1 by https://github.com/linuxmint/mintupdate/commit/40fb35e4688e767efbf4783927db86b579ab661e
