### ISSUE TITLE
Auto-Fix dpkg issues instead of showing an error message

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/mintupdate#22]
I recently saw a mail from a person in a LUG forum (ILUGC) asking the below question. 
>>iam using mint 15 oliva i coudnt update my system it is showing following
error

>>E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a'
to correct the problem.

>>E: _cache->open() failed, please report

>>how to solve this? {name clipped}

Now that made think, why cant Update Manager itself do this and rectify the problem? Perhaps it is not trivial and there is some rationale to it, keen to know. I will be grateful on your thoughts on why it cant be automagically fixed?

I would have thought 'sudo' rights is an issue but Update Manager starts with root privileges.

**Comment by clefebvre** [comment]
hmm... I'd rather fix that directly in APT.

**Comment by arclite7** [comment]
Mintupdate 5.4.7; 2019-02-11 Preparation before update from 19v0 to 19v1 LTS

Same issue being reported with apparent error but as described, unnecessary?
Surely the inconvenience and the delay of 4 years in responding to this issue will automatically ramp the prioritisation before marketplace motivation to generally criticise the product against its competition?

E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 
E: _cache->open() failed, please report.
