### ISSUE TITLE
Wrong kernel version is displayed

### ISSUE THREAD

**Issue by KevinNadaud** [linuxmint/mintupdate#222]
I'm currently using Linux Mint 18 with the kernel 4.8.0-36. 
The update manager proposes to update the kernel from 4.4.0-57 to 4.4.0-67 as shown on the fig below
![update_mananger](https://cloud.githubusercontent.com/assets/18683315/24293789/c31501f8-1093-11e7-84cb-dcdd77bebea3.png)
Nevertheless, if we the description, we can see the update contain the 4.8.0-42 kernel. 

This may be due to the default kernel version of the LM18 which is 4.4.0 and not the 4.8.0. 
Do you need any other information ?

**Comment by calexil** [comment]
confirming, this is ongoing...

![screenshot at 2017-04-04 13-50-48](https://cloud.githubusercontent.com/assets/3487071/24670953/fc17822a-193d-11e7-90e8-d9f479c7031d.png)

**Comment by calexil** [comment]
@KevinNadaud if you read below carefully you will see those updates are actually for 4.8

look at the tiny text in grey.

there are commits that fix this that have not been pushed to the current version yet

@clefebvre  Close this

**Comment by KevinNadaud** [comment]
yes I saw the tiny grey line indicating the version (this is what I mean by the description). 
OK if it will be fixed in next version !
