### ISSUE TITLE
Use svg for level icons

### ISSUE THREAD

**Issue by theel0ja** [linuxmint/mintupdate#223]
In HiDPI mode:

![image](https://cloud.githubusercontent.com/assets/5832930/24321980/1d68b850-1163-11e7-9e11-9705ccc7f65b.png)

Svg icons seems to exist: https://github.com/linuxmint/mintupdate/tree/master/usr/share/icons/hicolor/scalable/status

**Comment by xenopeek** [comment]
Confirmed the level icons are blurry in HiDPI mode on Linux Mint 19 Cinnamon beta. I restarted Cinnamon after switching to HiDPI to ensure any weirdness wasn't due the mid session HiDPI switch.

**Comment by gm10** [comment]
Closing this, not sure if this is still an issue but levels will be removed, anyway.
