### ISSUE TITLE
Request: Don't close kernel window automatically

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/mintupdate#225]
...or at least provide a checkbox to let the window stay open.

Reason: I often install two new kernels, e.g. 4.4.0-70 and 4.8.0-44, and remove two or more older ones.
For this I have to open the window a few times, that's unnecessary.
I am tempted to use synaptic for this action, but the Mint kernel window is much more clear,

**Comment by calexil** [comment]
@clefebvre Feature request

**Comment by NikoKrause** [comment]
That's a duplicate of https://github.com/linuxmint/mintupdate/issues/130
