### ISSUE TITLE
No limit to how many old kernels are kept

### ISSUE THREAD

**Issue by NZamp** [linuxmint/mintupdate#226]
When selecting the option to "Always update everything" in the update manager, every new kernel update (point release) gets installed while the old one is never removed instead. 

--Edit:
For example, when Linux Kernel 4.4.0 is installed, it will update it to 4.4.0-x, then 4.4.0-y etc, while keeping the older version too.

This leads to insufficient disk space after some time of use, and a novice (...or even a more advanced) user wouldn't notice that this is happening due to old kernels being kept installed alongside with their point updates. Also the user has to manually do the job and clean up the mess from the "kernels" section of the update manager.

**Comment by calexil** [comment]
it should really only keep two kernels, the current one and the one one version prior

**Comment by NZamp** [comment]
This is exactly what I thought, there is no reason to keep more than 2 kernels installed, at least in the same kernel series

**Comment by calexil** [comment]
@clefebvre Feature request

**Comment by NZamp** [comment]
@clefebvre It would be nice to see this bug fixed (if possible) in Linux Mint 18.2 release

**Comment by xenopeek** [comment]
#309 describes the same feature request.
