### ISSUE TITLE
I can't delete newer kernel in kernel windows

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/mintupdate#227]
I installed kernel 4.8. I installed kernel 4.4. I want use kernel 4.4 so i must delete kernel 4.8, right?
I can't delete kernel 4.8 in kernel window.
#bug
![screenshot_2017-04-01_12-36-33](https://cloud.githubusercontent.com/assets/23406555/24578012/5b084778-16d8-11e7-8322-6ea635209b59.png)
![screenshot_2017-04-01_12-36-48](https://cloud.githubusercontent.com/assets/23406555/24578016/5eed00cc-16d8-11e7-8e35-37c5ae4f37ec.png)
![screenshot_2017-04-01_12-41-10](https://cloud.githubusercontent.com/assets/23406555/24578029/86752502-16d8-11e7-9566-630efb961422.png)

**Comment by calexil** [comment]
you cant delete the kernel you have currently loaded.

**Comment by calexil** [comment]
close this

**Comment by pyroxar** [comment]
Thanks.
I think that this should be easier.
Maybe should be add option with message "This operation requires restart" or something else.

**Comment by calexil** [comment]
it is easier... if you wanna delete a kernel... dont be running it... lol

**Comment by pyroxar** [comment]
In Ubuntu Kernel Upgrade Utility I can remove kernel which i actually use.

**Comment by calexil** [comment]
@pyroxar it is removing the cached download of the installer .debs... not the actively loaded kernel.

you cant delete the kernel that is loaded

@clefebvre Close this
