### ISSUE TITLE
Window to manage kernels (mintUpdate) is not fully translated.

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/mintupdate#228]
Window to manage kernels (mintUpdate) is not fully translated.
I have in mind title of window "kernels", button "continue", checkbox "don't show this message again".

Title of windows when is show alert should be "warning" and when i manage kernels should be "kernels". Two different title of windows for different function.
I have idea that rename "kernels" to "managment of kernels".
![siilked](https://cloud.githubusercontent.com/assets/23406555/24977094/3cfcd328-1fcc-11e7-811f-ae89165e51ba.png)

**Comment by NikoKrause** [comment]
The missing translatability of those strings has been fixed https://github.com/linuxmint/mintupdate/pull/193/files

**Comment by pyroxar** [comment]
Ok.
Where is located polish translation for Linux Mint? How i can help translating?

**Comment by NikoKrause** [comment]
Translation is handled here https://translations.launchpad.net/linuxmint/latest/+lang/pl

**Comment by pyroxar** [comment]
Did you see?
linuxmint/Cinnamon#6436

**Comment by NikoKrause** [comment]
@JosephMcc This is fixed in LM Sonya, hence can be closed

**Comment by JosephMcc** [comment]
Cool. Thanks.
