### ISSUE TITLE
Split mintupdate into two programs?

### ISSUE THREAD

**Issue by Schallaven** [linuxmint/mintupdate#229]
Seeing all the issues regarding the kernels, their installation, the extra-special-code needed in the source, and so on, it might be a good idea to split actually mintupdate in two _good_ applications according to KISS and one-program-for-one-job principles:

- mintupdate as it is minus the kernel stuff; it is doing well what it is built for: updating (mostly user) applications
- implement a new kernel-control-center-app for updating, replacing, purging, installing, switching etc all kernels available

Right now "kernel controlling" is more or less a sub-menu-item with a more or less clear list-dialog, but it could be a much better and clearer GUI implemented with much more options and clear details of the changelogs, warnings, information for the user etc. An important thing like the kernel should deserve its own app.

On the same time, it is not (in Linux Mint which focuses on stability) and it should not be an every day task. Updating and replacing the kernel is something you want to do, when you need new drivers or support for hardware, an important bug fix for something is provided, etc. It should not be (or does not need to be) a task sitting in the bottom right corner of your desktop.

What do you think?

**Comment by pyroxar** [comment]
MintUpdate and application for management of kernels like "ubuntu kernel update utility" is in my opinion great idea. I think that you should attach possibility management of GRUB configuration.

**Comment by calexil** [comment]
ukuu us good for advanced users @pyroxar mint is not really targeting those kind of users.

ukuu can regularly suggest kernels that will totally break an install

**Comment by xenopeek** [comment]
mintupdate was reworked in Linux Mint 18.2 and 18.3. The new Linux kernels menu seems to provide what information you found lacking. Users get their kernel security updates and HWE kernel upgrades in the main window.
