### ISSUE TITLE
Ä and Ö letters aren't working in kernel's description

### ISSUE THREAD

**Issue by theel0ja** [linuxmint/mintupdate#230]
Using the latest version from `master` on 18.1 Cinnamon (but with old translations).

![image](https://cloud.githubusercontent.com/assets/5832930/25039785/3c701dd2-210e-11e7-9c92-613ce64f9041.png)

**Comment by theel0ja** [comment]
Same on official version on 18.1.
![image](https://cloud.githubusercontent.com/assets/5832930/25045701/34af32ae-2136-11e7-910f-f99428652297.png)

**Comment by RBM-GITHUB** [comment]
I am not a skilled programmer but it seems like it's trying to handle text extracted from some HTML data, but the programmer did not know or ignored cases where these things (things like `&#nbsp;`) need to be also handled.

**Comment by monsta** [comment]
Looks similar to https://github.com/linuxmint/mintupdate/issues/172

**Comment by xenopeek** [comment]
Retested on Linux Mint 18.3 in Finnish shows the problem has been solved. Perhaps it was already fixed earlier but closing it now.

![Screenshot](https://i.imgur.com/aSzkhBG.png)
