### ISSUE TITLE
mintupdate upgrade 

### ISSUE THREAD

**Issue by jtsagata** [linuxmint/mintupdate#231]
When mintupdate needs itself updating then only the mintupdate and mint-upgrade-info is showed. That hides the other upgrades.

I have seen in 2 separate cases, users that ignore this and explain to me "it is just 2 upgrades ... i will wait until they are some more to press that key" That's wrong, but its not me.

I suggest a special handling in this case. Possible solutions
1. Auto upgrade these 2 packages without asking
2. Show a dialog that ask user to upgrade on start up like acrobat in windows 
3. When the user open the mintupdate show a dialog asking to upgrade. When you hover over the icon show a special message

I prefer no 3.

**Comment by gm10** [comment]
So @clefebvre, since I'm doing house-keeping, what's the status on this?

**Comment by clefebvre** [comment]
@jtsagata @gm10, yes it's a valid use case. There's nothing that explains what's going on, so a user could think "ah well, there's no security updates" so no need to do anything... (I can't remember if we consider priority updates as security updates... anyway, even it helped a bit, it wouldn't be a proper solution). I agree, we should treat this as a special case and show a dedicated screen which explains that the update manager itself needs to be upgraded.
