### ISSUE TITLE
user with blank password can not update linux kernel

### ISSUE THREAD

**Issue by unxed** [linuxmint/mintupdate#235]
User with blank password (after "passwd -d") can install common updates with mintupdate, but can not upgrade the linux kernel (it still asks for the password).

Steps to reprodue:
1. Delete current user's password with "sudo passwd -d USERNAME"
2. Try to install linux kernel update with mintupdate

**Comment by calexil** [comment]
do not run a system with no password... thats asking for serious trouble

**Comment by unxed** [comment]
Is using a weak password written down on the piece of paper pinned to the wall behind PC something really better? All that mandatory safety requirements do is the **illusion** of safety.

**Comment by calexil** [comment]
no dont do that either, use a robust password with upper and lowercase letters, numbers, and symbols.

or use the four word method, think of four distinct words you will remember but ones that dont relate to each other

ie: nape beach often pine

**Comment by unxed** [comment]
Why in the world may I need it in that case?

**Comment by calexil** [comment]
?

**Comment by calexil** [comment]
@clefebvre This can be closed

**Comment by fbidu** [comment]
My 2 cents: while I agree that we should not run a system without a password, if it allows passwordless users to upgrade the kernel, so should `mintupdate`

**Comment by jtsagata** [comment]
To my understanding mintUpdate now use aptdaemon and policykit. So you can just configure policykit not to ask for a password. Problem solved.

As for the virtual machine case just use a provision script with vagrant.

**Comment by xenopeek** [comment]
Synaptic is launched with pkexec to run kernel installation. pkexec' authenticate dialog does not accept blank passwords.
