### ISSUE TITLE
Update manager shows older kernel as an upgrade

### ISSUE THREAD

**Issue by reportedby-bp** [linuxmint/mintupdate#238]
My current kernel is 4.8.0-51-generic and update manager shows 4.4.0-78.99 as an upgrade

RELEASE=18.1
CODENAME=serena
EDITION="MATE 64-bit"
DESKTOP=MATE

Update Manager version 5.2.1.1
```
[bill@XPS] ~ $ uname -r
4.8.0-51-generic
[bill@XPS] ~ $ 
```

![2017-05-16 12-23-35](https://cloud.githubusercontent.com/assets/28741013/26126621/57c7c2ec-3a54-11e7-8dcd-030762617bab.png)

I also posted this to the [Linux Mint forum](https://forums.linuxmint.com/viewtopic.php?f=18&t=245729)

A later check shows reference to the 4.8 kernel in update manager's description section

![um-017-05-16 17-51-42](https://cloud.githubusercontent.com/assets/28741013/26130023/ce0cdbca-3a60-11e7-94a6-a25c7540ac52.png)

I waited a while then performed an apt update and apt upgrade

This is prior to the apt upgrade
![um3-2017-05-17 00-06-32](https://cloud.githubusercontent.com/assets/28741013/26138423/133ae22e-3a97-11e7-987c-2f8475f17cd8.png)

Immediately afterwords I refreshed update manager which then showed the 4.8 series.

![um4-2017-05-17 00-08-47](https://cloud.githubusercontent.com/assets/28741013/26138439/33070bf0-3a97-11e7-8c7e-9c65b2f35e96.png)

**Comment by NZamp** [comment]
It's similar to the issue #226 that I've pointed out too. Do you have both 4.4 and 4.8 kernel series installed? If so, it's possible that the update manager tries to find updates for both 4.8 and 4.4 series so you're prompted with an update on the older kernel too.

However, old kernels of both series are still installed, at least in 18.1 (what's the point of an update if it keeps the older version too?)

**Comment by reportedby-bp** [comment]
NZamp,

Thank you for your response.

This [link](https://forums.linuxmint.com/viewtopic.php?f=18&t=245729#p1316886) will show the state of the system at the time of the update manager showing the 4.4 kernel as an upgrade.


To answer your question, I only had the 4.8 kernel series installed.

**Comment by clefebvre** [comment]
This was fixed. It was a cosmetic issue (to do with libc-dev updates).
