### ISSUE TITLE
alter Icon UI: doesn't yet show number of updates or urgency info

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/mintupdate#241]
if multiple updated in between whether 
icon (color?) variations to show
**max** urgency-level|security-vs-normal
or (not only that but) bargraph/composite icons to show **distribution**

e.g. to triage updates
and thus make "high priority" updates more apparent

**Comment by xenopeek** [comment]
Thanks for contributing to mintupdate. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
