### ISSUE TITLE
Tray Icon Doesn't Integrate With Cinnamon When Tray Icon Integration Is ON

### ISSUE THREAD

**Issue by feren** [linuxmint/mintupdate#243]
When Cinnamon's Tray Icon Integration is turned on in System Settings > General, after Cinnamon is restarted, for some reason, MintUpdate's tray icon is left unaffected, and still has it's own non-Cinnamon-theme-decorated menu, which is now out-of-place unlike other integrated icons, because of it WON'T be integrated in its current state in Cinnamon...

**Comment by JosephMcc** [comment]
That's because it doesn't have indicator support. Not all applications do. In my own experience enabling indicators in Cinnamon has never worked well.
