### ISSUE TITLE
Update manager policy does not respect current selection

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/mintupdate#244]
Mint 18.2 beta Cinnamon 64 bit

If I open the policy window, it always pre-selects the middle option, regardless if I have set previously one of the other 2 choices. This is different to the policy setting in Mint 18 & 18.1, where the previously selected choice got obeyed and appeared as pre-selection.

**Comment by xenopeek** [comment]
This appears to have been fixed on 18.3 (or perhaps in 18.2 final).
