### ISSUE TITLE
[BUG] [WARNING] Running MCEdit-Unified from source , on Linux Mint will break Mintinstall

### ISSUE THREAD

**Issue by Tsoccerguy3** [linuxmint/mintupdate#247]
https://github.com/Khroki/MCEdit-Unified/issues/794

Affects linux Mint KDE 18.x x64

There is a bug in Pillow that if you follow the steps on the opening page here , https://github.com/Khroki/MCEdit-Unified , you will corrupt the python libraries required by Mintinstall and Software Manager will no longer work . Good luck trying to find what files get replaced and the changed cfg files .
https://bugs.launchpad.net/linuxmint/+bug/808907

`Result from running gksu mintinstall

add_categories took 1.234 ms
build_matched_packages took 0.218 ms
add_packages took 6111.321 ms
add_reviews took 1402.498 ms
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
Traceback (most recent call last):
File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1930, in
Application()
File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 59, in wrapper
res = func(*arg)
File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 617, in init
sans26 = ImageFont.truetype(self.FONT, 26)
File "/usr/lib/python2.7/dist-packages/PIL/ImageFont.py", line 239, in truetype
return FreeTypeFont(font, size, index, encoding)
File "/usr/lib/python2.7/dist-packages/PIL/ImageFont.py", line 128, in init
self.font = core.getfont(font, size, index, encoding)
IOError: cannot open resource`

**Comment by xenopeek** [comment]
This seems to have the explanation https://forums.linuxmint.com/viewtopic.php?t=211785#p1107101. Using Python virtualenv as MCEdit recommends should avoid that issue.
