### ISSUE TITLE
Not all string are translated in Hungarian localization

### ISSUE THREAD

**Issue by KAMI911** [linuxmint/mintupdate#248]
However we have 100% complete translations for Hungarian language, the Beta has a few dozen string in English. Currently I found in update manager, but we will review all apps, shipped with Linux Mint 18.2.

**Comment by JosephMcc** [comment]
Could you let us know what strings they are? It will make it easier for us to try and address.

**Comment by KAMI911** [comment]
Few examples, but we have lots more missing strings:
https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/hu/+translate?batch=10&show=all&search=you+can+have
https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/hu/+translate?batch=10&show=all&search=Grub
https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/hu/+translate?batch=10&show=all&search=let+me

**Comment by KAMI911** [comment]
Did you figure out what went wrong?

**Comment by NikoKrause** [comment]
Those strings habe been all translated 24 May or later.
Last export of translation from Launchpad to GitHub was 23 May. https://github.com/linuxmint/mint-translations/commits/master/po-export/mintupdate

You'll have to wait till the new translations are exported. If it's translated on launchpad, then it will appear in the final version of 18.2.

It's more interesting, if you find an untranslated String in the applet, which is not on launchpad.

**Comment by KAMI911** [comment]
Thank you for the fix. Will be another round for fixes or is this the last import before the release?
