### ISSUE TITLE
Add button to delete all old kernels but the current and the previous one

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/mintupdate#252]
Right now it's only possible to delete old kernels one by one. And each time the kernel window has to be opened again, since it's closing itself after a kernel deletion. That's very time consuming.

It would be great to have a button "Delete all old kernels", which deletes all installed kernels but the current and the previous one.

**Comment by jondo** [comment]
I just wanted to file a similar feature: Being able to select multiple kernels to remove them at once. Currently, I would like to just keep the newest kernels of each of the 4.4, 4.8, 4.10, 4.11, 4.13 series.

I like to keep these selected old ones around in case the upgrade broke something and I did not notice it yet.

(I am using mintUpdate 5.2.9.)

**Comment by clefebvre** [comment]
Thanks, this is planned.
