### ISSUE TITLE
Advice on fetching the latest manifest

### ISSUE THREAD

**Issue by gaining** [linuxmint/mintupdate#255]
I'm the author of a program called [Resetter](https://github.com/gaining/Resetter), basically it tries to reset Linux mint by removing apps from a computer that aren't in the manifest (default installed list) and if the a computer doesn't have apps installed that are in the manifest, it installs it.
Problem with this is I have to manually update the manifest file myself because mint adds new packages after few updates. I'd like to add a functionality to my app so that it could fetch the latest manifests on its own. Do you guys have any advice for that?

**Comment by xenopeek** [comment]
I imagine you have found a solution on your own as I see you've updated Resetter to support Linux Mint 18.3. Update Manager would install additional packages if so required by new dependencies in updated packages. This happens, that a newer version of some package introduces new dependencies.
