### ISSUE TITLE
Blacklisted packages reappear on Refresh (LMDE)

### ISSUE THREAD

**Issue by lsteeger** [linuxmint/mintupdate#259]
Whenever I Refresh the Update Manager, my entire list of Blacklisted packages reappear.  This did not happen prior latest update 5.2.9

**Comment by monsta** [comment]
Do you use LMDE? I can confirm it there, it's quite annoying. It doesn't happen for me in Mint 18.2 though, with the same mintupdate version.

**Comment by lsteeger** [comment]
Yes, I'm running on LMDE.

I've done some debugging.  In checkAPT.py 'add_update' the blacklist is gotten by:

    self.settings.get_strv("blacklisted-packages")

Whenever checkAPT.py is run as **uid=0,** this returns an empty array.

Looks like a problem with _**settings**_ storage for **uid<>0** versus **uid=0.**

**Comment by clefebvre** [comment]
We might get away with specifying the username behind our sudo calls...

for instance

`sudo -u monsta checkAPT.py`

instead of

`sudo checkAPT.py`

**Comment by lsteeger** [comment]
I think this might jepardize the class apt.cache.Cache _**update**_ method execution which requires **uid=0.**

I believe the blacklist filtering used to be done in mintUpdate.py **RefreshThread** _**run**_ method outside of the **uid=0** scope by post-processing checkAPT.py output.

Perhaps it could be returned there, thus avoiding have to acquire the user's name, which seems to be problematic.

**Comment by lsteeger** [comment]
I've closed my pull request https://github.com/linuxmint/mintupdate/issues/261.

This issue requires further thought.  mintupdate-tool does not consider the blacklist itself, but rather, it directly instantiates the checkAPT object which attempts to check a blacklist in the **uid=0** scope. But, this blacklist could have been created by any user outside of **uid=0** scope which would not be accessible.

Question: Should the blacklist be tied to an _individual user_ or should it be _system-wide_?

**Comment by clefebvre** [comment]
Quick follow up on this. mintupdate-cli replaces mintupdate-tool and helps with this.. the blacklist (and other conf/choices) is no longer read from dconf but from the -i option, or from /etc/mintupdate-cli.blacklist.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintupdate/issues/379
