### ISSUE TITLE
[Feature request] Add close shortcut

### ISSUE THREAD

**Issue by John-Seebauer** [linuxmint/mintupdate#262]
In mintUpdate's main window, there is a menu item File->Close to exit the main window. Can we add a keyboard shortcut (i.e. Ctrl+Q or Ctrl+W) to that item? This would be similar to exit functionality in many other applications (i.e. Firefox, GIMP, Nemo).

**Comment by panaak** [comment]
Just came across this, while trying to find out why the _Update Manager_ doesn't close itself after successfully applied updates even though i have the option checked in the preferences. it worked in *Serena* but now it always asks to close in the end. Am I the only one?

**Comment by xenopeek** [comment]
File->Close hides the main window. The default keyboard shortcut in your WM to close a window has the same effect. Commonly that is Alt+F4.
