### ISSUE TITLE
LMDE2: Applying level 1 updates on fresh install breaks system

### ISSUE THREAD

**Issue by Schallaven** [linuxmint/mintupdate#264]
Hello!

One help-seeker in #linuxmint-help reported a bug, which I could reproduce:

* Download and install LMDE2 in vbox (used Mate 64bit edition for this)
* Start LMDE2 and open mintupdate
* Apply _only_ Level 1 updates
* Restart

Greeter/Login still works, but then x-server will give you a black screen only. X-Server fully works, if you for example send the ACPI-shutdown signal you get the respective shutdown dialog - just no panels, background, etc

None of the mate-programs are started, because of a GTK2/GTK3 problem, which can be confirmed by switching to tty and run for example mate-panel:
`Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported`

It is probably that some of the mint-programs pull some GTK3 libs but don't update/remove the GTK2 ones they still use. Removing all GTK3 libs and reinstalling mate-desktop-environment fixes the problem (or at least let you run a non-themed version of Mate).

Applying all level 1-3 updates + level 4 updates for mdm and x-org/server fixes the problem or does not cause a problem in the first place. Still, a problem since Level 1 are clearly marked as "unlikely will break anything" but ... they do in this case.

**Comment by clefebvre** [comment]
Can you pinpoint which update is responsible for this and why?

**Comment by clefebvre** [comment]
That looks like an incomplete MATE upgrade... with parts still in GTK2 and parts still in GTK3.

**Comment by Schallaven** [comment]
It is probably, I will try to get the responsible update on the weekend when I have more time :)

**Comment by monsta** [comment]
Cinnamon edition should be fine - it's already on GTK+3, there was no such migration.

**Comment by monsta** [comment]
Wow. I just reproduced this. WTF... the whole MATE was left at 1.16, only a few packages were upgraded to 1.18:
- gir1.2-mate-desktop
- libmate-desktop-2-17
- engrampa
- engrampa-common
- gir1.2-mate-panel

That's it. All other MATE packages are still at 1.16.

**Comment by monsta** [comment]
Well, of course after reboot there's just a black screen. Good that the terminal is still available via Ctrl-Alt-T shortcut. I run mintupdate from it, and it shows the system is up to date. Synaptic proves it wrong.

**Comment by monsta** [comment]
Ok, I see what happens here. MATE packages are actually scattered across several levels.
- engrampa is on level 1
- mozo is on level 2
- all the other packages are on level 3

Now on level 1 we also have mintmenu... and new GTK+3 version pulls in new GTK+3 gir1.2-mate-desktop and gir1.2-mate-panel. Not sure why libmate-desktop is pulled by the corresponding GI package but libmate-panel-applet isn't, it's probably a missing dependency. Anyway, it's enough to have a mix of GTK+3 library and GTK+2 apps which use it (caja, mate-panel and others), which is forbidden and leads to immediate abort of the app.

**Comment by monsta** [comment]
Ok, mintUpdate 5.2.9.1 solves it.
