### ISSUE TITLE
mint-update shows package descriptions in multiple languages

### ISSUE THREAD

**Issue by alindt** [linuxmint/mintupdate#267]
After playing with LANG and LC_* variables, mintupdate shows package descriptions in various languages **at once**.

```
$ locale
LANG=en_IE.UTF-8
LANGUAGE=
LC_CTYPE="en_IE.UTF-8"
LC_NUMERIC="en_IE.UTF-8"
LC_TIME="en_IE.UTF-8"
LC_COLLATE="en_IE.UTF-8"
LC_MONETARY="en_IE.UTF-8"
LC_MESSAGES="en_IE.UTF-8"
LC_PAPER="en_IE.UTF-8"
LC_NAME="en_IE.UTF-8"
LC_ADDRESS="en_IE.UTF-8"
LC_TELEPHONE="en_IE.UTF-8"
LC_MEASUREMENT="en_IE.UTF-8"
LC_IDENTIFICATION="en_IE.UTF-8"
LC_ALL=en_IE.UTF-8
```

![wtf](https://user-images.githubusercontent.com/1379385/28659991-fa5e4e2a-72b9-11e7-9982-6829ef81f85f.png)

**Comment by xenopeek** [comment]
Something more must have been at play here. If the issue happens again, please test against the latest mintupdate version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintupdate. You can use the forums for getting assistance with troubleshooting.
