### ISSUE TITLE
mintUpdate 5.2.9 CTRL-A in text area does not select all text (Description or Changelog)

### ISSUE THREAD

**Issue by LarryAT** [linuxmint/mintupdate#273]
Previous to Linux Mint Cinnamon (64-bit) 18.2/sonya upgrade which includes mintUpdate 5.2.9, clicking in the Description or Changelog area and typing CTRL-A would properly select all text, allowing said text to be copied with CTRL-C. 

(Also, selecting some text and typing SHIFT-CTRL-END doesn't extend selection to end of text, but I don't know if that worked before.)

Selecting all text in a long Changelog is now only possible by selecting at the beginning and while keeping mouse-button-1 down, swiping mouse down dozens of times to get to end of text.  :( 

The previous, working, mintupdate was version 5.2.1.1.

**Comment by xenopeek** [comment]
Right-click the changelog area and you can use Select All and Copy from the context menu instead.
