### ISSUE TITLE
Are security updates disabled?

### ISSUE THREAD

**Issue by jepster** [linuxmint/mintupdate#274]
Is it true, that Linux Mint is disabling the important Ubuntu security updates per default? That would mean, that if any critical security issue comes up in the Ubuntu system, the system would be vulnerable for intrusion via the publicly available security issues. 

I got this hint:

> Mint, a distro based on Ubuntu, completely disables these important updates by default, leaving users vulnerable to known, fixed vulnerabilities.

If this Linux Mint update criticism is true, then no Linux Mint user is save. Please be so kind and clarify this issue.

**Comment by jepster** [comment]
I can see via the update manager, that the Linux Kernel is not checked by default. Usually I am checking the Linux Kernel to update it. I had no issues so far. Do I assume wrong, that if I check the Linux kernel via the update manager, the Linux kernel is not updated?

![auswahl_051](https://user-images.githubusercontent.com/628434/30035355-8feaede6-91a9-11e7-850d-4a9ea04e82de.png)

Also people are writing here about security issues in Linux Mint: https://www.infoworld.com/article/3182824/linux/is-linux-mint-a-secure-distribution.html

**Comment by f380cedric** [comment]
It is true, and false, depending of your choice. Mintupdate will ask you to select the update policy you want to follow. To have an idea why it is like this, I found an **old** example [here](http://segfault.linuxmint.com/2013/11/answering-controversy-stability-vs-security-is-something-you-configure/)
If the kernel update is not checked, it won't update. You can configure Mintupdate to automatically select security updates (including or excluding kernel updates) in Edit → Settings

**Comment by clefebvre** [comment]
Security updates are shown by default for all policies and we encourage everyone to install them.

That kernel update you highlighted related to a newer kernel being available. If you check it and press Apply it will indeed install it.
