### ISSUE TITLE
[Feature Request] Snooze Button

### ISSUE THREAD

**Issue by ambs** [linuxmint/mintupdate#275]
Sometimes you do not want to install updates but want to the tray icon to get green up to when there are new updates. A snooze button would mean 'ok, no hurry on those updates, let me know when there are some more'.

Cheers

**Comment by xenopeek** [comment]
Thanks for contributing to mintupdate. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
