### ISSUE TITLE
Mint 18.2 - Encrypted system does not boot after kernel upgrade

### ISSUE THREAD

**Issue by Thunderlight1** [linuxmint/mintupdate#276]
Distribution : Linux Mint 18.2 Sonya - 64-bit

Issue
Installed my machine with the default encryption of the whole system, but not the home directory. After upgrading to a newer kernel with apt-get, it does not start anymore. It stops after I have entered the encryption password and confirming that the password is correct.
To have it start, I need to select the old kernel.
Tried to build ramdisk, but it did not help.

Steps to reproduce
Install a new Linux Mint 18.2 system with the option encrypt system.
Update the system and install a newer kernel.
Reboot system.
Enter encryption password.
Screen confirms the correct password.
System hangs.

Expected behavior
System should start using the new selected kernel.

Other information
Workaround: You can start the system by selecting the old kernel at the grub menu.
Could not find any logs about this issue in /var/log directory.

**Comment by xenopeek** [comment]
There may have been a regression in the newer kernel with your specific hardware. You can get support with such issues in https://forums.linuxmint.com/viewforum.php?f=46.

Update Manager can't predict such things. It just instructs Synaptic to download and install the package. The package itself has the information on how it should be installed. Like updating your boot manager (GRUB) to boot the newest kernel by default.
