### ISSUE TITLE
Updater wont search (refresh) or report

### ISSUE THREAD

**Issue by Anon01234** [linuxmint/mintupdate#277]
The update applet can not be refreshed. However, when executing sudo apt-get update works in a terminal.

1) The version and edition of Linux Mint you are using (if you are not sure, open a terminal and run "mintwelcome").

"Mint KDE 18.2 64-bit"

2) What you did for the problem to happen, and how to reproduce it.

"None, it will happen automatically"

3) What happened.

"No refresh of updates"

4) What you expected to happen instead.

"It should look for updates and report them"

5) If the problem happened once, sometimes, or always.

"It occurred several times now" (sometimes)

No error occurs.

As a work-a-round you can use the terminal.

**Comment by NikoKrause** [comment]
Can you take some screenshots?

**Comment by Anon01234** [comment]
Hi Niko,
It happened again but something strange is going on here.

When it happened I was watching youtube. A red cross, so the updater is not available???

A few moments later I got the blue sign indicating there are updates available. 

So either way it solved it self or you get an red cross when the applet is checking for updates?

**Comment by NikoKrause** [comment]
I usually see a red cross, if it fails to refresh, e.g. because of bad/no internet connection.

**Comment by Anon01234** [comment]
Hmm, that seems not to be the case here from my end. 

But then again, I get sometimes the well known 404 error from ubuntu...

Still that doesn't change what is happening.

**Comment by xenopeek** [comment]
Should it happen again please do the following:

1. Click the Refresh button in Update Manager. Does it succeed or fail?
2. If it failed, immediately after open a terminal and run the following 4 commands:
  `/usr/lib/linuxmint/mintUpdate/checkAPT.py`
  `for f in /tmp/mintUpdate/*; do ls -l "$f"; cat "$f"; done`
  `apt update`
  `inxi -Sr`
3. Copy the entire output from the terminal (see its Edit menu for selecting and copying text) and share it for analysis.
