### ISSUE TITLE
[Feature request] Adding Multi Select On Kernel Window

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintupdate#278]
Hi,

Could you add multi select function for multiple install or remove of kernels to mintupdate's kernel window.

Best regards

**Comment by minto0s** [comment]
I second that request

**Comment by xenopeek** [comment]
Thanks for contributing to mintupdate. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
