### ISSUE TITLE
Window too big on small screens

### ISSUE THREAD

**Issue by MegaV0lt** [linuxmint/mintupdate#279]
I was installing mint 18.2 on an Samsung NC10 netbook yesterday at an friends home.
Problem after install was to select the policy of the updates. The window was bigger than the screen and it was not possible to access the "OK" Button. I also tried to disable the taskbar, but the buttons weren't accessible.

On small screens the window should not get bigger than the screen!

Samsung NC10 Displayresolution is: 1024x600 Pixel

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/mintupdate/issues/170
