### ISSUE TITLE
[bug] All window manager enviroment turns low opacity and can't roll back

### ISSUE THREAD

**Issue by azurinko** [linuxmint/mintupdate#281]
Hello, when I open text editor, from desktop, and try to do a different task while it's starting, all windows turn on low opacity(like starting animation of text editor) and I can't roll it back because they all act like being in process of minimalization. I can't properly replicate this bug, but it happened to me with text editor twice. I'll try to take a screenshot next time.

**Comment by xenopeek** [comment]
This appears to be unrelated to Update Manager. Suggest to post on the forums for help with troubleshooting issues before reporting bugs. See also our troubleshooting guide: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
