### ISSUE TITLE
Please add an option to allow pinning of the "Downloading Package Information" window

### ISSUE THREAD

**Issue by affinityv** [linuxmint/mintupdate#282]
If there are no errors on updates or when checking repositories, the popup Window will automatically be destroyed.  I would prefer to be able to see it entirely after the fact and to manually dismiss the Window when I am done with it.

I hate Lookout (otherwise known as Outlook), but they have a pinning Window feature; that is what I would like to see.

Doing this may require the modal status of the Window to be adjusted when it is no longer the "focus" of the operation.

**Comment by xenopeek** [comment]
Thanks for contributing to mintupdate. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
