### ISSUE TITLE
Update Manager Python2 vs Python3

### ISSUE THREAD

**Issue by xingguodasha** [linuxmint/mintupdate#288]
The Update Manager apparently fails to update when the system is configured to run Python 3 instead of Python 2 (through update-alternative). It should rather be hardcoded to python2 (if this is required to run) rather than assuming that 'python' redirects to python 2.

**Comment by PeriGK** [comment]
Hi @xingguodasha ,

I am not sure this is the case. My system updates fine, out of the box, and my default python is python3

```
$ python
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.

```

**Comment by xingguodasha** [comment]
Periklis,

I had never noticed that before and I have been using python3 for a while. So it may depend on the packages that are being updated.

Checking my last update history, I was updating the package 'python-samba' among many other packages. This might have triggered the bug.

The update failed while my system was configured for Python3. Then it worked just by using update-alternative and picking python2.

So may be only the update process of 'python'-related packages is concerned by my remark.

The update worked with python2.7 and was not working with python3.5:

Python 3.5.2 (default, Sep 14 2017, 22:51:06)
[GCC 5.4.0 20160609] on linux
vs

Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2

Frederic.

On 11/23/2017 01:26 PM, Periklis wrote:

Hi @xingguodasha<https://github.com/xingguodasha> ,

I am not sure this is the case. My system updates fine, out of the box, and my default python is python3

$ python
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by leigh123linux** [comment]
@xingguodasha Can you explain the issue better as I have difficultly understanding the point you are trying to make.
mintupdate code is hardcoded to python3 (#!/usr/bin/python3) so it shouldn't be possible to run under python2
The only code without a shebang is
https://github.com/linuxmint/mintupdate/blob/master/usr/lib/linuxmint/mintUpdate/proxygsettings.py
Are you sure you haven't screwed up with update-alternative?

**Comment by xingguodasha** [comment]
I have launched mintupdate and it failed to update.

For some reasons I switched to python2, I did the update again and it passed.

I am surprised that the update fails or passes depending on my system configuration for python. If the update process needs python 2 (instead of Python 3), then it should call /usr/bin/python2 and not /usr/bin/python since the latter one depends on the system configuration.

As I answered to Periklis, in my case, when it failed, the process was updating the package 'python-samba'. I wonder whether the update process might depend on the kind of package to be updated.

I think I have a pretty standard configuration for update-alternatives:

~ $ update-alternatives --config python
There are 2 choices for the alternative python (providing /usr/bin/python).

  Selection    Path                Priority   Status
------------------------------------------------------------
  0            /usr/bin/python3.5   2         auto mode
* 1            /usr/bin/python2.7   1         manual mode

Press <enter> to keep the current choice[*], or type selection number:

Is that any clearer ?

Frederic

On 11/23/2017 04:05 PM, Leigh Scott wrote:

@xingguodasha<https://github.com/xingguodasha> Can you explain the issue better as I have difficultly understanding the point you are trying to make.
mintupdate code is hardcoded to python3 (#!/usr/bin/python3) so it shouldn't be possible to run under python2
The only code without a shebang is
https://github.com/linuxmint/mintupdate/blob/master/usr/lib/linuxmint/mintUpdate/proxygsettings.py
Are you sure you haven't screwed up with update-alternative?

**Comment by leigh123linux** [comment]
What provides /usr/bin/python3

**Comment by xingguodasha** [comment]
~ $ /usr/bin/python3
Python 3.5.2 (default, Sep 14 2017, 22:51:06)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>


On 11/23/2017 04:41 PM, Leigh Scott wrote:

What provides /usr/bin/python3

**Comment by xenopeek** [comment]
Certain packages from your configured APT software repositories may have pre or post install scripts written in Python 2 and use a `#!/usr/bin/python` hashbang instead of an explicit `#!/usr/bin/python2`. That's something the package's developer or maintainer should address. Changing the system default Python version will otherwise break APT for such packages. I've seen the same for other users a number of times.

Instead of changing your system default Python version, make your own scripts use an explicit hashbang. The Linux Mint developed Python scripts do this as well.
