### ISSUE TITLE
Upgrade-info blocks mintUpdate

### ISSUE THREAD

**Issue by johankor** [linuxmint/mintupdate#292]
When mint-upgrade-info_1.1.0_all.deb was made available in mintUpdate, it would no longer list any other updates (including security related ones) before this upgrade-info update was installed. Since I was not interested in upgrading to 18.3 at this point, I left this update unattended for a while. The consequence of this was that my system missed out on security updates for several days.

I've been told that this is intended behavior, as this update is important for the update mechanism itself. But I'm not the only one that didn't know about this, others have also missed out on security updates. If this is the case, shouldn't this be indicated more clearly to the user?

**Comment by clefebvre** [comment]
duplicate https://github.com/linuxmint/mintupdate/issues/231
