### ISSUE TITLE
Mint 18.3 problems after kernel update, Teamviewer install crashes

### ISSUE THREAD

**Issue by keithsplace1** [linuxmint/mintupdate#293]
resently fresh installed Mint 18.3 32bit and tried to install teamviewer from software manager and web page download and synaptic crashes in  both instances.

**Comment by xenopeek** [comment]
I downloaded and installed Teamviewer on Linux Mint 18.3 from here https://www.teamviewer.com/en/download/linux/ without problems. After downloading the .deb file you should double-click it in your file manager to launch the GDebi package installer. Note that Teamviewer is not available in the Linux Mint 18.3 repositories so you can't install it through Software Manager (or for that matter through Update Manager, on which you've opened this issue).

If you have trouble with installing software from outside the Linux Mint repositories you can ask for support on the forum here https://forums.linuxmint.com/viewforum.php?f=47.
