### ISSUE TITLE
Are updates of a flatpak shown in the list of available updates?

### ISSUE THREAD

**Issue by sphh** [linuxmint/mintupdate#296]
I just noticed that I could update a program I installed as a flatpak with the help of the Software Manager with the command line `flatpak update`, but it was not included in the list of available updates in the Update Manager.

Is there a configuration I have missed how to include updates to flatpaks into the Update Manager?

If not, please consider this as a enhancement wish.

**Comment by clefebvre** [comment]
Thanks, this is planned.
