### ISSUE TITLE
Nemo update listed although Nemo not installed

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintupdate#297]
My latest run of mintupdate on Mint 18.3 lists _cinnamon-nemo_ for installation. However I am running MATE and using Caja.

`dpkg -l *cinnamon*` returns no installed packages.

`dpkg -l *nemo*` returns _libnemo-extension1_ as installed (although I have no idea why it is since I have never installed nemo).

**Comment by ewangi** [comment]
Update: running `apt-get upgrade` shows that it is indeed the package _libnemo-extension1_ that wants to be upgraded and not some mythical "_cinnamon-nemo_" package.

It appears that libnemo-extension1 is depended upon by _xreader_. Given that I have neither Cinnamon nor Nemo, I don't know why Xreader on my system should depend on this package. However I will upgrade it just to keep it quiet.

If all of the above conforms to what should happen in practice, please feel free to close this issue.

**Comment by clefebvre** [comment]
xreader provides page plugins for nemo and caja and thus depends on their extension libraries.
