### ISSUE TITLE
Few Missing Translations

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintupdate#298]
Hi,

There is few missing translations for mintupdate. 

![mintupdate-missing-translations-18 3](https://user-images.githubusercontent.com/1300133/34314084-5b967668-e781-11e7-9ae9-3a3c1e823fff.png)

**Comment by pyroxar** [comment]
I confirm. In Polish version also translations are lacking. 
I don't have translate text in places pointed out by you.

In the Polish language, translations are lacking in the kernels' window (in the first paragraph).
![translateit](https://user-images.githubusercontent.com/23406555/34320971-a277aa74-e804-11e7-99ea-58ea1db20b92.png)
@kelebek333  Do you also haven't a translation of the first paragraph in the kernels' window?

PS: Where are files with translations for MintUpdate? I can't locate any files. Anybody know where the files are?

**Comment by kelebek333** [comment]
Hi @pyroxar ,

"kernels' window (in the first paragraph)" for Polish language not translated on launchpad. You can translate them on Launchpad. 

https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/pl/177/+translate

This section fully translated for Turkish language.

![mintupdate-translations-18 3-2](https://user-images.githubusercontent.com/1300133/34322742-489e6f0a-e841-11e7-9368-e5bba671b474.png)

**Comment by xenopeek** [comment]
Translations are done by volunteers. You can help improve the translations for your language. See our guide for new translators here: https://linuxmint-translation-guide.readthedocs.io/en/latest/

**Comment by kelebek333** [comment]
@xenopeek , this problem is not about missing launchpad translations. This problem on mintupdate's source side. Mintupdate's Turkish and French translation's fully finished. 

%d update available
%(selected)d updates selected (%(size)s)

https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/tr/211/+translate
https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/fr/211/+translate

%(selected)d update selected (%(size)s)

https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/tr/210/+translate
https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/fr/210/+translate

You can look at following screenhot.

![mintupdate-missing](https://user-images.githubusercontent.com/1300133/35697580-a3d7e922-079b-11e8-963d-7aa16985a316.png)

**Comment by xenopeek** [comment]
Thanks for clarifying. On October 27 2017, the day before the translations on your link were done, the POT files were updated https://github.com/linuxmint/mintupdate/commit/d858d9863c42851b9983fb0d946538e6d6279647 for release 5.3.0. We don't do a new release every time a string is translated but update POT files as part of major or minor releases. We've only done two bugfix releases since those translations were completed.

**Comment by kelebek333** [comment]
Problem solved with this fix. https://github.com/linuxmint/mintupdate/pull/329

**Comment by kelebek333** [comment]
Problem solved with this fix. https://github.com/linuxmint/mintupdate/pull/329/commits/04e247566927074dc3bac58f0b98cf8952c1d0b1

![mintupdate-locale-3](https://user-images.githubusercontent.com/1300133/37566931-c71c8368-2ad0-11e8-836c-85ece65e42b9.png)
