### ISSUE TITLE
The interface should be blocked while a kernel is being installed/removed via Synaptic

### ISSUE THREAD

**Issue by monsta** [linuxmint/mintupdate#30]
Right now it's possible to try checking for updates or installing them while Synaptic is busy installing or removing a kernel. This will result in an error message:

> Another synaptic is running.
> There is another synaptic running in interactive mode. Please close it first.

**Comment by JosephMcc** [comment]
This sort of goes with https://github.com/linuxmint/mintupdate/issues/134
