### ISSUE TITLE
System Update Errors

### ISSUE THREAD

**Issue by caltrop-3** [linuxmint/mintupdate#300]
here is a short list of the 18 errors generated during the latest update
this started happening about a month ago

W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/additional-repositories.list:1 and /etc/apt/sources.list.d/additional-repositories.list:2
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/additional-repositories.list:1 and /etc/apt/sources.list.d/additional-repositories.list:2

**Comment by clefebvre** [comment]
This is a configuration error. You can edit your repositories with the "Software Sources tool". Make sure to remove any duplicates. Check the listing with "inxi -r".
