### ISSUE TITLE
System tray icon keeps indicating updates available

### ISSUE THREAD

**Issue by jhm2** [linuxmint/mintupdate#301]
After upgrading to Linux Mint 18.3 Cinnamon the system tray icon of Update Manager keeps on showing the blue mark indicating available updates after updating. After a bit of fiddling around I found that this happens as long as the package list isn't empty, even if the packages aren't selected and after updating the selected packages. How do I make this icon behave as before?
 
![afbeelding](https://user-images.githubusercontent.com/35330999/34820905-43de0874-f6c2-11e7-8be8-3c3df564279d.png)

**Comment by clefebvre** [comment]
This is by design. The icon indicates you have updates available. The preselection is just there to help you select things a little quicker.
