### ISSUE TITLE
Preference Suggestion - Not a bug ...

### ISSUE THREAD

**Issue by joelhof5** [linuxmint/mintupdate#304]
Hope this is the right place to submit this. In preferences, add a box to select details always. Every time I do an update, I have to click to see the download progress, then when it switches to install, I have to click details again to show the installation progress and details. Would be nice to have a single check box in the main window, or prefs, to have this on all the time for both download progress and install details. Same issue in synaptic. Mint 18.3. Thanx. Excellent work!

**Comment by clefebvre** [comment]
This is a synaptic limitation. I don't think it can be solved in mintupdate.
