### ISSUE TITLE
[feature request] Reorganisation of kernel window

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintupdate#308]
Three related requests relating to the kernel section of mintupdate:

(i) Given that the kernel versions are shown in descending numerical order, i.e. latest first, could the same be done with the branch numbers on the left-hand side e.g. 4.13 at the top down to 4.4 for current LM18 branches?

(ii) Could some indication be given on the branch number tabs at the left-hand side if there is at least one kernel installed in that branch e.g. different shading of that branch, small dot in the tab, etc. The rationale behind this is negating the need to scroll through every branch to determine which kernels are installed (personal observation + a poster in LinuxQuestions recently who discovered additional kernels that were installed only when scrolling down one of the kernel branches - they were in effect "hidden" to the poster otherwise).

(iii) It could be useful if the kernel window, on opening, would automatically display the kernel branch that includes the active kernel (perhaps even auto scrolling if the active kernel would otherwise be hidden).

**Comment by xenopeek** [comment]
Thanks for contributing to mintupdate. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
