### ISSUE TITLE
Sort downloads

### ISSUE THREAD

**Issue by mat-m** [linuxmint/mintupdate#311]
In the _Download Package Files_ dialog, we have a table under the _Show Individual Files_ toggle.
It would be nice if we could sort it on any column. 

TypicalIy, I have a slow connection. I would like to sort on Status, so the Done would be out of sight and I could keep an eye on pending transfers.

Currently we cannot, but I don't know if it is a feature or a bug.

Thanks
Linux Mint 18.3 Sylvia

**Comment by xenopeek** [comment]
Many thanks for contributing to Update Manager. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

Noting that mintupdate uses synaptic to do the downloads and package installations. I think the progress window is from synaptic not mintupdate. This is the progress window in question:
![Screenshot](https://i.imgur.com/DSrIWCz.png)

**Comment by mat-m** [comment]
I guess from the closing it is considered a FR and not a bug.

Thanks.
