### ISSUE TITLE
Window extends far off the screen when DPI set to high

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintupdate#314]
To reproduce:

1. Set DPI to high.
2. Possibly (I'm unsure this is necessary to reproduce the bug) change some font settings to large sizes.
3. Open Update Manager and observe how it extends far off the screen to the left, even after toggle between minimized and unminimized, and even after closing and re-opening. (I would try toggle maximise, but the window in question has no maximise button.)
4. Reboot and observer that that too makes no difference.

Mint 18.3 x64 Cinnamon.

**Comment by JosephMcc** [comment]
What do you mean by "Set the DPI" to high? What settings are you changing? What's your monitor resolution? We need more info to properly troubleshoot this.

If you are using HiDPI settings on a non-HiDPI monitor and going out of your way to force overly large fonts then this isn't a bug. The default window size is meant to work in sensible situations.

**Comment by CottonEaster** [comment]
I am sorry. I should have provided more detail. (Excuse: I was frazzled from trying half a dozen distros with three or four DEs, and not being able to get any of them to work decently on my screen.)

Monitor: 13.3" FHD, running at its native resolution of 1920 x 1080. It is not really a HiDPI monitor and yet, to my eyes (which are only slightly worse than average), everything - fonts, window decorations, icons - are too small (on all DEs and distributions) out of the box.

I set the 'user interface scaling' (in System Settings -> General) to 'high'.
