### ISSUE TITLE
Linux Mint 17.2 Rafaela: Update Manager default levels preferences break Intel 7265 WiFi support after upgrade to 4.4.0-111-generic kernel

### ISSUE THREAD

**Issue by toggoboge** [linuxmint/mintupdate#319]
This is going to be a very difficult issue to deal with for a non-technical user who has not changed the default Update Manager settings. It seems that the default settings updated the kernel from 3.16.0-38 to 4.4.0-111 (to deal with Meltdown and Spectre???), but didn't update linux-firmware to match.

**Some info about my system**

Apparently I have mintUpdate 4.9.3.4

![mintupdate version](https://user-images.githubusercontent.com/36522620/36285960-7a7df66a-12a5-11e8-9111-5aaa552aa851.png)

```
~/Downloads @mileens$ cat /etc/issue.net; echo
Linux Mint 17.2 Rafaela
~/Downloads @mileens$ uname -a
Linux mileens 4.4.0-111-generic #134~14.04.1-Ubuntu SMP Mon Jan 15 15:39:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
~/Downloads @mileens$ lspci | grep 7265
03:00.0 Network controller: Intel Corporation Wireless 7265 (rev 59)


```
**Symptoms:** After rebooting (Wed Feb 14 14:33 in "last reboot" info below) and switching from 3.16.0-38 to 4.4.0-111 kernel, my Intel 7265 WiFi device was not accessible in Network Manager.

For a later occurence, I saw the following in /var/log/syslog:

```
Feb 15 21:47:34 mileens kernel: [  875.492892] Intel(R) Wireless WiFi driver for Linux
Feb 15 21:47:34 mileens kernel: [  875.492896] Copyright(c) 2003- 2015 Intel Corporation
Feb 15 21:47:34 mileens kernel: [  875.494448] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-7265D-19.ucode failed with error -2
Feb 15 21:47:34 mileens kernel: [  875.494463] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-7265D-18.ucode failed with error -2
Feb 15 21:47:34 mileens kernel: [  875.494473] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-7265D-17.ucode failed with error -2
Feb 15 21:47:34 mileens kernel: [  875.494482] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-7265D-16.ucode failed with error -2
Feb 15 21:47:34 mileens kernel: [  875.494491] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-7265D-15.ucode failed with error -2
Feb 15 21:47:34 mileens kernel: [  875.494500] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-7265D-14.ucode failed with error -2
Feb 15 21:47:34 mileens kernel: [  875.494509] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-7265D-13.ucode failed with error -2
Feb 15 21:47:34 mileens kernel: [  875.494511] iwlwifi 0000:03:00.0: request for firmware file 'iwlwifi-7265D-13.ucode' failed.
Feb 15 21:47:34 mileens kernel: [  875.494515] iwlwifi 0000:03:00.0: no suitable firmware found!

```
So I did a little digging:

```
~/Downloads @mileens$ ls -l /lib/firmware/iwlwifi-7265D*
-rw-r--r-- 1 root root  740436 May 13  2015 /lib/firmware/iwlwifi-7265D-10.ucode
-rw-r--r-- 1 root root 1002800 May 13  2015 /lib/firmware/iwlwifi-7265D-12.ucode
~/Downloads @mileens$ last reboot
reboot   system boot  4.4.0-111-generi Thu Feb 15 21:33 - 22:25  (00:52)    
reboot   system boot  4.4.0-111-generi Wed Feb 14 14:34 - 21:32 (1+06:57)   
reboot   system boot  4.4.0-111-generi Wed Feb 14 14:33 - 14:34  (00:00)    
reboot   system boot  3.16.0-38-generi Fri Feb  2 11:04 - 14:34 (12+03:29)  

wtmp begins Fri Feb  2 11:04:29 2018

```
It looks like the oldest firmware version supported by the new kernel is 13, but the newest I have installed is 12, hence my problem.

This is provided by linux-firmware:

```
~/Downloads @mileens$ dpkg -S /lib/firmware/iwlwifi-7265D-12.ucode
linux-firmware: /lib/firmware/iwlwifi-7265D-12.ucode

```
And looking at Update Manager, I see linux-firmware (at level 5) hasn't been updated. This is in accordance with the default preferences for levels (only update levels 1-3).

![update manager linux-firmware deselected](https://user-images.githubusercontent.com/36522620/36285714-a1b9ac98-12a4-11e8-9b63-e413e56ea27e.png)

![update manager - preferences - levels](https://user-images.githubusercontent.com/36522620/36285731-b6d7fe68-12a4-11e8-806a-7e7af9372754.png)

Checking the box next to linux-firmware and installing it fixed my problem. No need for a reboot - just did this:

```
~/Downloads @mileens$ sudo modprobe -r iwlwifi
[sudo] password for brian: 
~/Downloads @mileens$ sudo modprobe iwlwifi

```
After updating linux-firmware, I see the following in /lib/firmware and in syslog:

```
~/Downloads @mileens$ ls -l /lib/firmware/iwlwifi-7265D*
-rw-r--r-- 1 root root  740436 Nov 16 16:41 /lib/firmware/iwlwifi-7265D-10.ucode
-rw-r--r-- 1 root root 1002800 Dec  1  2016 /lib/firmware/iwlwifi-7265D-12.ucode
-rw-r--r-- 1 root root 1008692 Dec  1  2016 /lib/firmware/iwlwifi-7265D-13.ucode
-rw-r--r-- 1 root root 1384500 Dec  1  2016 /lib/firmware/iwlwifi-7265D-16.ucode
-rw-r--r-- 1 root root 1036528 Nov 16 16:41 /lib/firmware/iwlwifi-7265D-29.ucode

Feb 15 22:36:24 mileens kernel: [ 3805.482808] Intel(R) Wireless WiFi driver for Linux
Feb 15 22:36:24 mileens kernel: [ 3805.482810] Copyright(c) 2003- 2015 Intel Corporation
Feb 15 22:36:24 mileens kernel: [ 3805.484028] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-7265D-19.ucode failed with error -2
Feb 15 22:36:24 mileens kernel: [ 3805.484034] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-7265D-18.ucode failed with error -2
Feb 15 22:36:24 mileens kernel: [ 3805.484039] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-7265D-17.ucode failed with error -2
Feb 15 22:36:24 mileens kernel: [ 3805.484563] iwlwifi 0000:03:00.0: loaded firmware version 16.242414.0 op_mode iwlmvm
Feb 15 22:36:24 mileens kernel: [ 3805.504873] iwlwifi 0000:03:00.0: Detected Intel(R) Dual Band Wireless AC 7265, REV=0x210

```
So version 16 of the firmware worked for me. I hadn't paid attention to these levels before, but I'm now gonna install the other security updates listed in Update Manager.

**Comment by togoboge** [comment]
I see from /var/log/apt/history.log that it was running "apt-get install snapd" that updated to the new kernel:

Start-Date: 2018-02-02  12:06:25
Commandline: apt-get install snapd
Install: squashfs-tools:amd64 (4.2+20130409-2ubuntu0.14.04.2, automatic), linux-generic-lts-xenial:amd64 (4.4.0.111.95, automatic), snapd:amd64 (2.29.4.2~14.04), linux-headers-generic-lts-xenial:amd64 (4.4.0.111.95, automatic), libapparmor-perl:amd64 (2.10.95-0ubuntu2.6~14.04.1, automatic), linux-headers-4.4.0-111:amd64 (4.4.0-111.134~14.04.1, automatic), cgroup-lite:amd64 (1.9, automatic), linux-image-extra-4.4.0-111-generic:amd64 (4.4.0-111.134~14.04.1, automatic), linux-image-4.4.0-111-generic:amd64 (4.4.0-111.134~14.04.1, automatic), systemd:amd64 (204-5ubuntu20.25, automatic), linux-image-generic-lts-xenial:amd64 (4.4.0.111.95, automatic), apparmor:amd64 (2.10.95-0ubuntu2.6~14.04.1, automatic), linux-headers-4.4.0-111-generic:amd64 (4.4.0-111.134~14.04.1, automatic)
Upgrade: libsystemd-login0:amd64 (204-5ubuntu20.12, 204-5ubuntu20.25), systemd-services:amd64 (204-5ubuntu20.12, 204-5ubuntu20.25), libsystemd-daemon0:amd64 (204-5ubuntu20.12, 204-5ubuntu20.25), libpam-systemd:amd64 (204-5ubuntu20.12, 204-5ubuntu20.25), libsystemd-journal0:amd64 (204-5ubuntu20.12, 204-5ubuntu20.25)
End-Date: 2018-02-02  12:08:06

**Comment by xenopeek** [comment]
Indeed, Ubuntu 14.04 (the package base used by Linux Mint 17.x) supports snapd but only when you use linux-generic-lts-xenial. It is a required dependency that gets installed when you install snapd. See https://packages.ubuntu.com/trusty-updates/snapd.

While on Linux Mint 17.x the kernel upgrade to mitigate Meltdown and Spectre is shown by default it remains up to the user to select when to install it. As you can see in the [screenshot](https://i.imgur.com/5hmBUGE.png) (taken on fresh Linux Mint 17.2, after updating mintupdate and mint-upgrade-info) both the kernel and firmware are up to the user to select to install.
