### ISSUE TITLE
Feature Request - 3 States for Shield Icon - Updates Available, Partially Updated, Fully Updated

### ISSUE THREAD

**Issue by smurphos** [linuxmint/mintupdate#320]
Hi, title says it all really.

18.3 shield behaviour still causes consternation and confusion for some users upgrading from earlier versions - e.g. https://forums.linuxmint.com/viewtopic.php?f=18&t=263867

It might be clearer if the Shield had 3 states for update status.

1) Fully updated - all updates installed including security.
2) Partially updated - outstanding security updates only.
3) Updates available - non-security (and security if applicable) updates outstanding.

**Comment by smurphos** [comment]
Alternatively which gives more emphasis to the importance of security updates but arguably will do less to reduce confusion

1. Fully updated.
2. Non-security updates only available.
3. Security (and non-security if applicable) updates available.

In both cases the user's policy choice or manually set preferences for level and visibility of kernel and security updates would still be respected in determining the state of the shield icon.

**Comment by xenopeek** [comment]
Many thanks for contributing to mintupdate. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
