### ISSUE TITLE
[Feature request] - add the apt-fast wrapper to speed up downloading updates/upgrades

### ISSUE THREAD

**Issue by gothicVI** [linuxmint/mintupdate#325]
From time to time - be it when there are updates containing a lot of files or simply when installing many packages e.g. at a version upgrade - downloading the packages is painfully slow due to the serial download process.
[apt-fast](https://github.com/ilikenwf/apt-fast) circumvents this issue by allowing up to 16 parallel downloads even from multiple mirrors!
I'm using it personally with no issues for over a year now. However, this restricts performing updates/upgrades and package installations to the terminal. Having the same functionallity also in mintupdate or even in synaptic, i.e. everywhere where apt is called, whould be really nice.

**Comment by xenopeek** [comment]
Many thanks for contributing to Linux Mint. Your suggestion was reviewed.
For more information on our workflow and feature requests, see https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
