### ISSUE TITLE
Unable to update after adding ppa during  software update

### ISSUE THREAD

**Issue by PaxGourou** [linuxmint/mintupdate#327]
Bug in Mint 18.2 and MintUpdate 5.2.9
I'm unable to refresh the list by the graphical way, but it is possible in terminal.

**Comment by xenopeek** [comment]
Hi, as written this observation doesn't have enough information for a developer to work on. I tried reproducing it by adding a PPA, installing updates afterwards through mintupdate and while that was ongoing adding another PPA (for which mintsources didn't permit me to refresh the cache as it saw mintupdate was installing updates). The updates installed fine so we need more detailed steps for how to reproduce the issue to be able to work on it.

If you need help solving your issue, or you want to take help to find the steps needed to reproduce the issue, please use the [forums](https://forums.linuxmint.com/). See our [troubleshooting guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) for why I ask you to do that. This issue can be reopened if you add more detailed information.
