### ISSUE TITLE
Call for attention when needed

### ISSUE THREAD

**Issue by macarena** [linuxmint/mintupdate#331]
Hi everyone,
It's really common for me to start an update and just minimize the mintupdate windows. I guess it's a common behavior for any other user too.
But sometimes it requests an action (like when it can't download all the packages and asks if you wanna continue with the downloaded ones) which I take minutes, even hours, to realize since it's minimized. I don't know if there is any other case in which it happens, but anyway it should be interesting to have some kind of "call for attention", like some notification, or change the systray icon, anything like that.

**Comment by xenopeek** [comment]
Many thanks for contributing to mintupdate. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
