### ISSUE TITLE
The old kernel version is not displayed

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#332]
By default, the "Old version" column in the Update Manager displays the version of the existing package. The Linux kernel seems to be an exception, because its (old/running) version is not displayed.

**Comment by kneekoo** [comment]
The only one that has the version displayed is the 4.4 kernel stuff.
![mint-18 3-kernel-4 4-update](https://user-images.githubusercontent.com/566306/39141824-24846146-4729-11e8-91dc-6f49c2f9e498.png)

Any other kernel release doesn't have its version displayed in the "Old version" column.
![mint-18 3-kernel-4 13-update](https://user-images.githubusercontent.com/566306/39141829-27bdf62e-4729-11e8-9ebd-aa47968fbcb7.png)

Mint 18.3 Cinnamon 64-bit, mintUpdate 5.3.2.1.

**Comment by kneekoo** [comment]
The issue is still present in mintUpdate 5.3.2.3.
![no-old-kernel-version](https://user-images.githubusercontent.com/566306/39988321-584eb7a8-5767-11e8-8a70-13d89082b961.png)

**Comment by smurphos** [comment]
Kernel packages are standalone - technically you are not updating an existing kernel package you are installing an additional one, hence there is no 'old version'.

Other packages are being updated - the old version is overwritten by the new version.

**Comment by kneekoo** [comment]
Once a new kernel package comes up, there's always at least one older version installed. So the difference between the kernel and regular package updates doesn't matter - the versions should be displayed. And it actually is for kernel 4.4, as you can see in my earlier post.

**Comment by gm10** [comment]
Closing this. The old version will show correctly as long as you've got the respective meta-package installed, i.e. either `linux-generic` for LTS or the respective `hwe` meta package. 5.4.2 already made the change to always install the LTS meta, with the 19.2 release also the HWE meta will automatically be added should you manually add a HWE kernel as in your example.
