### ISSUE TITLE
[Feature request] Provide low-latency version of kernels in addition to the generic type

### ISSUE THREAD

**Issue by minto0s** [linuxmint/mintupdate#336]
For each version of the kernel I would see two check boxes; one for generic the other for low-latency. If both are selected they get installed simultaneously. If only one, then the selected type. Or none, then nothing happens.
Low latency kernels not only help multimedia, but at least some types of virtual machines.

**Comment by xenopeek** [comment]
This is related to #200.

**Comment by monsta** [comment]
@clefebvre @xenopeek: you can close #200 as https://github.com/linuxmint/mintupdate/commit/bbb50cf2e06397b9d2bbaad6cfa22fed20369253 should take care of it. Not sure about this report.

**Comment by xenopeek** [comment]
Support for lowlatency kernels is currently implemented as an advanced feature. To enable mintupdate to use lowlatency kernels run this on Linux Mint 19:

`gsettings set com.linuxmint.updates use-lowlatency-kernels "true"`

It's implemented somewhat differently from this feature request: either generic or lowlatency kernels will be displayed in mintupdate, not both at the same time.

**Comment by S-Marais** [comment]
@xenopeek the approach provided by the commit actually doesn't fix anything. It works exactly like if nothing had changed.

**Comment by xenopeek** [comment]
Take a closer look. Installing a new kernel through Update Manager > View > Linux kernels, after enabling use of low latency kernels, installs the low latency kernel as expected.

**Comment by S-Marais** [comment]
so yes it works but it has been a bit weird before it started to work properly. First it did not  show anything then after a few tries it finally showed what was required but not the latest (I could only install 4.15-23 and not 4.15-24) and finally today all went well. I'm not sure why tho.
