### ISSUE TITLE
[Feature request] Provide support for ubuntu mainline kernel ppa

### ISSUE THREAD

**Issue by minto0s** [linuxmint/mintupdate#338]
Kernels from Ubuntu's mainline kernal ppa are most useful when new hardware drivers are not yet retrofitted in Ubuntu or Linux Mint's stable kernel collections.

Those kernels often work quite well to the point that one might even elect to run one of them on a permanent basis. Installing them manually is not difficult but it would add value to Mint if it was integrated in it mintupdate's kernel window. 

Of course one can already install ukuu to do that, but ukuu (like mintupdate) currently does not support kernel types other than generic. 

As discussion is underway here to supplement generic type kernels with low latency type ones which provide distinct benefits to AV intensive software users, I think it would be a good idea to combine these two things into one solution.

Implementation method wise, forking ukuu and modifying it to support 
a) both low latency and generic kernels from 
b) main Linux Mint kernel repository as well as Ubuntu's mainline kernel ppa, then 
c) using the resulting material as the current kernels window under mintupdate and 
d) removing all kernel related material from mintupdate's main window 
would provide a worthwhile improvement, especially if the kernel selection mechanism also uses 
e) a checkbox system where generic, low-latency types of a given kernel can be installed individually or simultaneously while being pulled from their native repositories (x.y.0-nn from Mint, x.y.z-nnnnnn from mainline).

**Comment by gm10** [comment]
The code for doing that exists, but it's not being released for policy reasons, not wanting to promote that kind of kernel. Even if that position changes in the future, there's no way we'd hide kernel updates from the main window as per your d). I don't even understand why you'd suggest that?

Along the same lines, mintupdate does already support lowlatency kernels, but that support is hidden behind a dconf setting. 

Closing this.
