### ISSUE TITLE
Incorrectly listing kernel versions

### ISSUE THREAD

**Issue by RobinKnipe** [linuxmint/mintupdate#351]
It looks like the Update Manager is listing old versions of the kernel (and associated packages):
![image](https://user-images.githubusercontent.com/7834222/39309234-6baf2a50-495f-11e8-8e7f-86e40f76de70.png)
I'm currently running version `4.14.34`, but the Update Manager seems to want to install version `4.4.0`.

**Comment by clefebvre** [comment]
Hi @RobinKnipe,

It's not the kernel itself but the META package linux-image-generic. You can see the included package at the bottom of the description.
