### ISSUE TITLE
Ignoring of auto updating settings

### ISSUE THREAD

**Issue by travel1988** [linuxmint/mintupdate#353]
Hello.
MintUpdate programm ignores settings of auto updating. It must update list of packets once a week, but it updates them every day.

Laptop is Sony VAIO VPCEH2S1R.

mintupdate:
  Installed: 5.3.2.1
  Candidate:   5.3.2.1
  Version table:
 *** 5.3.2.1 500
        500 http://packages.linuxmint.com sylvia/main amd64 Packages
        500 http://packages.linuxmint.com sylvia/main i386 Packages
        100 /var/lib/dpkg/status

[dmesg.txt](https://github.com/linuxmint/mintupdate/files/1976402/dmesg.txt)
![screen](https://user-images.githubusercontent.com/38999523/39660504-4bdbb90a-5049-11e8-98b0-bf5d0783a30d.png)

**Comment by icarter09** [comment]
@travel1988 are you still having this issue? I'm able to change the auto update settings to and Mint is picking up on the changes, which causes the updater to refresh correctly.

**Comment by travel1988** [comment]
Yes, I'm still having this problem on Linux Mint 18.3, but i didn't use 19 and i wonder if there is such a problem.

**Comment by icarter09** [comment]
@travel1988 I'm currently on Mint 19. Whenever you upgrade to 19, can you check if this issue still persists?

**Comment by travel1988** [comment]
Ok, I'll upgrade and check this moment when I'll have an opportunity for this. And then I'll write you back.

**Comment by travel1988** [comment]
I checked MintUpdate in Mint 19. Everything is good. Thanks for support.

**Comment by travel1988** [comment]
Now after my last message and using Mint 19 i have opposite situation. As i discovered automatic checking is absent.

**Comment by icarter09** [comment]
@travel1988 can you provide a screenshot of the Update Settings, like you did at the beginning of this ticket? Thanks.

**Comment by icarter09** [comment]
@travel1988 I'm noticing some odd behavior as well when I'm testing this out on my desktop instead of my laptop. I'll start looking more into the issue. Does it work when you alter the hours or minutes?

**Comment by travel1988** [comment]
It is the same situation when i alter minutes.

![screen](https://user-images.githubusercontent.com/38999523/48976821-1bb34580-f09f-11e8-8924-23b06aa1b6da.png)

**Comment by travel1988** [comment]
Noticing the situation i observed that time settings work only when my laptop is switch on. So after my laptop switching off the time altering goes from the beginning.

**Comment by icarter09** [comment]
@travel1988 I just verified through the logs that the Auto-refresh is working correctly for minutes. In a couple of days, I'll be able to verify the days and hours as well. 

Help troubleshoot this....Run `mintupdate` from the terminal and it will log to `/tmp/mintUpdate/{log file}`. If you "tail -f" the log file, you should be able to see it auto-updating taking place. 

Let me know if this helps out any.
