### ISSUE TITLE
Main window and Update Policy window too tall to be usable on netbook screens

### ISSUE THREAD

**Issue by bplu4t2f** [linuxmint/mintupdate#354]
Both the main window and the Update Policy window are too tall to fit on a 1024x600 netbook screen. In the Update Policy window it is not even possible to confirm the selection with Enter, so you have to navigate blindly to the OK button with Tab.

**Comment by xenopeek** [comment]
You can move windows that are too tall for your screen up above the top of your screen so you can reach the bottom half of such windows. You can either press Alt+F7 and then move your mouse cursor to move the window and left click to release the window, or hold down the Alt key and then drag the window with the left mouse button held down on it.
