### ISSUE TITLE
mintUpdate kills itself when launched a second time

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#355]
I was updating today while posting new info on #332, and I wanted to add the mintUpdate version. The main window is disabled for user interaction while the update is running, so I couldn't go to Help -> About.

_No problem_, I said. I fired up a terminal and issued a command:
`mintupdate --version`

To my surprise, mintUpdate killed itself and a new instance showed up with all the available updates listed in the window, like nothing happened. I didn't know what happened behind the scene. Did the update process get killed as well? If so, would I have to **apt -f install** or try installing the updates again, like nothing happened?

Anyway... a minute or two later, while trying to refresh the updates list, I got the message that APT is already running, and I found the notification window that the update had completed successfully.

So here are the main issues:
- mintUpdate doesn't check if there's an instance up and running, killing any active instance without caring about the consequences;
- mintUpdate doesn't pick up the ongoing update process to display the progress or at least a notification that an update is running in the background, so the user knows what's going on, and not worry;
- mintUpdate should check if it's called from the terminal and respond accordingly: (1) if you pass no parameters, it should warn there's already an active instance and that the user can **--force** starting a fresh instance if the other is simply an old one that got stuck for whatever reason, and (2) if you give mintUpdate some parameters, it could respond accordingly - **--version** with the version number, etc.

The first time I noticed this self-kill issue was starting mintUpdate manually immediately after startup, so I can check for updates. As soon as the delayed-start mintUpdate starts up, my existing instance got killed. Quite annoying, but at least I didn't worry about it like it happened today.

Please try to address this as soon as humanly possible. Hopefully it will be ready for Mint 19 and LMDE 3. :)
Thanks!

**Comment by chingyinwan123** [comment]
Should I consider whether the user would delete the pid file after creating an active mintUpdate instance and before the mintUpdate window closes?

**Comment by chingyinwan123** [comment]
If multiple instances of mintUpdate are opened and their windows are closed, there would be multiple instances of mintUpdate running in the background.

To preserve system memory, some instances of mintUpdate need to be killed after their windows are closed. Perhaps all instances other than the first instance of mintUpdate (i.e. the instance of mintUpdate opened before the force-started instances) could be killed when their windows are closed?

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintupdate/commit/71f501b256e99ae16ec31edf7e5088c317b344ac
