### ISSUE TITLE
[feature request] Checkboxes to allow removal of multiple kernels

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintupdate#357]
At the moment, if you have several kernels installed and want to purge more than one of these, you have to go through the removal process for each one, including entering the password each time.

It would be helpful to allow the user to select multiple kernels for removal, perhaps through use of checkboxes, the selected kernels then being queued and removed one after another. This is especially useful for someone who has not kept on top of purging old kernels and has amassed a large number of them.

**Comment by xenopeek** [comment]
Many thanks for contributing to mintupdate. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
