### ISSUE TITLE
system wide config settings (w/o hacking mintUpdate.py)

### ISSUE THREAD

**Issue by rik-shaw** [linuxmint/mintupdate#36]
It would be nice to configure various "system wide" settings (users can of course override with their own settings in their home directory).  An example I would like to adjust is the refresh frequency.  Right now, it seems that the default values are hard coded in mintUpdate.py, to timer_minutes = 30, timer_hours = 0, timer_days = 0.

This used to be configurable in /etc/linuxmint/mintUpdate.conf

**Comment by JosephMcc** [comment]
Unless I misunderstand you, you can configure refresh timeouts in Edit->Preferences on the auto refresh tab.

**Comment by rik-shaw** [comment]
@JosephMcc I am referring to a "system default" or "all users" change.  Yes, individual users can customize via Edit | Preferences but is there no way to adjust the "system level" default?  So this isn't an "individual user" need but rather a "system administrator" need.

**Comment by mtwebster** [comment]
There are a couple ways to override the 'default' values for gsettings - check out http://askubuntu.com/questions/65900/how-can-i-change-default-settings-for-new-users, i know there are debian hooks you can use (for example, make a dummy package that all it has is an overrides file)

**Comment by JosephMcc** [comment]
You can look in /usr/share/glib-2.0/schemas/ and find several .override files. They should be an example of mtwebster is talking about. You find one in there that sets default themes and stuff for linux mint: linuxmint-artwork.schema.override
