### ISSUE TITLE
Update inidcator shield does not change to green check mark after updates applied.

### ISSUE THREAD

**Issue by navyguns** [linuxmint/mintupdate#361]
When updates are available the shield has the blue dot. After updates are applied through the update manager and the update manager refreshes, the shield does not change to the green check mark. After a reboot, the shield has the green check mark. Mint 19 Cinnamon Beta on HP15-d069wm i3 6GB RAM.

**Comment by navyguns** [comment]
It does not update with a cog when refreshing the list. The blue dot remains during refresh and after installing updates.

**Comment by navyguns** [comment]
Looking at the Information, the last update gave this:

(synaptic:11945): Gtk-CRITICAL **: 11:59:36.970: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
06.06@11:59 ++ Return code:0 
06.06@11:59 ++ Install finished 
06.06@11:59 ++ Starting refresh 
06.06@12:00 ++ System is up to date 
06.06@12:00 ++ Refresh finished 
06.06@12:16 ++ Starting refresh (including refreshing the APT cache) 
06.06@12:16 ++ System is up to date 
06.06@12:16 ++ Refresh finished

**Comment by clefebvre** [comment]
ok it looks like a systray issue in cinnamon then. I'll close this here, no need to report it to Cinnamon, we've gathered similar feedback on systray in the blog comments, we'll be looking into it.
