### ISSUE TITLE
Update Manager freezes when using bad mirror

### ISSUE THREAD

**Issue by rdelval** [linuxmint/mintupdate#362]
Changed the mirrors I was using for updating to the evowise in Linux Mint 19 beta.

Unfortunately, the evowise mirror is having issues.
```
$ sudo apt update
Hit:1 http://mirror.math.ucdavis.edu/ubuntu bionic InRelease
Hit:2 http://mirror.math.ucdavis.edu/ubuntu bionic-updates InRelease                          
Hit:3 http://mirror.math.ucdavis.edu/ubuntu bionic-backports InRelease                        
Hit:4 https://dl.yarnpkg.com/debian stable InRelease                                          
Hit:5 http://archive.canonical.com/ubuntu bionic InRelease                                    
Ign:6 http://mirrors.evowise.com/linuxmint/packages tara InRelease                            
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Get:8 http://mirrors.evowise.com/linuxmint/packages tara Release [24.1 kB]
Get:9 http://mirrors.evowise.com/linuxmint/packages tara Release.gpg [819 B]                  
Ign:9 http://mirrors.evowise.com/linuxmint/packages tara Release.gpg                          
Get:10 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11 Metadata [204 B]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 DEP-11 Metadata [2,456 B]
Reading package lists... Done                 
W: GPG error: http://mirrors.evowise.com/linuxmint/packages tara Release: The following signatures were invalid: BADSIG A6616109451BBBF2 Linux Mint Repository Signing Key <root@linuxmint.com>
E: The repository 'http://mirrors.evowise.com/linuxmint/packages tara Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
This makes the update manager freeze and become non operational. The Update Manager did give me a warning and a chance to change the mint base. Unfortunately, I did not and it led to the Manager freezing upon trying to refresh.

Any time I bring the update manager now, it freezes upon starting up making it impossible to change the settings through the GUI. Ideal behaviour would be to detect a bad mirror and prompt the user to change the mirror.

Left alone long enough, the system prompts the user to force quit:
![image](https://user-images.githubusercontent.com/1643994/41187680-cf084db8-6b63-11e8-9009-e54c03b70709.png)

Is there anywhere I can pull logs from? I tried looking but wasn't able to find any.

**Comment by just4t** [comment]
Same issue here running **Linux Mint 19 Tara beta** in **VirtualBox**:  _evowise CDN_ mirror being reported as not signed and trying to change default mirror fails, too

Then now, the **Update Manager** hangs trying _Finding the list of updates..._

- Running _sudo apt-get update && apt-get upgrade -y_ fails at:

_Ign:6 http://ftp.cixug.es/mint/packages tara InRelease                         
Get:7 http://ftp.cixug.es/mint/packages tara Release [24,1 kB]                 
Ign:8 http://ftp.cixug.es/mint/packages tara Release.gpg                       
Reading package lists... Done                                  
E: The repository 'http://ftp.cixug.es/mint/packages tara Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details._

Hope this helps to debug it

**Comment by just4t** [comment]
[SOLVED] 180620-2100-CEST: Looks **_repository ... is no signed_** has been fixed and **_Update Manager_** updated, today ;)
