### ISSUE TITLE
Cancelling update process during download does not work

### ISSUE THREAD

**Issue by ragsu** [linuxmint/mintupdate#366]
Pressed cancel during the download phase of kernel update and the updater still continued to installing the half downloaded kernel and ending up in errors; still showing in the mintupdate as if the kernel was properly installed.

**Comment by kneekoo** [comment]
Can you absolutely confirm that you canceled during the download phase, and not the install phase? Because I've canceled update downloads a few times in the past, and it didn't try to update my system with the stuff it brought in by that point.

**Comment by ragsu** [comment]
There is a chance that the download was just about to finish, or just finished at the point of the click.

**Comment by icarter09** [comment]
@ragsu is this still an issue?

**Comment by ragsu** [comment]
I manually fixed it by switching the Kernel at startup. I have not tested if the bug is repeatable.

**Comment by icarter09** [comment]
@ragsu could you test if it is repeatable whenever you have a moment? Thanks.

**Comment by gm10** [comment]
Closing this. You get a confirmation window asking you whether you want to proceed if you cancelled the download, so this was probably user error. Also I'm looking into dropping synaptic usage entirely, anyway.
