### ISSUE TITLE
I want to have the newest kernels available

### ISSUE THREAD

**Issue by Nikolice** [linuxmint/mintupdate#367]
Greetings.
I saw the kernel's version № «4.17.4» – as being the «latest» stable now: on the «[www.kernel.org](https://www.kernel.org/)» (which (the site) – is supported by the «Red hat enterprise's „Linux‟»)… And (some similar), – is _provided_ – for a _de-fault_ – in a «newest» „**Fedora Core**‟ (v. № 28; workstation edition) distribution…

How – can we (Minters) – have the _latest_ precompiled kernels, _too_? … Even – if they – were built «_for_» «Fedora»?

**Comment by clefebvre** [comment]
https://wiki.ubuntu.com/Kernel/MainlineBuilds
