### ISSUE TITLE
Bug: Kernel Meta packages get ignored

### ISSUE THREAD

**Issue by gm10** [linuxmint/mintupdate#369]
Noticed that the 4.15.0-24.26 problem is mostly home-made. That version was revoked by Ubuntu weeks ago but Mint users still see it in their update manager. 

The reason is simple, after the check for kernel meta packages in checkAPT.py the code does not return, eventually landing on the manual detection process and pulling in the latest in the series.

The latest version of the meta package is -23 at this time, but the dependencies of version -24 are still in the repo and get flagged as updates by that code.

**Comment by Pjotr123** [comment]
Bad bug. Should be fixed....
