### ISSUE TITLE
mintupdate-cli -i argument description issue

### ISSUE THREAD

**Issue by gm10** [linuxmint/mintupdate#371]
https://github.com/linuxmint/mintupdate/blob/master/usr/lib/linuxmint/mintUpdate/mintupdate-cli.py#L27

Reference to `/etc/mintupdate-cli.blacklist` should be to `/etc/mintupdate.blacklist`.

**Comment by ehtron** [comment]
Hi :)
mint 19 tara 64 cinnamon

ignore in mintupdate-cli does not work... 
like 

linux-headers-4.15.0-24-generic
linux-modules-*
linux-image-*
linux-modules-extra-*


in /etc/mintupdate-cli.blacklist or /etc/mintupdate.blacklist and 
as -i / --ignore parameter also.

`/usr/bin/mintupdate-cli upgrade --ignore linux-headers-4.15.0-24-generic --refresh-cache --dry-run --yes`

we need a prameter like the kernel settings in the gui options to ignore kernel updates...

regards ehtron
