### ISSUE TITLE
A mistake in translation

### ISSUE THREAD

**Issue by malccin** [linuxmint/mintupdate#373]
In the Polish version there is a small slip in the edit menu. It is now: "Zaznacz **aktualzacje** jądra systemu" It should be written "Zaznacz **aktualizacje** jądra systemu".

**Comment by chingyinwan123** [comment]
I have corrected the translation error.

**Comment by chingyinwan123** [comment]
Hello. I would like to work on this issue. How do I contribute to fixing this issue?

This is my first time trying to make a contribution on Github. I am not sure how to make a contribution to a repository.

**Comment by xenopeek** [comment]
Hi, we have a [translator guide](https://linuxmint-translation-guide.readthedocs.io/en/latest/) that should get you started with helping to complete/improve translations.
