### ISSUE TITLE
Giving priority to "mint-artwork.gschema.override"

### ISSUE THREAD

**Issue by jalansari** [linuxmint/mintupdate#375]
Currently, the default system gsettings are treated as highest priority, which makes it difficult to override them.

Can the following file be renamed?
From:
`/usr/share/glib-2.0/schemas/mint-artwork.gschema.override`
to a name using a priority number, e.g.:
`/usr/share/glib-2.0/schemas/20_mint-artwork.gschema.override`

This would allow users to further override/customise the system settings, using higher priority numbered overrides, e.g.:
`/usr/share/glib-2.0/schemas/70_my-higher-priority-settings.gschema.override`

**Comment by clefebvre** [comment]
No, users don't usually need to do that and if they do there's plenty of space after m in the alphabet.
