### ISSUE TITLE
Separate APT cache updates from list gathering in checkAPT.py

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mintupdate#379]
in Debian, when sudo is invoked, checkAPT.py cannot access the user's dconf storage, so it sees the root settings and blacklist instead.

Here's an issue caused by this:
https://github.com/linuxmint/mintupdate/issues/259
https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/50

One solution would be to drop priviledges to read the settings, or to separate checkAPT into two distinct parts, one to update the cache (with sudo) and one to gather the list (as user).

We can also consider using aptdaemon for cache updates (which doesn't require admin privs) and drop sudo usage altogether.

**Comment by Forkest** [comment]
Could be related to #169.

**Comment by lguez** [comment]
I think I have the same issue with Linux Mint 19. In the blacklist tab, I added sane-utils, simple-scan, sane-backends, libsane-common and libsane. And I checked "Apply updates automatically" in Auto-upgrade. I also locked the packages in Synaptic package manager. The blacklisted and locked packages are upgraded during the automatic upgrade.
