### ISSUE TITLE
[Feature request] Kernel Mainline and Liquorix Kernel Support For Kernel Window

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintupdate#381]
Hi,

Could you add kernel mainline and Liquorix kernel support for Mintupdate's kernel window.

Kernel mainline's packages starts with linux-image-unsigned-* .

Liqorix kernel's packages starts with linux-image-* but end with *-liquorix-amd64, *-liquorix-686 or *-liquorix-686-pae .

Best regards

**Comment by Magissia** [comment]
Adding mainline kern package support would ease tests using "bleeding edge" canonical's kernel builds from the official kernel ppa (such as http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.18.3/ )

**Comment by xenopeek** [comment]
Thanks for contributing to mintupdate. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by kelebek333** [comment]
@Magissia thank you.

@xenopeek , could you open this issue for Liquorix Kernel Support.
