### ISSUE TITLE
Fingerprint authorisation not possible since LM 19

### ISSUE THREAD

**Issue by bitboy85** [linuxmint/mintupdate#382]
After upgrading to LM 19 Cinnamon it is not possible to authorize the installation of updates with fingerprint GUI. It was possible in every LM 17.x and 18.x version.
Using sudo or gksudo in the terminal correctly fires up the fingerprint gui. Login is also working fine so i guess it is an issue with mintupdate.

**Comment by xenopeek** [comment]
This issue isn't in a state where a developer could do work on it, if the responsible component would be one maintained by Linux Mint. I suggest you ask for help with troubleshooting by posting a new topic on the [support forum](https://forums.linuxmint.com/).
