### ISSUE TITLE
Cannot update via mintupdate

### ISSUE THREAD

**Issue by Moini** [linuxmint/mintupdate#384]
I don't know what caused this problem, but this is what's happening:

- mintupdate (graphical version) works insofar as it is downloading the list of updates and displaying them

- as soon as I try to actually run an update, I get the error message (similar, but not exactly): "Couldn't install security updates." It does not ask for my password, just fails.

- when I try to access the list of ppas, the cursor shows a waiting animation for a couple of seconds, and that's all. After that, the program just 'works' as it did previously. No error message, no password asked, no nothing.

- when I try to debug the program, starting from the command line, it just seems to start the process, and then it just returns to the normal prompt, without any output, so I don't know how to get any useful error message to understand what is happening. Please let me know how to gain access to some useful debugging output.

- Update: Accidentally, I kept the terminal open this time. Interestingly, it still prints an error message (after a new prompt was printed!) when I try to access the ppa list:

`~$ ==== AUTHENTICATING FOR com.linuxmint.mintsources ===   
Software Sources   
Authenticating as: Username,,, (username)   
Password:    
** (process:31072): ERROR **: 17:35:17.309: Got unexpected EOF while reading from controlling terminal.   
polkit-agent-helper-1: pam_authenticate failed: Authentication failure   
`

It might have to do with the ppas, I suspect mintupdate somehow cannot deal with the files. Let me know if you'd like to have any of them. Or with an encrypted home directory - this didn't happen before that was encrypted.

Updating, adding ppas, etc. all works fine when done with apt on the command line. So I currently use mintupdate to know when there are updates, then I open a terminal, and do the actual update... 

This is with Linux Mint 19, MintUpdate 5.4.0.

**Comment by xenopeek** [comment]
I suggest you ask for help with troubleshooting by posting a new topic on the [support forum](https://forums.linuxmint.com/), to narrow down on the exact cause.
