### ISSUE TITLE
Update download speed limiter

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#385]
I'm currently dealing with updates at a customer and although the download bandwidth is enough for the IPTV service running on it, the downloading the updates makes the stream freeze. It would be great if I could limit the download speed either system-wide or for a specific tool: update manager, mintinstall etc.

I found a console tool named **trickle** capable of doing such things, but the problem is mintupdate spawns multiple processes and trickle is tied to the process launched directly with the terminal command. For instance, to start a program with a 100 KB/s download rate, you would do this:
`trickle -d 100 program`

I also tried wondershaper as a system-wide traffic shaper and the documentation is too short, not updated and it's also a console tool, so it's neither user-friendly and good enough.

Is there something else that could be added to Linux Mint or even a working solution for update manager and mintinstall so we can easily limit the download speed?

**Comment by gm10** [comment]
This can just be set as an apt option. Create a file in `/etc/apt/apt.conf.d` with this content:

```
Acquire
{
  Queue-mode "access";
  http
  {
    Dl-Limit "100";
  };
};
```
This will limit all of apt's http downloads to 100 KB/s. Also the ones that are triggered manually. Add additional protocols as needed.

Personally I don't see a need to add something like this to mintupdate, I don't think many users need this.

**Comment by kneekoo** [comment]
Thanks, that's a handy tip. I completely forgot about the APT's configurability. It would be nice if mintupdate would be able to control this APT setting. I don't think this feature should have a high priority, but it can be quite helpful to have an easy way to limit the speed without manual edits, which is prone to user errors.
