### ISSUE TITLE
 Preferences / Einstellungen window hight to low #370 

### ISSUE THREAD

**Issue by ehtron** [linuxmint/mintupdate#386]
Hi :)
mint 19 tara / 64 upgrade from 18.3

after update to v. 5.4.1 tara,
the issue #370  is **not** gone...

**Comment by JosephMcc** [comment]
As I mentioned in the other issue, this isn't a bug. We don't know how long these strings might become under different translations. Just forcing the window taller and taller to accommodate them isn't a good solution. Closing this since it isn't a bug.
