### ISSUE TITLE
Where is the README?

### ISSUE THREAD

**Issue by Hyd3L** [linuxmint/mintupdate#388]
This is a fantastic update manager, and I wish to install it on my Debian Cinnamon system,
but this repository lacks of a README.

**Comment by Hyd3L** [comment]
I was looking for some sort of install instructions for other distros.
This is a Python form that calls Synaptic Package Manager, so it should
be easy to install on Debian, but it's not because it has some other mint
packages as dependencies that apparently conflict with some other debian packages.
I actually don't remember exactly which were these packages, cause I tried this installation
sth like 1 month ago.

**Comment by ewangi** [comment]
@Hyd3L: mintinstall is for use in the Mint ecosystem and depends, for example, on mint-common, so I assume that it would not be wise to try to install it on a Debian system. Your reason for a README file is therefore not relevant in this case.

However, have you thought about requesting that the Mint developers consider making mintinstall distro-agnostic in the same way that Cinnamon is? If so, you could create a new issue with that as a requested/suggested feature. There may be good reasons why this isn't feasible, technically and/or strategically, but perhaps there aren't.

**Comment by Hyd3L** [comment]
@ewangi yea! You got it.
Cinnamon is distro-agnostic, and mintupdate is a nice tool.
A newbie in GNU/Linux wouldn't install Debian probably, they'd go for Mint,
however there could be cases where somebody installs Debian for other people,
and wants to provide a much easier way to run updates to its users.
Therefore mintupdate would be nicer if it will ever become distro-agnostic,
in any case.... there's Mint Debian Edition, which is almost the same thing,
so I'd understand if this idea is not so relevant atm.

**Comment by xenopeek** [comment]
See new issue #438.
