### ISSUE TITLE
Kernel cleaning code snippet for inclusion in mintupdate?

### ISSUE THREAD

**Issue by Pjotr123** [linuxmint/mintupdate#389]
I've posted a script on GitHub with which to clean out many old unused kernels at once, which I've cherry-picked from the byobu package.

Perhaps it can be incorporated into mintupdate? There's definitely a need for easily getting rid of many old kernels at once...

The code is here:
https://github.com/Pjotr123/purge-old-kernels-2

**Comment by gm10** [comment]
Supporting this. Users having trouble with full /boot partitions are a common issue on the forums, an option in mintupdate that takes care of kernel housekeeping for the average user would be a good thing to have.

**Comment by gm10** [comment]
Closing this, should have been fully addressed with the Remove old kernels button and the upcoming autoremove automation option.
