### ISSUE TITLE
Add flatpak support

### ISSUE THREAD

**Issue by krajcsi** [linuxmint/mintupdate#404]
If I'm correct, update manager currently doesn't support flatpak packages, i.e., if a flatpak package is updated e.g., on flathub, it will not be displayed and updated with the update manager. But is would be nice if the update manager could do this, to make the flatpak support of Mint more complete, and to have a more coherent software management.

**Comment by gm10** [comment]
See existing suggestion and answer to it (always search first): https://github.com/linuxmint/mintupdate/issues/296

**Comment by krajcsi** [comment]
Thanks! Sorry for the noise, for some reason I couldn't find that issue.

**Comment by gm10** [comment]
Likely because by default only open issues are listed, but the Mint team closes suggestions once they've reviewed them.

**Comment by krajcsi** [comment]
Yeah, I may supposed that only implemented feature requests are closed. I'm closing this one.
