### ISSUE TITLE
Hide older kernel versions ... by age or 4.xx ...

### ISSUE THREAD

**Issue by aspadistra** [linuxmint/mintupdate#406]
It would be really nice if one could hide older kernel versions ... by age or 4.xx ...

[ ] 4.4
[ ] 4.8
[ ] 4.10 
[ ] 4.11
[ ] 4.13

Are all not the current newest, so should be subject to hiding ... unless one is running a kernel that old ... 

Also "Hiding By Age" might be worth considering as an alternate, as kernels older than 250 days (unless one is running a kernel that old) should be subject to hiding. 

This really would clean up the user interface, and at least in the era that I am typing this -- the User Interface should recommend hiding ...

[ ] 4.4 
[ ] 4.8

**Comment by gm10** [comment]
4.4 should not be hidden. In fact if you were to hide anything, it's the only one that should be shown, since it's the only kernel that's still supported in your entire list, all the others are past end-of-life. Version numbers can be deceiving. ;)

That said, it would be good to indicate whether a kernel is still supported.

**Comment by aspadistra** [comment]
WEATHER on is using MINT or UBUNTU or DEBIAN ... UKUU is a must for kernel management. 

It just shows the entire list of active kernels, and does not do filtering of them either. 

HOWEVER, MINT is at least aiming at less skilled users ... and having a cruise liner full of kernels and no UKUU in sight is not a good idea. 

SOME kernels shown by MINT -- I ASSUME -- are "UNSTABLE" or marked "DO NOT USE" -- but that marking is inaccessible in the UI of the MINT UPDATER! 

The MINT UPDATER [at least] can check to see what version of MINT it is running on ++ and alter the hiding options (and recommendations for hiding options) ++  ... as obviously if one is running MINT_ver = UBUNTU 14 ... you need to see the older kernels and not see some of the newer ones.

**Comment by gm10** [comment]
Well, your issue had inspired me to add this earlier (#413):
![](https://i.imgur.com/Sta3hma.png)
![](https://i.imgur.com/FxDG2DC.png)
The support status mean, not the mainline kernel integration, that's my private feature. 

If that patch gets accepted then an option could be added based on that to hide kernels that have reached end of life.

**Comment by aspadistra** [comment]
I wish I could remember what other Linux kernal installer (not UKUU, obviously) indicated "Unsupported" or "End of Life" or "DO NOT USE" ... 

This oddly is a Linux only issue, as BSD kernel updates are about 40 days slower -- and the kernel update process is a 'Administrativa Hell on Wheels' in its slowness. 

My favorite kernel is MINIX3, that can be memorized by wrote (and the mousy and keyboard drivers too...) as all of them are under 5k of C++. 

The tragedy of Linux + BSD + MINIX3 + BEOS ...
-- NOT WRITTEN IN ADA95 (exception for complier directives for ADA2014). 
-- ADA code not "Bandstop Limited" to 12.5% Object Orientation.
