### ISSUE TITLE
Incorrect l10n string

### ISSUE THREAD

**Issue by NunoMCSilva** [linuxmint/mintupdate#417]
https://github.com/linuxmint/mintupdate/blob/44401bddc2e38a83b9c3f3bc1d0ceca7c5eae2a1/po/mintupdate-pt.po#L1671

The correct string would be "Mostrar sempre atualizações do kernel".

**Comment by NikoKrause** [comment]
I've changed it on launchpad, but somebody from the translation team needs to approve it.
If you want to help with the translations you can do that on: https://translations.launchpad.net/linuxmint/latest/+lang/pt

Thanks
