### ISSUE TITLE
/etc/cron.daily/mintupdate asking for action in the background

### ISSUE THREAD

**Issue by elbarbudo** [linuxmint/mintupdate#418]
I am running Linux Mint 19 Tara 64-bit MATE, and I activated autoupdate.
At the end of my logs, I got : 
====================================================================
`memoires@memoires5 ~ $ tail -30 /var/log/mintupdate.log
Préparation du dépaquetage de .../gstreamer1.0-packagekit_1.1.9-1ubuntu2.18.04.4_amd64.deb ...
Dépaquetage de gstreamer1.0-packagekit (1.1.9-1ubuntu2.18.04.4) sur (1.1.9-1ubuntu2.18.04.3) ...
Préparation du dépaquetage de .../packagekit_1.1.9-1ubuntu2.18.04.4_amd64.deb ...
Dépaquetage de packagekit (1.1.9-1ubuntu2.18.04.4) sur (1.1.9-1ubuntu2.18.04.3) ...
Traitement des actions différées (« triggers ») pour ufw (0.35-5) ...
Paramétrage de libwbclient0:amd64 (2:4.7.6+dfsg~ubuntu-0ubuntu2.4) ...
Paramétrage de samba-libs:amd64 (2:4.7.6+dfsg~ubuntu-0ubuntu2.4) ...
Traitement des actions différées (« triggers ») pour ureadahead (0.100.0-20) ...
ureadahead will be reprofiled on next reboot
Paramétrage de python-samba (2:4.7.6+dfsg~ubuntu-0ubuntu2.4) ...
Paramétrage de samba-common (2:4.7.6+dfsg~ubuntu-0ubuntu2.4) ...
debconf: Impossible d'initialiser l'interface : Dialog
debconf: (La variable TERM n'a pas de valeur, l'interface dialog est donc inutilisable.)
debconf: Utilisation de l'interface Readline en remplacement
Serveur et utilitaires Samba
----------------------------

Une nouvelle version (/run/samba/upgrades/smb.conf) du fichier de configuration 
/etc/samba/smb.conf est disponible mais la version actuellement utilisée a été 
modifiée localement.

  1. install the package maintainer's version
  2. keep the local version currently installed
  3. show the differences between the versions
  4. show a side-by-side difference between the versions
  5. show a 3-way difference between available versions
  6. do a 3-way merge between available versions
  7. start a new shell to examine the situation

Action souhaitée pour le fichier de configuration modifié smb.conf : `
======================================================================
apt is waiting for an answer it will never get and no further update is possible

**Comment by gm10** [comment]
duplicate of https://github.com/linuxmint/mintupdate/issues/376, fix pending
