### ISSUE TITLE
mintupdate-launcher not exiting in 18.x

### ISSUE THREAD

**Issue by alicektx** [linuxmint/mintupdate#423]
...this got fixed under 19 it seems - would be nice if it got corrected under previous versions as well: https://github.com/linuxmint/mintupdate/pull/317

Super simple fix, but i'm not personally familiar with how to do pull requests i'm afraid...

**Comment by gm10** [comment]
@clefebvre, you got any interest in backporting this one?

**Comment by clefebvre** [comment]
Not this one in particular. I'd be more interested in trying to harmonize versions across 18.x releases and see if we can bring them all under the same branch to make backporting issues easier. This one in particular isn't critical or even serious though.
