### ISSUE TITLE
strange upgrade behavior on clean Linux Mint 19 system

### ISSUE THREAD

**Issue by rimvydukas** [linuxmint/mintupdate#427]
Hi,

Tried to install new laptop today and noticed one interesting thing while tried issue apt upgrade after that. I saw, that apt complained that I have modified /etc/default/grub file and asked me what to do: keep existing file or replace it. It is very strange as this is completely new and clean installation. So I've tried to do another experiment. Did clean reinstall and tried to use update manager. Fired it up and tried to update only grub2 package. Got the same nice warning that I have modified /etc/default/grub file. So is it some kind of bug or am I doing something wrong? I can't remember having such issues in the past when I did apt or update manager upgrades on the clean installs.

**Comment by gm10** [comment]
We discussed this on the forums. This is normal behaviour.

**Comment by rimvydukas** [comment]
> We discussed this on the forums. This is normal behaviour.

Yes, we did this and I've provided additional info regarding this behaviour on the forum. Looking at this I suspect that this is not normal and expected thing.

**Comment by gm10** [comment]
It still is, see my reply to you on the forum (let's keep the discussion to one place ;))

**Comment by jondo** [comment]
Can you link to the forum thread, please?

**Comment by gm10** [comment]
@jondo the gist of it was that the GRUB package changed the format of `/etc/default/grub` in one of the updates earlier this year and thus needs to modify that file. Mint 19's installer, on the other hand, makes a change to that file if Mint is not the only installed OS. GRUB detects that existing modification and asks you before performing its own modification. 

This applies only if you installed from the LM19 iso, it won't happen with the LM19.1 iso as long as a future GRUB update doesn't change the file again.

**Comment by gm10** [comment]
GRUB can also handle the old format but I suggest you just let it replace the file with the new defaults. You won't lose any functionality, no worries, the change the installer makes is actually not needed (blame Ubuntu, it's their installer).

**Comment by jondo** [comment]
@rimvydukas, could you please rename this issue to something more specific, such that this issue can be easier found by other people having the same problem? I suggest "User should not need to decide about GRUB configuration details". Point is that users don't have any of the background information @gm10 gave in the last comment.

As a remedy, the release notes should state what to do in case of this warning. Well, at least it's documented here now.

**Comment by gm10** [comment]
"User should not need to decide about GRUB configuration details" -- we don't control what the GRUB package does and while we could control to just overwrite your configuration that's not a good solution. Many users (myself included) have modified their configuration and actually need to decide what to do in such a situation. So we're not gonna change that behaviour.

Also my understanding is that if you install LM19 with Internet connection then the GRUB update at issue here will be downloaded and applied during the installation and the question never comes up.

**Comment by jondo** [comment]
OK, I understand that configuration changes by the user should not be overwritten. I think the improvable case is the one where the user has never manually changed the configuration. For this case, I still think a release notes entry would be useful. @rimvydukas, do you agree? If yes, please suggest the text of such an entry.
