### ISSUE TITLE
Kernel recommendations

### ISSUE THREAD

**Issue by gm10** [linuxmint/mintupdate#440]
mintupdate may want to check:
- if a supported higher version HWE meta-package is available when the LTS meta-package is installed 
  - implement like mirror and timeshift warning, once and then never again with option to add to updates right away 
  - level 4 filter override?
- if a supported kernel higher than the current meta gets installed
  - check if version matches HWE meta-package version and offer to install if not present, warning that it won't be kept up to date otherwise
    - level 4 filter override?
  - otherwise always pop up warning that it won't be kept up to date (checkbox to not show warning again)?

special case:
- if a supported kernel higher than any available meta package is installed:
  - suggest to downgrade (e.g. case of 4.15.0-24 getting revoked)?

@clefebvre some note keeping and further brainstorming on what we discussed, feel free to add

**Comment by Pjotr123** [comment]
Like you, I'm of the opinion that if your system is already running well on the LTS kernel, there's no need to board the HWE rollercoaster. So no notifications are needed then about a newer HWE kernel being available. In my opinion, such a notification would only be confusing and might lead to undesirable behaviour....

**Comment by gm10** [comment]
Maybe not about the availability (I share your concerns) but the HWE meta package should be suggested if a manually installed HWE kernel is detected.
