### ISSUE TITLE
Linux Mint 19.1 - Non-installed upstream kernels is showing as "Unsupported"

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintupdate#447]
Hi,

Non-installed upstream kernels is showing as "Unsupported".

![lm-19-mintupdate-kernelwindow](https://user-images.githubusercontent.com/1300133/50281329-2d022e80-0460-11e9-9940-5f8aeeb88ecb.png)

**Comment by gm10** [comment]
Working as intended. Only released kernels get tech support from Ubuntu. The -43 version is a pre-release kernel that you would only see if you added the -proposed pocket. It may fail certification and never get released. Should it get released it will be shown as supported.

**Comment by kelebek333** [comment]
Proposed repo not added my lists. 4.15.0-43 upstream from bionic-updates or bionic-security. 

```
apt-cache policy linux-headers-4.15.0-43
linux-headers-4.15.0-43:
  Installed: (none)
  Candidate: 4.15.0-43.46
  Version table:
     4.15.0-43.46 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages
```

**Comment by gm10** [comment]
Oh, that's interesting, I guess their website is lagging behind, it's still listing -42 as the latest and I had checked only there: https://packages.ubuntu.com/bionic-updates/linux-generic

In that case that means Ubuntu made a packaging mistake and didn't follow their own release procedure. They only tagged the meta package as supported but not the kernel itself:

`apt show linux-generic|grep Supported`
`apt show linux-image-4.15.0-43-generic|grep Supported`

The HWE kernel meta package isn't tagged, either, nor the actual kernel packages:
`apt show linux-generic-hwe-18.04|grep Supported`

There's unfortunately nothing my code can do to mitigate Ubuntu's mistake here. If this isn't a one-off but they'll stop tagging them in the future as well I'd even have to remove the feature again to avoid confusion. Fingers crossed.

**Comment by kelebek333** [comment]
Hi @gm10 ,

Problem partially solved. I think, kernel packages fixed by its maintainer.

```
apt show linux-image-4.15.0-43-generic|grep Supported
Supported: 5y
```

![lm-19-mintupdate-kernelwindow-fixed-1](https://user-images.githubusercontent.com/1300133/50289162-10bebb80-0479-11e9-83cb-5c938f2283ea.png)

```
apt show linux-image-4.18.0-13-generic|grep Supported
Supported: 5y
```
4.18 showing 5y supported, but kernels tool showing "Supported Until August 2019"

![lm-19-mintupdate-kernelwindow-fixed2](https://user-images.githubusercontent.com/1300133/50289165-12887f00-0479-11e9-976d-8391cd7a6220.png)

**Comment by gm10** [comment]
Excellent, thanks for the follow-up, at least they're moving fast at Ubuntu. 

> 4.18 showing 5y supported, but kernels tool showing "Supported Until August 2019"

Despite what Ubuntu's tag says, that one is a HWE kernel from the 18.10 release and only gets 6 months of support in the 18.04 LTS release. Since it's released early you get a bit more. See 
https://wiki.ubuntu.com/Kernel/Support#A18.04.x_Ubuntu_Kernel_Support

So this is definitely working as intended. The majority of my code was about getting that bit to work, because, as you can see, the tag is of no help at all, and these things don't get released on schedule, so I'm actually very happy to see my code works perfectly.
