### ISSUE TITLE
Mintupdate 5.4.7 Wrong Size of Kernel Update

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintupdate#465]
Hi,

Mintupdate 5.4.7  is showing wrong Kernel update's size . Packages of linux-headers, linux-headers-generic, linux-image-generic, linux-modules-generic, linux-modules-extra-generic not listed, therefore the size is not shown.

![mintupdate-wrong-size-kernel](https://user-images.githubusercontent.com/1300133/52053230-d9f4be80-2569-11e9-9673-cf75b37bb78d.png)

**Comment by gm10** [comment]
This isn't kernel specific, this will happen for any package that results in the installation of additional packages (the popup you get to confirm).

**Comment by kelebek333** [comment]
Hi @gm10 ,

I am aware that the meta package triggers other packages. But in this case, size of packages to be loaded is shown incorrectly. I think, users should be able to see the actual size of the kernel update. Showing 6 kb size in update manager right now, but the size of the packages to be loaded with the trigger is much larger than this.

**Comment by gm10** [comment]
Why did you close this (and a few others)? Hope you didn't misunderstand me, I said it was a valid issue report...
