### ISSUE TITLE
Auto-fix DPKG issues instead of reporting an error (#22 22 Jan 2014 - Closed) ?

### ISSUE THREAD

**Issue by arclite7** [linuxmint/mintupdate#470]
Mintupdate 5.4.7; 2019-02-11 Preparation before update from 19v0 to 19v1 LTS

Same issue being reported with apparent error but as described, unnecessary?
Surely the inconvenience and the delay of 4 years in responding to this issue will automatically ramp the prioritisation before marketplace motivation to generally criticise the product against its competition?

E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
E: _cache->open() failed, please report.

**Comment by arclite7** [comment]
Honestly, I could be doing something else, like successfully updating my laptop to do essential and time-sensitive work? Thank you.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintupdate/issues/22

**Comment by arclite7** [comment]
Your response is both arrogant and ignorant, my reference to #22 was already present. If your OCD preference to press the button to close before either reading or respecting the dignity of another human being who has bothered to read the comments of #22 4+ years prior where no action has been taken to rectify the issue following your own cryptic comment of APT preference leaving the error to suggest forwarding a report, then perhaps you should request peer comment before being allowed to proceed. You appear disrespectful by wasting other people's time and by jeopardizing the integrity of all other contributors.
