### ISSUE TITLE
Replace configuration file dialog box is too small.

### ISSUE THREAD

**Issue by HoracioDos** [linuxmint/mintupdate#471]
Hello!
Many times when a package is updated and a configuration file needs be replaced or kept a dialog box appears. This box is too small to check any difference between files and it should be bigger.
Thanks in advance
![image](https://user-images.githubusercontent.com/4549674/52800437-80f15400-305a-11e9-9710-4cb3ea2c8a5e.png)

**Comment by HoracioDos** [comment]
I've realized that this issue may belong to synaptic. If that's the case, it can be closed.
Thanks

**Comment by gm10** [comment]
It does ultimately belong to synaptic but it's still something that should ideally be addressed since synaptic is being used by mintupdate (for now). I haven't personally experienced this, what Mint version & edition is this, and is this a HiDPI setup maybe?
