### ISSUE TITLE
Translation Error On Lanchpad (Related mintUpdate.py:1808 )

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintupdate#495]
Hi,

For translation below,

```
This update affects the following package on your system:
This update affects the following %d packages on your system:
```
I get this error on launchpad.

`number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match `

![mintupdate-tranlation-error](https://user-images.githubusercontent.com/1300133/54476234-e2e4db00-480b-11e9-8cb7-1686dec2eb12.png)

You can review the following translations that are incorrectly translated to prevent this error.

https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/ca/184/+translate
https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/es/184/+translate
https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/hr/184/+translate

**Comment by gm10** [comment]
Thanks, will be fixed by #494.
