### ISSUE TITLE
System snapshot started rsync dry run reads every file of every mount point, WHY !

### ISSUE THREAD

**Issue by jonshouse1** [linuxmint/mintupdate#511]
**Describe the bug**
My system has 8 NFS volumes mounted, why does snapshot try and read them all !

**Screenshots**
If applicable, add screenshots to help explain your problem, you can just drag & drop them here.

**To Reproduce**
mkdir /nfs
mkdir /nfs/volume1
mkdir /nfs/volume2
mkdir /nfs/volume3
through to volume8

mount all 8, now have 32TB mounted 80% used, start mintupdate, edit, system snapshots

**Expected behavior**
Read directories that contain the system only, exlcude nfs, smb etc unless root is nfs. OR just use paths that are the actual operating system !

**Distribution:**
Linux Mint 19 XFCE

**Software version:**
5.4.7

**Comment by gm10** [comment]
`timeshift` only automatically excludes mount points in the standard mount locations (/mnt and /media). For non-standard mounts you must add appropriate filters yourself.

**Comment by jonshouse1** [comment]
> you must add appropriate filters yourself.

Why !

Your code should exclude mount points that are network volumes, if that does not include /

All the info needed is in in /proc,   as displayed by df -h.  

It is daft to assume the user should take an extra step to make the behaviour of your code acceptable.

**Comment by gm10** [comment]
You cannot just exclude all network mounts. What if a system folder is mounted from a network location? You'd still want to restore the data in it. But I agree insofar as timeshift still has a long way to go, the wizard should at least ask for such mount points. 

For now timeshift is an upstream project though: https://github.com/teejee2008/timeshift

**Comment by jonshouse1** [comment]
> You cannot just exclude all network mounts. What if a system folder is mounted from a network location?
As I said, it is simple enough to test if "/" is network mounted.

> You'd still want to restore the data in it.
Some confusion here.
To me the "source" is the "system" you are trying to snapshot. I think it is sensible that any location can be used to as the destination, but the source should exclude anything network mounted ? I don't see why this would be an issue.  

> But I agree insofar as timeshift still has a long way to go, the wizard should at least ask for such mount points.

To me if you are snapshoting a system then the system should be the O/S ... does apt not know the O/S paths, or mintupdate itself..... either the source should be "The Operating System"  or "The operating system + HOME" ... but it should never be "all mounted volumes" as this is simply retarded.

**Comment by gm10** [comment]
> To me the "source" is the "system" you are trying to snapshot. I think it is sensible that any location can be used to as the destination, but the source should exclude anything network mounted ? I don't see why this would be an issue.

Except there is no such thing as "the system". Your network mount can contain vital parts of the operating system. You cannot just ignore them because they're on a different file system. Your application A could have created path /B and you could have mounted that from a networked location C. You cannot rely on the package management system here because it's not the only way to install software to your system.

That's why this cannot just be fully automated. But nevertheless the user should be notified about the possible problem because you're not the first and won't be the last making the mistake.

**Comment by jonshouse1** [comment]
>  last making the mistake.
Yes yes, I get the feeling you did not really listen hard here.  

I know the theory and the reality, I was booting Sun workstations with NFS root 20 years ago, i've developed many embedded device including a number of PXE boot/NFS root devices.

The reality is that the user installs the distro, the distro copies files into /etc /var /bin /usr /sbin /var and a few others, if you include this list plus /home then you capture everything for 99% of users.   If users are advanced enough, and have changed from those DEFAULTS enough to install applications outside of those paths then THOSE users should have to do "extra crap" to snapshot the system.

For the majority of users simply excluding network volumes for the SOURCE to any rsync is sensible, far more sensilbe than the current behaviour that simply attempts to snapshot every volume in the data centre if that happens to be mounted.

The default should be rsync "/" excluding network mounted volumes with an option to exit or work around  if "/" itself is network mounted, not difficult, sensible....

**Comment by gm10** [comment]
Advanced users can be expected to look through the settings at least... but anyway, please take it up with the app's author, I linked it to you above.
