### ISSUE TITLE
Automatic updates do not respect schedule

### ISSUE THREAD

**Issue by mjsulik** [linuxmint/mintupdate#542]
Mint 19.1 
Cinnamon 4.0.10
Kernel 4.18.0.17-generic
MintUpdate 5.4.7

mintUpdate checks for updates shortly after system startup even though I set the initial update check and follow-up update check to a longer period. 
![Screenshot from 2019-04-10 05-45-17](https://user-images.githubusercontent.com/8450514/55879958-9b284980-5b54-11e9-9bdd-eb1195c94a42.png)

**Comment by clefebvre** [comment]
Fixed in master.
