### ISSUE TITLE
Mint Update Settings > Level selection > Doesn't work

### ISSUE THREAD

**Issue by Andrew9x** [linuxmint/mintupdate#547]
The autoselect filter by level does not work as it should.

![updatemanager](https://user-images.githubusercontent.com/42618917/57969167-4b6b4800-7974-11e9-833a-917685e41268.png)

**Expected behavior**
Only updates with level 4 should be selected, based on my settings.

**Distribution:**
- Linux Mint 19

**Software version:**
5.4.7

**Comment by maddypie** [comment]
@Andrew9x I know I'm kinda late, but is this bug resolved yet? Please let me know.

**Comment by Andrew9x** [comment]
Hi!
I no longer use mint so I can't confirm it.

**Comment by xenopeek** [comment]
mintupdate no longer uses the level system in current versions.
