### ISSUE TITLE
apt get: too many errors. (gconf2)

### ISSUE THREAD

**Issue by two-dogs** [linuxmint/mintupdate#552]
* Cinnamon version (linuxmint 19.1 cinnamon 64bit)
   
**Issue**
saw same errors shown on the forum posts provided

https://forums.linuxmint.com/viewtopic.php?f=90&t=296589#p1649754
https://forums.linuxmint.com/viewtopic.php?f=46&t=296232

**Steps to reproduce**

install linuxmint-cinnamon-64bit 19.1 and ran on virtual (qemu)

**Expected behaviour**

error free upgrade

**Other information**
many more people describing exact same issue via irc linuxmint-help

**Comment by two-dogs** [comment]
duplicate closed, wrong directorate, 
https://github.com/linuxmint/cinnamon/issues/8660

**Comment by zcot** [comment]
This is a bad state right now for fresh install. After the initial install, the first massive update leaves the system in a broken package situation.

a good sum is here from karlchen which also includes links from topics above: https://forums.linuxmint.com/viewtopic.php?f=46&t=296373

solution output as seen from one of the forum thread sections:
```
robinia@robinia-Thinkpad-X220:~$ sudo dpkg --configure -a
dpkg: dependency problems prevent configuration of libwebkit2gtk-4.0-37:amd64:
 libwebkit2gtk-4.0-37:amd64 depends on libjavascriptcoregtk-4.0-18 (= 2.24.2-0ubuntu0.18.04.1); however:
  Version of libjavascriptcoregtk-4.0-18:amd64 on system is 2.22.4-0ubuntu0.18.04.1.

dpkg: error processing package libwebkit2gtk-4.0-37:amd64 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libwebkit2gtk-4.0-37:amd64
robinia@robinia-Thinkpad-X220:~$
robinia@robinia-Thinkpad-X220:~$ sudo apt-get install -f
Reading package lists... Done
Building dependency tree      
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libjavascriptcoregtk-4.0-18
The following packages will be upgraded:
  libjavascriptcoregtk-4.0-18
1 to upgrade, 0 to newly install, 0 to remove and 270 not to upgrade.
1 not fully installed or removed.
Need to get 0 B/4,766 kB of archives.
After this operation, 1,450 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 249700 files and directories currently installed.)
Preparing to unpack .../libjavascriptcoregtk-4.0-18_2.24.2-0ubuntu0.18.04.1_amd64.deb ...
Unpacking libjavascriptcoregtk-4.0-18:amd64 (2.24.2-0ubuntu0.18.04.1) over (2.22.4-0ubuntu0.18.04.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up libjavascriptcoregtk-4.0-18:amd64 (2.24.2-0ubuntu0.18.04.1) ...
Setting up libwebkit2gtk-4.0-37:amd64 (2.24.2-0ubuntu0.18.04.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
robinia@robinia-Thinkpad-X220:~$ sudo dpkg --configure -a
robinia@robinia-Thinkpad-X220:~$
```


Depending on how the user initiates the first upgrade(gui or terminal) or what error report they are initially encountering and bring to the forum or IRC, it shows a different looking view of the source of the issue.
```
Errors were encountered while processing:
 libwebkit2gtk-4.0-37:amd64
```
```
dpkg: error processing package gconf2 (--configure):
 dependency problems - leaving triggers unprocessed
dpkg: too many errors, stopping
Errors were encountered while processing:
 gconf2
 gconf2
 gconf2
...
...
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

It seems to be clear to hang up around:
libjavascriptcoregtk-4.0-18
libwebkit2gtk-4.0-37

so, maybe the order? no clue. but javascriptcore doesn't rely on webkit but it does the other way around.

after the fact, it seems `sudo apt-get install -f` does a fine fix.

```
zcot@zcot-MS-7309:~$ apt depends libwebkit2gtk-4.0-37
libwebkit2gtk-4.0-37
  Depends: libjavascriptcoregtk-4.0-18
  Depends: libatk1.0-0
  Depends: libc6
  Depends: libcairo2
  Depends: libegl1
  Depends: libenchant1c2a
  Depends: libfontconfig1
  Depends: libfreetype6
  Depends: libgcc1
  Depends: libgcrypt20
  Depends: libgdk-pixbuf2.0-0
  Depends: libgl1
  Depends: libglib2.0-0
  Depends: libgstreamer-gl1.0-0
  Depends: libgstreamer-plugins-base1.0-0
  Depends: libgstreamer1.0-0
  Depends: libgtk-3-0
  Depends: libharfbuzz-icu0
  Depends: libharfbuzz0b
  Depends: libhyphen0
  Depends: libicu60
  Depends: libjpeg8
  Depends: libnotify4
  Depends: libpango-1.0-0
  Depends: libpng16-16
  Depends: libsecret-1-0
  Depends: libsoup2.4-1
  Depends: libsqlite3-0
  Depends: libstdc++6
  Depends: libtasn1-6
  Depends: libwayland-client0
 |Depends: libwayland-egl1-mesa
  Depends: libwayland-egl1
  Depends: libwayland-server0
  Depends: libwebp6
  Depends: libwebpdemux2
  Depends: libwoff1
  Depends: libx11-6
  Depends: libxcomposite1
  Depends: libxdamage1
  Depends: libxml2
  Depends: libxslt1.1
  Depends: zlib1g
  Recommends: gstreamer1.0-plugins-good
 |Recommends: gstreamer1.0-pulseaudio
  Recommends: gstreamer1.0-alsa
  Recommends: gstreamer1.0-gl
  Recommends: libgl1-mesa-dri
  Suggests: libwebkit2gtk-4.0-37-gtk2

```

**Comment by monsta** [comment]
This is tracked upstream at https://bugs.launchpad.net/bugs/1551623

**Comment by rubinlinux** [comment]
You can work around this using aptitude for now.  Run aptitude as root, 'e' to evaluate, 'g' to go, hit OK, 'g' to go again. You may get an error but apt upgrade will work afterwards without errors

**Comment by zcot** [comment]
Additionally, you can simply clear the error, then use update manager again to "Apply Updates", I'm talking about using the GUI, don't go searching or fixing, -the update manager will take care of it automatically on the next pass. Or if you have to use terminal then: `sudo apt-get install -f` then proceed with update(upgrade) again.

**Comment by two-dogs** [comment]
@zcot , agreed, i followed steps, 1. use update manager , that updated/added two mint related packages, 2. on second pass update manager had lots of packages wanting update, i did so and found error at process completion, 3. i executed `sudo aptitude upgrade` and aptitude completed with correcting error and finishing upgrade, step 2. leaves system partially upgraded, re-running update manager should be akin to the aptitude upgrade step, and as @zcot says, the process should not need to get overly complicated.

**Comment by two-dogs** [comment]
Linuxmint-19.2 cinnamon 64bit (beta) does not show issue described above, i'll call that fixed.
