### ISSUE TITLE
Show changelog from PPA packages

### ISSUE THREAD

**Issue by darealshinji** [linuxmint/mintupdate#56]
I'd be nice if mintUpdate would somehow be able to download the changelog from PPA packages too.

**Comment by TheDevKing** [comment]
I'd love to see this attempted, even if there isn't a 100% reliable way to get a changelog. In the event a changelog is not found it could just default to the "Changelog not found" message. Sometimes is better than never, no?

**Comment by brennanhm** [comment]
Hi guys,

I was looking for a way to contribute to the Linux Mint codebase and after asking on IRC where to begin, I decided to start working on this issue. The new code checks whether or not the change information was successfully fetched from the official sources. If not, it attempts to extract the latest change record from Launchpad's site. So far I've tested it successfully on four different PPAs. I'm relatively new to Python, but eager to learn and open to feedback :)

**Comment by brennanhm** [comment]
I tried using two different methods to get the PPA owner and name, which are required to build the Launchpad URL. The first method, which is commented out, would throw an exception (during the apt-cache command) if the package hadn't been installed. The second method works even if the package hasn't been installed.

**Comment by brennanhm** [comment]
Hi,
The coded solution for this feature request was merged on April 19th, so can it be closed now?
https://github.com/linuxmint/mintupdate/pull/128/files

**Comment by monsta** [comment]
Yes, and thanks for this feature :smile:

**Comment by brennanhm** [comment]
No problem! :)
