### ISSUE TITLE
Update Romanian language for mintupdate

### ISSUE THREAD

**Issue by DorianB2017** [linuxmint/mintupdate#562]
Hi Clem!
Please update the Romanian language for mintupdate in Linux Mint 19.2, taking the update data from here: https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/ro/+translate.
There were many sentences/phrases/words/areas not translated in Romanian language. Now, I completely translated into Romanian language.
Thank you.

**Comment by DorianB2017** [comment]
I would like, however, to be implemented my translations from here: https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/ro/+translate, in mintupdate ver. 5.5.4.1.
Thank you for understanding.

**Comment by clefebvre** [comment]
This isn't possible as we'd have no way of making sure translations apply to the past branch. We will however update all translations for newer versions (5.5.6+).
