### ISSUE TITLE
Update manager icon not displayed in LM 19.2 after system start

### ISSUE THREAD

**Issue by lessharm** [linuxmint/mintupdate#563]
**Describe the bug**
After the upgrade vom LM 19.1 to LM 19.2 Cinnamon the update manager icon doesn't appear in the panel after system start is ready. This is reported in both the german and the main forum. For me the workaround is to restart Cinnamon in the panel and immediately the icon apears.

**To Reproduce**
1. Normal system start

**Expected behavior**
With delay of 20 s the icon should appear

**Distribution:**
- [ ] Linux Mint

**Software version:**
5.5.4

**Logs:**
08.17@11:44 ++ Launching Update Manager
08.17@11:44 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 10 minute(s)
08.17@11:44 ++ Starting refresh (local only)
08.17@11:44 ++ System is up to date
08.17@11:44 ++ Refresh finished
08.17@11:54 ++ Update Manager is in tray mode, performing initial refresh
08.17@11:54 ++ Starting refresh (retrieving lists of updates from remote servers)
08.17@11:54 ++ System is up to date
08.17@11:54 ++ Refresh finished
08.17@11:54 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)

**Crash report:**

**Additional context**

**Locale:**

**Comment by jakoblm** [comment]
I can confirm the behavior described above. It does not happen to me after every system start, but very often. Sometimes the icon even appears, but it's only half visible. The workaround for me is also to restart Cinnamon.

**Comment by DorianB2017** [comment]
I confirm this bug, too. The Update Manager icon does not appear on the systray after the system is started.

**Comment by clefebvre** [comment]
This is tracked at https://github.com/linuxmint/cinnamon/issues/8771.
