### ISSUE TITLE
A more recent version of cups

### ISSUE THREAD

**Issue by lessharm** [linuxmint/mintupdate#564]
**Is your feature request related to a problem? Please describe.**
I've read in the linuxmint forum, that there there is a known issue with cups 2.2.7 and chromium-based browser. The cups version 2.2.7 is the default one of LM 19.x. For example, if you want to add a new printer via http://localhost:631/, the authentification window doesn't appear and so you can't use this function. I can reproduce this with the chromium webbrowser and Vivaldi. But it should work with version 2.2.8 or 2.2.10. 

**Describe the solution you'd like**
Is it possible for linuxmint to make an official update for cups? Maybe there is also a recommended way to update it otherwise without getting in trouble with the system?

**Describe alternatives you've considered**
With firefox it works with cups 2.2.7.

**Comment by clefebvre** [comment]
Not related to mintupdate.
