### ISSUE TITLE
Mintupdate doesn't auto-update 5.0 kernel anymore

### ISSUE THREAD

**Issue by momo42** [linuxmint/mintupdate#569]
Under Linux Mint 19.1 I switched from kernel 4.15 to 5.0 via mintupdate. After rebooting with 5.0 and removing _all_ the old 4.15 kernels, mintupdate started auto-updating the 5.0 kernels without problems. Every time I checked the kernel window to remove old kernels the newest 5.0 and some older ones were installed. Everything fine.

After update to Mint 19.2 some weeks ago I noticed (on four different machines with 5.0 kernel and auto-update activated) that this mechanism stopped working.

It seems that while auto-update itself is working well no kernel updates are applied anymore.
So I checked the preferences and noticed that while auto-updates were working both sliders on the new Automation tab were deactivated (on all four machines). So I activated them and waited some weeks but no kernel updates got applied. Automatically removing old kernels works but new 5.0 kernels (or others) are not installed unless you do it manually.

OS: Mint 19.2
mintupdate 5.5.4

I have no idea what further information would be helpful. So please let me know and I will provide them.

**Comment by kelebek333** [comment]
You can try to install linux-generic-hwe-18.04 package with following command.

`sudo apt-get install --install-recommends linux-generic-hwe-18.04`

**Comment by kelebek333** [comment]
Did you try to install linux-generic-hwe-18.04 package with following command.

`sudo apt-get install --install-recommends linux-generic-hwe-18.04`

**Comment by momo42** [comment]
Thanks for your help.

I checked Synaptic and found out that `linux-generic-hwe-18.04-edge` (5.0.0.23.79) is installed. If I remember correctly that package got auto-installed right after removing the last 4.15 Kernel with Mint 19.1 mintupdate. `linux-generic-hwe-18.04` (without -edge) seems to contain the recent kernel.

It's a nasty trap. Any user who switched to the 5.0 kernel under Mint 19.1 and received frequent updates is now stuck on an old unpatched kernel until he notices the problem.

Also an Mint 19.1 -> 19.2 update issue but in my opinion this should be fixed as it jeopardizes the safety of users in the long term.

**Comment by momo42** [comment]
Ok, I had installed kernel 5.0.0-23 (last auto-updated kernel) and 5.0.0-25 (manually installed due to auto-update not working anymore).
I now clicked on "Remove kernels" and immediately after removing 5.0.0-23 mintupdate offered the new 5.0.0-27 kernel to me as update and some message that new packages has to be installed (the same procedure like done when switching from 4.15 to 5.0 half a year ago)
I installed all updates and after that went to Synaptics.
`linux-generic-hwe-18.04-edge` is gone and instead `linux-generic-hwe-18.04` is installed now.

Seems to be fixed for me but still not a good solution as many users won't notice that they have (again) to remove a kernel by hand to get further updates ...

**Comment by donnisnoni95** [comment]
i have same issue here

**Comment by gm10** [comment]
The problem is Ubuntu forgetting to update the `linux-generic-hwe-18.04-edge` meta-package:
```
$ apt list linux-generic-hwe-18.04*
Listing... Done
linux-generic-hwe-18.04/bionic-updates,bionic-security 5.0.0.27.84 amd64
linux-generic-hwe-18.04-edge/bionic-updates 5.0.0.23.79 amd64
```
