### ISSUE TITLE
Could You Add "Show Changelog" Mintupdate's Updates

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintupdate#571]
Hi,

Could you add "Show Changelog" description/section to Mintupdate's updates.

![update-manager-changelog-1](https://user-images.githubusercontent.com/1300133/64430418-ebceaf00-d0c0-11e9-8459-3ebce405b188.png)

**Comment by clefebvre** [comment]
This was discussed in the past. I'm not sure it's relevant since it's a mandatory update.
