### ISSUE TITLE
Automatic Upgrade fails every time

### ISSUE THREAD

**Issue by Vicat28** [linuxmint/mintupdate#575]
**Describe the bug**
Update Manager cannot install the updates automatically, some errors are listed in /var/log/mintupdate.log.

**Expected behavior**
Updates should be installed automatically on a daily basis as the option in Update Manager settings says.

**Distribution:**
Linux Mint 19.2 Tina Cinnamon

**Software version:**
mintupdate 5.5.4.1

**Logs:**
/var/log/mintupdate.log:

> -- Automatic Upgrade starting Wed 25 Sep 2019 09:05:07 CEST:
> Traceback (most recent call last):
>   File "/usr/bin/mint-refresh-cache", line 16, in <module>
>     cache.update()
>   File "/usr/lib/python3/dist-packages/apt/cache.py", line 561, in update
>     raise FetchFailedException()
> apt.cache.FetchFailedException
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
>     os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_mint-refresh-cache.0.crash'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/bin/mint-refresh-cache", line 16, in <module>
>     cache.update()
>   File "/usr/lib/python3/dist-packages/apt/cache.py", line 561, in update
>     raise FetchFailedException()
> apt.cache.FetchFailedException
> E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
> -- Automatic Upgrade completed

**Comment by clefebvre** [comment]
Are you able to refresh the cache manually?

`sudo apt update`

What happens when you run this?

`sudo /usr/bin/mint-refresh-cache`

**Comment by Vicat28** [comment]
Yes, I can refresh the cache manually without any problems (both from command line and using the Refresh button in Update Manager)
Running `sudo /usr/bin/mint-refresh-cache` does not give any output, so I guess it is executed without errors.

**Comment by clefebvre** [comment]
And is the problem still occurring?

**Comment by Vicat28** [comment]
Yes, but today the error was a bit different - it failed to download the packages (but I am able to download and install them manually).

/var/log/mintupdate.log:

> -- Automatic Upgrade starting Thu 26 Sep 2019 06:59:06 CEST:
> Traceback (most recent call last):
>   File "/usr/bin/mint-refresh-cache", line 16, in <module>
>     cache.update()
>   File "/usr/lib/python3/dist-packages/apt/cache.py", line 561, in update
>     raise FetchFailedException()
> apt.cache.FetchFailedException
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
>     os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_mint-refresh-cache.0.crash'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/bin/mint-refresh-cache", line 16, in <module>
>     cache.update()
>   File "/usr/lib/python3/dist-packages/apt/cache.py", line 561, in update
>     raise FetchFailedException()
> apt.cache.FetchFailedException
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Suggested packages:
>   arj lha lzip lzop ncompress rpm2cpio rzip sharutils unace unalz unar zoo
>   fonts-lyx
> Recommended packages:
>   xul-ext-ubufox
> The following packages will be upgraded:
>   file-roller firefox firefox-locale-en firefox-locale-pl
> 4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Need to get 52,1 MB of archives.
> After this operation, 14,3 kB of additional disk space will be used.
> Err:1 http://packages.linuxmint.com tina/upstream amd64 firefox amd64 69.0.1+linuxmint1+tina
>   Could not resolve 'packages.linuxmint.com'
> Err:2 http://packages.linuxmint.com tina/upstream amd64 firefox-locale-en amd64 69.0.1+linuxmint1+tina
>   Could not resolve 'packages.linuxmint.com'
> Ign:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 file-roller amd64 3.28.0-1ubuntu1.1
> Err:4 http://packages.linuxmint.com tina/upstream amd64 firefox-locale-pl amd64 69.0.1+linuxmint1+tina
>   Could not resolve 'packages.linuxmint.com'
> Err:3 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 file-roller amd64 3.28.0-1ubuntu1.1
>   Could not resolve 'archive.ubuntu.com'
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/f/file-roller/file-roller_3.28.0-1ubuntu1.1_amd64.deb  Could not resolve 'archive.ubuntu.com'
> E: Failed to fetch http://packages.linuxmint.com/pool/upstream/f/firefox/firefox_69.0.1+linuxmint1+tina_amd64.deb  Could not resolve 'packages.linuxmint.com'
> E: Failed to fetch http://packages.linuxmint.com/pool/upstream/f/firefox/firefox-locale-en_69.0.1+linuxmint1+tina_amd64.deb  Could not resolve 'packages.linuxmint.com'
> E: Failed to fetch http://packages.linuxmint.com/pool/upstream/f/firefox/firefox-locale-pl_69.0.1+linuxmint1+tina_amd64.deb  Could not resolve 'packages.linuxmint.com'
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> -- Automatic Upgrade completed

**Comment by clefebvre** [comment]
That looks like a temporary failure to route or resolve DNS, networking issue.

**Comment by Vicat28** [comment]
I think I fixed it by reinstalling the python-apt package - running `sudo /usr/lib/linuxmint/mintUpdate/automatic_upgrades.py` installs the updates now and no errors are listed in the log file.
I will wait until the next automatic upgrade and close the issue if it works.
