### ISSUE TITLE
mintmenu update offered in Cinnamon

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#578]
Linux Mint 19.2 **Cinnamon** 64-bit - clean installation, no other desktop environment installed, single OS on this PC

mintmenu - described as "Advanced **MATE** menu" - is offered as an update. Why?

**Comment by Xmetalfanx** [comment]
I will let someeone from the team comment on this but IF it's only for Mate and not suppose to be there on a Cinnamon install (they say just forgot to remove it from the Cinnamon ISO/install) it should be ok to just remove that package and then you will not see it again in updates.

Though I'd wait for someone from the team to comment ... just in CASE it does tie into Cinnamon somehow and they just didn't update the description for example

**Comment by mtwebster** [comment]
On Mint, the mate panel is used as a fallback environment if cinnamon crashes.  That menu applet is the primary menu used there (as well as in Mint's Mate edition).  It's not strictly necessary, and you should have no ill effects if you uninstall it, other than, if you crash and fall back to Mate, you won't have a menu (though it'd be easy to add one to the panel - there are alternatives).

On the other hand, removing it won't stop you potentially getting other updates (like mate-panel or metacity - the window manager used there).

**Comment by kneekoo** [comment]
Thanks for the clarification. :)
