### ISSUE TITLE
Show recently updated

### ISSUE THREAD

**Issue by AndreiMiculita** [linuxmint/mintupdate#579]
Hello,

Quite often I find that after performing an update, I would like to know what programs were updated. However, all I can see is the big tick with "Your system is up to date" below it.

I'd like it if I could see a list of recently updated software. Either what was updated the last time I pressed the "install updates" button, or all the software that was updated in the past, say, 24h. This list could be below the "description" section.

This is an idea I got from the Google Play Store on Android. In the Google Play Store, after you update a bunch of apps, they are moved to a list below the outdated apps. You can open them to see the update, which is, at least to me, very useful.

**Comment by clefebvre** [comment]
View -> History of Updates.
