### ISSUE TITLE
The loading spinner renders incorrectly with vsync turned off.

### ISSUE THREAD

**Issue by JustinSpedding** [linuxmint/mintupdate#580]
**Describe the bug**
I use nvidia drivers with vsync turned off for gaming performance reasons. When I open the mint update and and check for updated, the loading spinner rendered fast, as in at least several hundred frames per second. It should have the smooth animation that I would see if vsync were turned on. Instead, it looks like a glitchy half-transparent circle.

**To Reproduce**
1. Turn vsync off via the mint settings or environmental variables
2. Go to the mint update gui
3. Click on the button to check for updates
4. See the spinner render way too fast.

I do not know why, but every once in a while, it does render smoothly with vsync off. This is not often, and I have not yet noticed a pattern to consistently make it do this.

**Expected behavior**
The spinner should look the same regardless of whether vsync is turned on or off.

**Distribution:**
- [x ] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
v5.5.4

**Logs:**
Copy & paste the log output from Update Manager > View > Information here.

**Crash report:**
If you are reporting a crash, please run `mintupdate` from a terminal window, reproduce the crash and copy & paste any output from the terminal window here.

**Additional context**
Add any other context about the problem you think might be relevant.

**Locale:**
If the problem is with text not getting displayed correctly, paste the output of the terminal command `locale`.

**Comment by clefebvre** [comment]
Does that happen with all spinners? There's one also in mintinstall.
