### ISSUE TITLE
Make "select all" button able to "unselect all"

### ISSUE THREAD

**Issue by romseguy** [linuxmint/mintupdate#581]
Very simple request, Make "select all" button able to "unselect all" as well, so we can select one by one which packages we want to update. Thank you!

**Comment by maddypie** [comment]
@romseguy Is your request resolved yet? If not are you referring to the "Synaptic Package Manager"?
Good day!

**Comment by xenopeek** [comment]
The Clear button, to the left of the Select All button, does this.
