### ISSUE TITLE
Update Manager reporting security updates "not installed"

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mintupdate#583]
**Describe the bug**
After I have successfully installed the updates, the update manager reports "security updates could not be installed". I have to "refresh" the list, so the message disappears. All software was installed successfully, but mintupdate does not recognize.

**Screenshots**
![Bildschirmfoto vom 2019-10-30 07-29-54](https://user-images.githubusercontent.com/51761218/67836259-71347580-faec-11e9-8eb1-73c7dbadf5e9.png)

**To Reproduce**
1. Install all updates in the update manager successfully. 
2. Mintupdate reports 'security updates could not be installed'.
2. Click on 'refresh' and wait. 
3. The message dissapears.

**Expected behavior**
I expect, that my software can be updated without this error message.

**Distribution:**
Linux Mint 19.2 Cinnamon

**Software version:**
5.5.4.1

**Logs:**
10.30@07:15 ++ Launching Update Manager
10.30@07:15 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 5 minute(s)
10.30@07:15 ++ Package cache location not found, disabling cache monitoring
10.30@07:15 ++ Starting refresh (local only)
10.30@07:15 ++ System is up to date
10.30@07:15 ++ Refresh finished
10.30@07:20 ++ Update Manager is in tray mode, performing initial refresh
10.30@07:20 ++ Starting refresh (retrieving lists of updates from remote servers)
10.30@07:20 ++ Found 1 software updates
10.30@07:20 ++ Refresh finished
10.30@07:20 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)
10.30@07:28 ++ Starting refresh (retrieving lists of updates from remote servers)
10.30@07:28 ++ Found 1 software updates
10.30@07:28 ++ Refresh finished
10.30@07:28 ++ Install requested by user
10.30@07:28 ++ Will install apport
10.30@07:28 ++ Will install python3-apport
10.30@07:28 ++ Will install python3-problem-report
10.30@07:28 ++ Ready to launch synaptic

(synaptic:3217): Gtk-CRITICAL **: 07:28:54.578: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
10.30@07:29 ++ Return code:0
10.30@07:29 ++ Install finished
10.30@07:29 -- Exception occurred in the install thread: <class 'TypeError'>
10.30@07:29 -- Could not install security updates
10.30@07:30 ++ Starting refresh (retrieving lists of updates from remote servers)
10.30@07:30 ++ System is up to date
10.30@07:30 ++ Refresh finished

**Comment by KHeilen** [comment]
Just would like to confirm jakoblm's bug report.
Precisely the same happened here today on
Linux Mint 19.2 64-bit Cinnamon
MintUpdate 5.5.4.2

Log:
Update Manager => View => Information
(File: /tmp/mintUpdate/mk1c8cv2)
12.07@11:20 ++ Launching Update Manager
12.07@11:20 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 10 minute(s)
12.07@11:20 ++ Package cache location not found, disabling cache monitoring
12.07@11:20 ++ Starting refresh (local only)
12.07@11:20 ++ Found 4 software updates
12.07@11:20 ++ Refresh finished
12.07@11:30 ++ Update Manager is in tray mode, performing initial refresh
12.07@11:30 ++ Starting refresh (retrieving lists of updates from remote servers)
12.07@11:30 ++ Found 5 software updates
12.07@11:30 ++ Refresh finished
12.07@11:30 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)
12.07@11:30 ++ Starting refresh (retrieving lists of updates from remote servers)
12.07@11:30 ++ Found 5 software updates
12.07@11:30 ++ Refresh finished
12.07@11:32 ++ Install requested by user
12.07@11:32 ++ Will install intel-microcode
12.07@11:32 ++ Will install libsqlite3-0:i386
12.07@11:32 ++ Will install libsqlite3-0
12.07@11:32 ++ Will install xul-ext-lightning
12.07@11:32 ++ Will install thunderbird-gnome-support
12.07@11:32 ++ Will install thunderbird-locale-en-us
12.07@11:32 ++ Will install thunderbird
12.07@11:32 ++ Will install thunderbird-locale-de
12.07@11:32 ++ Will install thunderbird-locale-en
12.07@11:32 ++ Will install linux-headers-generic
12.07@11:32 ++ Will install linux-libc-dev
12.07@11:32 ++ Will install linux-image-generic
12.07@11:32 ++ Will install linux-generic
12.07@11:32 ++ Will install grub-common
12.07@11:32 ++ Will install grub2-common
12.07@11:32 ++ Will install grub-pc
12.07@11:32 ++ Will install grub-pc-bin
12.07@11:32 ++ Ready to launch synaptic

(synaptic:5049): Gtk-CRITICAL **: 11:32:52.478: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
12.07@11:39 ++ Return code:0
12.07@11:39 ++ Install finished
12.07@11:39 -- Exception occurred in the install thread: <class 'TypeError'>
12.07@11:39 -- Could not install security updates
12.07@11:52 ++ Starting refresh (retrieving lists of updates from remote servers)
12.07@11:52 ++ System is up to date
12.07@11:52 ++ Refresh finished

In fact the update installation had finished successfully.
apt-get commands and the logfile /var/log/apt/term.log helped confirm so.
Clicking on [Refresh] in Update Manager made the displayed error message go away.
No more new updates found.

Forum report:
https://forums.linuxmint.com/viewtopic.php?f=47&t=306788&p=1724798#p1724775

**Comment by KHeilen** [comment]
It happened again:

12.14@23:23 ++ Launching Update Manager
12.14@23:23 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 10 minute(s)
12.14@23:23 ++ Package cache location not found, disabling cache monitoring
12.14@23:23 ++ Starting refresh (local only)
12.14@23:23 ++ Found 1 software updates
12.14@23:23 ++ Refresh finished
12.14@23:26 ++ Install requested by user
12.14@23:26 ++ Will install libdevmapper1.02.1
12.14@23:26 ++ Will install liblvm2cmd2.02
12.14@23:26 ++ Will install dmsetup
12.14@23:26 ++ Will install libdevmapper-event1.02.1
12.14@23:26 ++ Will install dmeventd
12.14@23:26 ++ Will install lvm2
12.14@23:26 ++ Will install liblvm2app2.2
12.14@23:26 ++ Ready to launch synaptic

(synaptic:2890): Gtk-CRITICAL **: 23:26:46.623: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
12.14@23:28 ++ Return code:0
12.14@23:28 ++ Install finished
12.14@23:28 -- Exception occurred in the install thread: <class 'TypeError'>
12.14@23:28 -- Could not install security updates
12.14@23:28 ++ Starting refresh (retrieving lists of updates from remote servers)
12.14@23:29 ++ System is up to date
12.14@23:29 ++ Refresh finished

Again the update installation had finished successfully, when the false alert got raised.

So far it has happened here twice on Mint 19.2, but in both cases only on Mint 19.2 Cinnamon 64-bit.
The slightly older Mint 19.2 xfce 32-bit system seems unaffected.

**Comment by claudiux** [comment]
This bug is still present in Cinnamon 4.4.8.

**Comment by KHeilen** [comment]
Happened again here today, Mint 19.2 Cinnamon:

02.13@21:24 ++ Launching Update Manager
02.13@21:24 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 10 minute(s)
02.13@21:24 ++ Package cache location not found, disabling cache monitoring
02.13@21:24 ++ Starting refresh (local only)
02.13@21:24 ++ Found 7 software updates
02.13@21:24 ++ Refresh finished
02.13@21:30 ++ Install requested by user
02.13@21:30 ++ Will install firefox-locale-de
02.13@21:30 ++ Will install firefox-locale-en
02.13@21:30 ++ Will install firefox
02.13@21:30 ++ Will install libexif12
02.13@21:30 ++ Will install libexif12:i386
02.13@21:30 ++ Will install libxml2:i386
02.13@21:30 ++ Will install libxml2
02.13@21:30 ++ Will install libqt5test5
02.13@21:30 ++ Will install qt5-gtk-platformtheme
02.13@21:30 ++ Will install libqt5dbus5
02.13@21:30 ++ Will install libqt5sql5-sqlite
02.13@21:30 ++ Will install libqt5widgets5
02.13@21:30 ++ Will install libqt5xml5
02.13@21:30 ++ Will install libqt5printsupport5
02.13@21:30 ++ Will install libqt5gui5
02.13@21:30 ++ Will install libqt5core5a
02.13@21:30 ++ Will install libqt5network5
02.13@21:30 ++ Will install libqt5sql5
02.13@21:30 ++ Will install xul-ext-lightning
02.13@21:30 ++ Will install thunderbird-gnome-support
02.13@21:30 ++ Will install thunderbird-locale-en-us
02.13@21:30 ++ Will install thunderbird
02.13@21:30 ++ Will install thunderbird-locale-de
02.13@21:30 ++ Will install thunderbird-locale-en
02.13@21:30 ++ Will install adobe-flash-properties-gtk
02.13@21:30 ++ Will install adobe-flashplugin
02.13@21:30 ++ Will install softmaker-office-2018
02.13@21:30 ++ Ready to launch synaptic

(synaptic:3401): Gtk-CRITICAL **: 21:30:53.696: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
02.13@21:34 ++ Update Manager window is open, skipping initial refresh
02.13@21:34 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
02.13@21:35 ++ Update Manager window is open, delaying recurring refresh by 60s
02.13@21:36 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
02.13@21:37 ++ Update Manager window is open, delaying recurring refresh by 60s
02.13@21:38 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
02.13@21:39 ++ Update Manager window is open, delaying recurring refresh by 60s
02.13@21:40 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
02.13@21:41 ++ Update Manager window is open, delaying recurring refresh by 60s
02.13@21:42 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
02.13@21:43 ++ Update Manager window is open, delaying recurring refresh by 60s
02.13@21:44 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
02.13@21:45 ++ Update Manager window is open, delaying recurring refresh by 60s
02.13@21:46 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
02.13@21:47 ++ Update Manager window is open, delaying recurring refresh by 60s
02.13@21:48 ++ Return code:0
02.13@21:48 ++ Install finished
02.13@21:48 -- Exception occurred in the install thread: <class 'TypeError'>
02.13@21:48 -- Could not install security updates
02.13@21:48 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
02.13@21:49 ++ Starting refresh (retrieving lists of updates from remote servers)
02.13@21:49 ++ System is up to date
02.13@21:49 ++ Refresh finished
02.13@21:49 ++ Update Manager window is open, delaying recurring refresh by 60s
02.13@21:50 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 58 minute(s)

**Comment by Harry-W-Haines-III** [comment]
Is this bug ever going to be fixed?  It occurs on 4 different computers, so its not hardware related.  It seemed to show up last summer and continues to this day in Mint 19.3, Cinnamon 4.4.8.
"Could not install security updates" is a generic error message.  Is there something wrong with the looping code?

**Comment by sunshinecorp** [comment]
This happens to me regularly since Mint 19.1. It has occured also in Mint 19.2, 19.3 and now in LMDE 4. Updates actually install every time, but it gives the error message 9 times out of 10.

**Comment by claudiux** [comment]
In `/usr/lib/linuxmint/mintUpdate/mintUpdate.py` on my computer, after the `Gdk.threads_leave()` at lines 598 and 606, I added a line `self.application.refresh()`.
I'm waiting for the next security updates to see if that solves the problem...

**Comment by claudiux** [comment]
That seems to be OK. I continue to test...

**Comment by flansuse** [comment]
As of today, with a fully updated 19.3 system, it still randomly happens for me too.

claudix, you are saying a patch is going to be released for mintUpdate?

Currently on 5.5.9.

**Comment by claudiux** [comment]
@flansuse Here is my patch. Save `mintUpdate.py` before applying this patch!
https://github.com/linuxmint/mintupdate/pull/624/files

**Comment by clefebvre** [comment]
Followed at https://github.com/linuxmint/mintupdate/issues/594.
