### ISSUE TITLE
Mintupdate/5.5.7 Missing Dependency

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintupdate#590]
**Describe the bug**
Mintupdate can't run after update to mintupdate/5.5.7

**To Reproduce**
1. Update mintupdate from Daily Build PPA or Tricia repository
2. mintupdate can't restart after upgrade
3. mintupdate can't start anyway
4. mintupdate can working after manually installation of libxapp1 and gir1.2-xapp-1.0

**Distribution:**
- [x ] Linux Mint

**Software version:**
mintupdate 5.5.7

**Crash report:**

```
'gi.repository.XApp' object has no attribute 'StatusIcon'
<class 'AttributeError'>
```

```
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:1114: Warning: cannot retrieve class for invalid (unclassed) type 'void'
  self.icon = XApp.StatusIcon()
could not get a reference to type class
<class 'TypeError'>
```

Hi,

Could you add following packages to dependency of Mintupdate.

libxapp1 
gir1.2-xapp-1.0

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintupdate/commit/3cc4d155640e3024e034555fc716895a0c303f27.
