### ISSUE TITLE
Menus disabled when mintupdate can update itself

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#602]
**Describe the bug**
When mintupdate can update itself, all its menus are disabled, which is mostly unnecessary.

**Expected behavior**
Most of the menu items have no impact on the package management, so they should be enabled. I mean I wanted to check the updates history and I couldn't because I first had to update mintupdate.

**File**
- Close Window _(no impact)_
- Quit _(no impact)_

**Edit**
- Preferences _(no impact)_
- System Snapshots _(no impact)_
- Software Sources _(no impact)_

**View**
- Visible Columns _(no impact)_
- Show Descriptions _(no impact)_
- History of Updates _(no impact)_
- Linux kernels (**impacts APT**)
- Information _(no impact)_

**Help**
- Welcome Screen _(no impact)_
- Keyboard Shortcuts _(no impact)_
- Contents _(no impact)_
- About _(no impact)_

**Distribution:**
[x] Linux Mint
[x] LMDE _(not tested, but I assume it's been ported similarly)_

I consider this a bug, because this feature obstructs access to useful features that have no negative impact if used.

**Software version:**
5.5.8 and older _(I assume 5.5.9 has the same behavior but we'll have to get a newer version to confirm this)_

**Comment by scootergrisen** [comment]
I see the menus are disabled while viewing the welcome screen until i click the OK button which is annoying.
5.6.9
Linux Mint Xfce

**Comment by mtwebster** [comment]
> I see the menus are disabled while viewing the welcome screen until i click the OK button which is annoying.

You only ever see the welcome screen once on a new install, not that big of a deal.

Updating the update manager is quick and there may be a bug in the program itself, so forcing this update is reasonable.
