### ISSUE TITLE
Don't kill already running Update Manager when starting it again from menu

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mintupdate#604]
**Describe the bug**
- I power on the computer.
- I do **nothing** excepted starting the Update Manager (important because this bug doesn't occur everytime if another software is started before).
- I do nothing excepted choosing in the menu "View - Linux kernels" (important because this bug doesn't occur if another menu is choosen before).
-> The update manager crashes and closes.

If I start Update manager again, no more crashes until I restart Linux.

**Expected behavior**
The update manager should show the installed kernels.

**Distribution:**
- [x] Linux Mint

**Software version:**
5.5.9

**Crash report:**
If you are reporting a crash, please run `mintupdate` from a terminal window, reproduce the crash and copy & paste any output from the terminal window here -> no output, only $ that is again waiting a new command.

**Comment by xenopeek** [comment]
I can't managed to reproduce this yet.

Can you make it crash again and afterwards—before restarting Update Manager—look in the /tmp/mintUpdate/ directory and see if there is a file there with current timestamp? If so, can you share what is in the file. If it is a very big and long file, just the last page or so.

**Comment by InfoLibre** [comment]
Just after a crash, there are 2 files.
[mintUpdate.zip](https://github.com/linuxmint/mintupdate/files/4142804/mintUpdate.zip)

**Comment by xenopeek** [comment]
Thanks. Nothing in those files that can help but I figured it out: mintupdate is by default started 20 seconds after logging in (see startup applications in your menu) and to ensure there is only one mintupdate process running, mintupdate kills any already running mintupdate process.

Actually any time you start mintupdate from your menu, it will kill the running mintupdate. One might expect instead for the window of the running mintupdate in the tray to be opened and brought to foreground.

**Comment by clefebvre** [comment]
This is done by design as part of the auto-upgrade of mintupdate.
