### ISSUE TITLE
Cannot activate automatic updates any more

### ISSUE THREAD

**Issue by jondo** [linuxmint/mintupdate#613]
**Describe the bug**
Nearly three weeks ago, automatic updates for unknown reason disabled themselves. (The last one I see in the history of updates is from 2020-03-27.)
Since then, I cannot turn on "Apply updates automatically" any more.

FWIW, the Preferences window shows the banner "Make sure your system snapshots are properly configured before using this option." Timeshift correctly creates automatic snapshots, though.

**Expected behavior**
I should be able to reactivate "Apply updates automatically" again.

**Distribution:**
Linux Mint 19.3 Tricia 64-bit, MATE 1.22.2

**Software version:**
5.5.9

**Additional context**
Available disk space on /: 12 GiB.

**Comment by tkoop** [comment]
I was having the same problem, so I Googled it and landed on this page.  

Please fix this or tell us a work-around.

**Comment by clefebvre** [comment]
What happens exactly? What do you mean by you can't enable them??

**Comment by tkoop** [comment]
I just looked again, and it looks like I can, in fact, enable updates, so I guess never mind then.

**Comment by jondo** [comment]
In the update manager preferences, when I try to move the "Apply updates automatically" slider to the right, it doesn't stay there.
The same happens with the "Remove obsolete kernels and dependencies" slider.

However, I just wondered why there aren't any updates after manual refresh. So I found out that the "history of updates" is full of automatic updates! Very fine, so it's just a broken user interface (which I will re-test after upgrading to LM 20.x.)

_(Note to self: this is on "expanse".)_
