### ISSUE TITLE
mintupdate fails to perform side-by-side comparison of overwritten config files

### ISSUE THREAD

**Issue by VA1DER** [linuxmint/mintupdate#617]
**Describe the bug**
When mintupdate installs a new software version that will overwrite a configuration file which has been manually edited by the user, it offers you a few options to determine whether or not you want to keep the previous version or overwrite with the new version.  One of those options is a side-by-side comparison.  Selecting the side-by-side comparison option does not bring up a side-by-side comparison, it brings up a line-by-line comparison as if you had instead selected the option "show the differences between the versions".

**Screenshots**
![Screenshot at 2020-04-29 09-49-16](https://user-images.githubusercontent.com/6966600/80615835-91e77480-8a16-11ea-9530-3e4409ace773.png)

![Screenshot at 2020-04-29 09-45-50](https://user-images.githubusercontent.com/6966600/80615894-a6c40800-8a16-11ea-8eec-7fbff8d96136.png)

**To Reproduce**
1. Use mintupdate to upgrade any package where you have manually modified the configuration files
2. Select the option "Side-by-side comparison"
3. Click next
4. You will get a line-by-line comparison

**Expected behavior**
A side-by-side comparison should appear

**Distribution:**
- [ ] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
5.5.9.

**Logs:**
04.29@08:09 ++ Found 3 software updates
04.29@08:09 ++ Refresh finished
04.29@08:09 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)
04.29@09:42 ++ Install requested by user
04.29@09:42 ++ Will install python-samba
04.29@09:42 ++ Will install libwbclient0
04.29@09:42 ++ Will install samba
04.29@09:42 ++ Will install samba-libs
04.29@09:42 ++ Will install samba-common
04.29@09:42 ++ Will install libsmbclient
04.29@09:42 ++ Will install smbclient
04.29@09:42 ++ Will install samba-common-bin
04.29@09:42 ++ Will install linux-libc-dev
04.29@09:42 ++ Will install linux-headers-generic-hwe-18.04
04.29@09:42 ++ Will install linux-image-generic-hwe-18.04
04.29@09:42 ++ Will install linux-generic-hwe-18.04
04.29@09:42 ++ Ready to launch synaptic

(synaptic:16096): Gtk-CRITICAL **: 09:42:44.197: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed

** (synaptic:16096): WARNING **: 09:46:28.041: no statusfd changes/content updates in terminal for 120 seconds

** (synaptic:16096): WARNING **: 09:46:28.041: TerminalTimeout in step: Configuring samba-common (amd64)

** (synaptic:16096): WARNING **: 09:50:25.024: no statusfd changes/content updates in terminal for 120 seconds

** (synaptic:16096): WARNING **: 09:50:25.024: TerminalTimeout in step: Configuring samba-common (amd64)
04.29@09:51 ++ Return code:0
04.29@09:51 ++ Install finished
04.29@09:51 ++ Starting refresh (local only)
04.29@09:51 ++ System is up to date
04.29@09:51 ++ Refresh finished

**Crash report:**
Nil crash

**Additional context**
Nil

**Locale:**
Nil

**Comment by clefebvre** [comment]
I can't figure out where the code is for this... it's not in mintupdate, it's not in synaptic, it doesn't seem  to be in APT even, maybe in debconf? or maybe it's provided by a diff tool?

It's definitely upstream from us.

**Comment by clefebvre** [comment]
Ok I found it. The package responsible for this is called ucf. Looking at its source code it calls diff and sdiff respectively with the following arguments:

```
diff -uBbwt file1 file2
sdiff -BbW file1 file2 
```

This is in Mint 20, I didn't check in 19.
