### ISSUE TITLE
Mint boot failure

### ISSUE THREAD

**Issue by KJ4SLE** [linuxmint/mintupdate#633]
After using this command: sudo dpkg --configure -a.

Mint will not boot.   I get the following: see pics
![20200712_180443](https://user-images.githubusercontent.com/67969490/87257730-6ac40f00-c46b-11ea-96eb-737156704900.jpg)
 I type help and get:
![20200712_180513](https://user-images.githubusercontent.com/67969490/87257737-80d1cf80-c46b-11ea-8e50-e7195d0e04b5.jpg)

- [ x] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Comment by clefebvre** [comment]
Use timeshift from a live ISO to restore the computer to its previously working state. Alternatively, still from the live ISO you can try and use boot-repair.
