### ISSUE TITLE
Warning Blocks Code

### ISSUE THREAD

**Issue by StellerJay** [linuxmint/mintupdate#634]
I have a bash script to open several programs and this is the part relating to mintUpdate:

if [ -z "$(pidof mintUpdate)" ]; then
    mintupdate &
    sleep 2
fi

In a terminal I get this message:

/usr/lib/linuxmint/mintUpdate/mintUpdate.py:1112: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:1258: DeprecationWarning: Gtk.ImageMenuItem.set_image is deprecated
  menuItem3.set_image(image)
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:638: DeprecationWarning: Gdk.threads_enter is deprecated
  Gdk.threads_enter()
/usr/lib/linuxmint/mintUpdate/mintUpdate.py:645: DeprecationWarning: Gdk.threads_leave is deprecated
  Gdk.threads_leave()

Without the 'if' loop the program opens, with the 'if' it doesn't. It also opens via a desktop file.

This issue started in the last few days. Unlike some other applications, mintUpdate will not open two instances so this is a minor issue. However, it might be causing issues elsewhere that I'm not aware of.

Mint 20/Mate
mintUpdate 5.6.9

**Comment by xenopeek** [comment]
mintupdate is automatically started 20 seconds after login. Have you disabled that in Startup Applications? When you start another mintupdate the already running process, if any, is killed (there's a feature request to change that).

You should redirect program output if you don't want to see it. This works as expected:
```
if [[ -z $(pidof mintUpdate) ]]; then
  nohup mintupdate &>/dev/null &
  sleep 2
fi
```
For further help with scripting use the [support forums](https://forums.linuxmint.com/viewforum.php?f=213).
