### ISSUE TITLE
mintupdate wants to install Libreoffice

### ISSUE THREAD

**Issue by oz42** [linuxmint/mintupdate#639]
Although I had uninstalled all Libreoffice components weeks ago, mintupdate wants to "update" a meta package named "libreoffice" that is not installed according to dpkg.

**Comment by xenopeek** [comment]
It shows the source package name in the updates. Many packages are built from libreoffice: https://packages.ubuntu.com/source/focal/libreoffice. Maybe it's the package fonts-opensymbol or python3-uno or one of the others on that list that you have installed. The details tab should say which packages specifically are included in the update.
