### ISSUE TITLE
Please add better support for flatpaks

### ISSUE THREAD

**Issue by ghost** [linuxmint/mintupdate#640]
**Is your feature request related to a problem? Please describe.**
The Update Manager does not support updates for flatpaks. The mintupdate-update-flatpak script on startup updates flatpaks automatically, but it should not handle updates like this. Also, there is no graphical way to add/remove flatpak repositories from Update manager.

**Describe the solution you'd like**
mintupdate should notify the user what updates are available and handle the updates same way as repository updates. Manual or Automatic ( as confirmed by user). GNOME software center does this. Also there should be a way to add/remove flatpak remotes easily. This can be done by cli command but I'm asking for a more complete package as the software manager

**Describe alternatives you've considered**
I've considered adding other software manager such as GNOME software center or Discover. Please let me know if they support my needs. But I really don't want multiple software managers on my system.

**Additional context**
I understand this is a reiteration of #296 and #404 but I think it should get more support in favour of mintinstall and mintupdate. Maybe a merge of the two apps like Pamac?

**Comment by orbitalchicken** [comment]
Also take a look at how Pop!_OS handles this. Software Manager and Software Updater are merged together and seams to include the update of Flatpaks.

**Comment by clefebvre** [comment]
see https://github.com/linuxmint/mintupdate/issues/644
