### ISSUE TITLE
Last update deleted a lot things

### ISSUE THREAD

**Issue by inpharmaticist** [linuxmint/mintupdate#641]
Not sure if this is the right place to put this but I accepted and upgrade that deleted multiple programs and folders. Once of which could have cost me a lot of Bitcoin, but I happened to have an old backup (I still lost some important data but all my funds were restored). I had timeshift activated, but the home folder wasn't included in those backups.

Not sure if you want more info, but this could have been pretty severe.

**Comment by clefebvre** [comment]
I do, which update was it and can you reproduce it again?

**Comment by inpharmaticist** [comment]
AFAIK it wasn't an OS update, but ~100 individual packages. I don't know how to reproduce it. In the Update Manager's History of Updates, I can take a screen shot of them all, but cant seem to copy/paste the text of the names of the packages nor export to csv.

**Comment by clefebvre** [comment]
Closed as the report only concluded to an observation.
