### ISSUE TITLE
update manager window not in focus

### ISSUE THREAD

**Issue by pakair** [linuxmint/mintupdate#643]
**Describe the bug**

The Update Manager window should always be on top (focus) when clicked.

**Screenshots**

https://imgur.com/JFaPMMJ

**To Reproduce**
1. start with empty Desktop
2. start a terminal
3. terminal is in focus (blinking white block cursor)
4. click on Update Manager (shield)
5. Window pops behind terminal

**Expected behavior**
Update Manager window should always be on top

**Distribution:**
LM 20 MATE, LM19.3 MATE 

Note: in LM19.2 MATE it behaves correctly.

Thank you

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintupdate/commit/b8a8b9e9da79603295916061a1f4ab47140539f5
