### ISSUE TITLE
Integrate Flatpak updates

### ISSUE THREAD

**Issue by orbitalchicken** [linuxmint/mintupdate#644]
I think that Flatpak updates should be integrated in the Update Manager.
The problem with the default behaviour is that the "mintinstall-update-flatpak" script which run automatically 20 minutes after startup, will ask for sudo password from time to time and the casual user have no idea why, no idea that's it's the flatpak updater which ask this, and no idea which flatpak will be updated. 

Then, mintinstall-update-flatpak should be removed from the startup applications.

**Comment by xenopeek** [comment]
Related to #640

**Comment by haggen88** [comment]
Maybe it would be nice to add a cleanup system that reclaims some space from any runtimes that may have been left
running: flatpak uninstall --unused

**Comment by michaelhmich** [comment]
> Maybe it would be nice to add a cleanup system that reclaims some space from any runtimes that may have been left
> running: flatpak uninstall --unused

isn it a flatpak thing, IMO flatpak and snap should do their thing, who knows if they disappear as fast as they came ...

**Comment by haggen88** [comment]
Flatpak from version 1.9.1 onwards [fixes](https://blogs.gnome.org/mwleeds/2021/01/11/cleaning-up-unused-flatpak-runtimes/) this problem. But since Mint still depends on the Flatpak package packaged by Ubuntu [who openly forces the use of Snap] you won't see these improvements until the next Ubuntu-based version [21.04 Hirsute Hippo brings 1.10.2-1], and Debian-based version [testing bullseye 2021-03-30 brings 1.10.2-1].

**Comment by finickydesert** [comment]
would doing a go-around by adding a repo directly instead of waiting for ubuntu to bring it up to date be a better solution?

**Comment by clefebvre** [comment]
- mintupdate now handles automated flatpak updates (this was moved from mintinstall).
- a flatpak upgrade is considered as part of the roadmap.
- mintupdate now handles cinnamon updates, it's the first mintupdate is able to handle multiple types of updates and this open up the possibility of a full flatpak support. We have this in our roadmap also so it could happen in Mint 20.2.

**Comment by orbitalchicken** [comment]
Great! Thanks!
