### ISSUE TITLE
[Minor:] Reboot prompt appears needless after updating an old kernel one is not using

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintupdate#645]
I have kernel 5.8.8. Recently mintupdate offered a security update to a 5.4 kernel - which I have installed, but neither had loaded not scheduled for boot. After the update, this showed:

![image](https://user-images.githubusercontent.com/47056543/93966739-58b0f780-fd5d-11ea-90bb-95d0401d4e4c.png)

But there is no need for that reboot, so far as I can tell. (Also, the comma in the text is ungrammatical. To fix that, change the comma to a semi-colon or a full-stop.)

MintUpdate 5.6.9 on Mint 20 Cinnamon.

**Comment by UnisTorvalds** [comment]
Possibly related to #728
