### ISSUE TITLE
Shouldn't 'Install Updates' be greyed-out when the system is up to date?

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintupdate#652]
**Describe the bug**

**Screenshots**
![image](https://user-images.githubusercontent.com/47056543/101561854-04153400-39be-11eb-8b5d-796696a05493.png)

**To Reproduce**
1. Have all updates installed.
2. Go to the Manager.
3. See the problem.

**Expected behavior**
Greyed-out 'Install Updates'.

**Distribution:**
- [X] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
5.6.9

**Logs:**
12.08@01:09 ++ Launching Update Manager
12.08@01:09 ++ Changes to the package cache detected, triggering refresh
12.08@01:09 ++ Starting refresh (local only)
12.08@01:09 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 10 minute(s)
12.08@01:09 ++ System is up to date
12.08@01:09 ++ Refresh finished

(synaptic:60858): Gtk-CRITICAL **: 01:13:21.112: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
12.08@01:13 ++ Starting refresh (local only)
12.08@01:13 ++ System is up to date
12.08@01:13 ++ Refresh finished
12.08@01:19 ++ Update Manager is in tray mode, performing initial refresh
12.08@01:19 ++ Starting refresh (retrieving lists of updates from remote servers)
12.08@01:19 ++ System is up to date
12.08@01:19 ++ Refresh finished
12.08@01:19 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)
12.08@01:21 ++ Changes to the package cache detected, triggering refresh
12.08@01:21 ++ Starting refresh (local only)
12.08@01:21 ++ System is up to date
12.08@01:21 ++ Refresh finished
12.08@17:59 ++ Changes to the package cache detected, triggering refresh
12.08@17:59 ++ Starting refresh (local only)
12.08@17:59 ++ Found 4 software updates
12.08@17:59 ++ Refresh finished
12.08@18:02 ++ Changes to the package cache detected, triggering refresh
12.08@18:02 ++ Starting refresh (local only)
12.08@18:02 ++ System is up to date
12.08@18:02 ++ Refresh finished
12.08@18:04 ++ Changes to the package cache detected, triggering refresh
12.08@18:04 ++ Starting refresh (local only)
12.08@18:04 ++ System is up to date
12.08@18:04 ++ Refresh finished
12.08@18:06 ++ Update Manager is in tray mode, performing recurring refresh
12.08@18:06 ++ Starting refresh (retrieving lists of updates from remote servers)
12.08@18:06 ++ System is up to date
12.08@18:06 ++ Refresh finished
12.08@18:06 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)
12.08@20:07 ++ Update Manager is in tray mode, performing recurring refresh
12.08@20:07 ++ Starting refresh (retrieving lists of updates from remote servers)
12.08@20:07 ++ System is up to date
12.08@20:07 ++ Refresh finished
12.08@20:07 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)
12.08@22:07 ++ Update Manager is in tray mode, performing recurring refresh
12.08@22:07 ++ Starting refresh (retrieving lists of updates from remote servers)
12.08@22:07 ++ System is up to date
12.08@22:07 ++ Refresh finished
12.08@22:07 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)
12.08@23:21 ++ Changes to the package cache detected, triggering refresh
12.08@23:21 ++ Starting refresh (local only)
12.08@23:21 ++ Found 1 software updates
12.08@23:21 ++ Refresh finished
12.08@23:23 ++ Changes to the package cache detected, triggering refresh
12.08@23:23 ++ Starting refresh (local only)
12.08@23:23 ++ System is up to date
12.08@23:23 ++ Refresh finished
12.09@00:07 ++ Update Manager is in tray mode, performing recurring refresh
12.09@00:07 ++ Starting refresh (retrieving lists of updates from remote servers)
12.09@00:07 ++ System is up to date
12.09@00:07 ++ Refresh finished
12.09@00:07 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)
12.09@01:19 ++ Starting refresh (retrieving lists of updates from remote servers)
12.09@01:19 ++ Found 1 software updates
12.09@01:19 ++ Refresh finished
12.09@01:19 ++ Install requested by user
12.09@01:19 ++ Will install libparted2
12.09@01:19 ++ Will install libparted-fs-resize0
12.09@01:19 ++ Will install parted
12.09@01:19 ++ Ready to launch synaptic

(synaptic:2323108): Gtk-CRITICAL **: 01:19:54.840: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
12.09@01:20 ++ Return code:0
12.09@01:20 ++ Install finished
12.09@01:20 ++ Starting refresh (local only)
12.09@01:20 ++ System is up to date
12.09@01:20 ++ Refresh finished

**Locale:**
LANG=en_GB.UTF-8
LANGUAGE=en_GB
LC_CTYPE=en_GB.UTF-8
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=

**Comment by mtwebster** [comment]
This is fixed in mintupdate 5.7:
https://github.com/linuxmint/mintupdate/commit/95212d08dcdd3eca40b301eb19209d6f076c58e5

Just not updated for mint 20 yet
