### ISSUE TITLE
Linux Kernel CVE Tracker links to package "linux.html" and therefore shows 0 results

### ISSUE THREAD

**Issue by agent-redd** [linuxmint/mintupdate#653]
**Describe the bug**
In "Update Manager" -> "View" -> "Linux Kernels" -> "CVE Tracker" the weblink leads to "https://ubuntu.com/security/cve?package=linux.html", which shows 0 results. This Link searches for package called "linux.html". Most probably the correct package name would be just "linux", without ".html". 

**Screenshots**
![Screenshot from 2021-01-06 13-32-09](https://user-images.githubusercontent.com/68111300/103769550-cb9c6080-5024-11eb-810c-617bf475ca6b.png)

**To Reproduce**
1. Open "Update Manager" 
2. Click on "View"
3. Click on "Linux Kernels"
4. Click "Continue" on Warning Popup 
4. Select any Linux Kernel
5. Click on "CVE Tracker"
6. Link opens in Webbrowser (https://ubuntu.com/security/cve?package=linux.html) and shows 0 results

**Expected behavior**
I guess the expected link is "https://ubuntu.com/security/cve?package=linux", which shows currently more than two thousand search results.

**Distribution:**
- [Linux Mint 20 Cinnamon] Linux Mint
- [NOT TESTED] LMDE
- [NOT TESTED] Other (please specify)

**Software version:**
5.6.9

**Logs:**
01.06@13:44 ++ Launching Update Manager
01.06@13:44 ++ Changes to the package cache detected, triggering refresh
01.06@13:44 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 10 minute(s)
01.06@13:44 ++ Starting refresh (local only)
01.06@13:44 ++ Found 1 software updates
01.06@13:44 ++ Refresh finished

**Crash report:**
No Crash related

**Additional context**
Bug search for "cve" did not found any open or closed Issue on this Git Repository, so I decided to open an Issue by myself.
(https://github.com/linuxmint/mintupdate/issues?q=is%3Aissue+is%3Aopen+cve)
I also read all the Headlines of all open Issues and no one indicated that this problem was already reported.

**Locale:**
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=

**Comment by agent-redd** [comment]
Update: I created a Pull Request here: https://github.com/linuxmint/mintupdate/pull/654
(i am pretty new on Github, so please be friendly if I did something wrong. I am eager to learn.)

**Comment by mtwebster** [comment]
#654 merged, thanks
