### ISSUE TITLE
Bug - Type E: 

### ISSUE THREAD

**Issue by 4User84** [linuxmint/mintupdate#659]
E:Type 'echo' is not known on line 2 in source list /etc/apt/sources.list.d/balena-etcher.list, E:The list of sources could not be read.

**To Reproduce**
I can't be as detailed as you'd like, as I'm new to Linux Mint, but here's what I did:
Researching how to create a bootable linux drive in linux mint 19.1 Cinnamon 32 (which I have installed), typed into Terminal the command to download Etcher (which didn't work...probably my my error), then updated my PC while trying to find Etcher online. Downloaded it, ran it, now updater gives me this:
E:Type 'echo' is not known on line 2 in source list /etc/apt/sources.list.d/balena-etcher.list, E:The list of sources could not be read.
I've deleted Etcher from the updater, still comes up with that error.

**Expected behavior**

**Distribution:**
- [ ] Linux Mint Tessa 19.1, Cinnamon, 32-bit

**Software version:**

**Logs:**
01.26@09:48 ++ Launching mintUpdate 
01.26@09:48 ++ Starting refresh 
01.26@09:48 ++ Initial refresh will happen in 10 minutes, 0 hours and 0 days 
01.26@09:48 ++ System is up to date 
01.26@09:48 ++ Refresh finished 
01.26@09:58 ++ MintUpdate is in tray mode, performing initial refresh 
01.26@09:58 ++ Starting refresh (including refreshing the APT cache) 
01.26@09:58 ++ Auto-refresh will happen in 0 minutes, 2 hours and 0 days 
01.26@09:58 ++ Error in checkAPT.py, could not refresh the list of updates 
01.26@10:47 ++ Starting refresh (including refreshing the APT cache) 
01.26@10:49 ++ Found 35 software updates 
01.26@10:49 ++ Refresh finished 
01.26@10:53 ++ Install requested by user 
01.26@10:53 ++ Will install libsasl2-modules-db 
01.26@10:53 ++ Will install libsasl2-2 
01.26@10:53 ++ Will install libsasl2-modules 
01.26@10:53 ++ Will install dnsmasq-base 
01.26@10:53 ++ Will install firefox-locale-en 
01.26@10:53 ++ Will install firefox 
01.26@10:53 ++ Will install libgs9 
01.26@10:53 ++ Will install ghostscript 
01.26@10:53 ++ Will install ghostscript-x 
01.26@10:53 ++ Will install libgs9-common 
01.26@10:53 ++ Will install libmagickwand-6.q16-3 
01.26@10:53 ++ Will install libmagickcore-6.q16-3 
01.26@10:53 ++ Will install imagemagick-6-common 
01.26@10:53 ++ Will install libproxy1v5 
01.26@10:53 ++ Will install libproxy1-plugin-gsettings 
01.26@10:53 ++ Will install libproxy1-plugin-networkmanager 
01.26@10:53 ++ Will install libopenexr22 
01.26@10:53 ++ Will install p11-kit 
01.26@10:53 ++ Will install p11-kit-modules 
01.26@10:53 ++ Will install libp11-kit0 
01.26@10:53 ++ Will install python3-pil 
01.26@10:53 ++ Will install python-apt-common 
01.26@10:53 ++ Will install python-apt 
01.26@10:53 ++ Will install python3-apt 
01.26@10:53 ++ Will install python-xdg 
01.26@10:53 ++ Will install python3-xdg 
01.26@10:53 ++ Will install tar 
01.26@10:53 ++ Will install tzdata 
01.26@10:53 ++ Will install unzip 
01.26@10:53 ++ Will install libwavpack1 
01.26@10:53 ++ Will install xdg-utils 
01.26@10:53 ++ Will install linux-headers-generic 
01.26@10:53 ++ Will install linux-image-generic 
01.26@10:53 ++ Will install linux-generic 
01.26@10:53 ++ Will install linux-libc-dev 
01.26@10:53 ++ Will install adobe-flashplugin 
01.26@10:53 ++ Will install apport 
01.26@10:53 ++ Will install python3-apport 
01.26@10:53 ++ Will install python3-problem-report 
01.26@10:53 ++ Will install libaudit-common 
01.26@10:53 ++ Will install libaudit1 
01.26@10:53 ++ Will install libcaribou0 
01.26@10:53 ++ Will install libcaribou-common 
01.26@10:53 ++ Will install caribou 
01.26@10:53 ++ Will install gir1.2-caribou-1.0 
01.26@10:53 ++ Will install libcephfs2 
01.26@10:53 ++ Will install librados2 
01.26@10:53 ++ Will install libc6-dbg 
01.26@10:53 ++ Will install libc6 
01.26@10:53 ++ Will install locales 
01.26@10:53 ++ Will install libc-bin 
01.26@10:53 ++ Will install multiarch-support 
01.26@10:53 ++ Will install grub-common 
01.26@10:53 ++ Will install grub2-common 
01.26@10:53 ++ Will install grub-pc 
01.26@10:53 ++ Will install grub-pc-bin 
01.26@10:53 ++ Will install gir1.2-appindicator3-0.1 
01.26@10:53 ++ Will install libappindicator0.1-cil 
01.26@10:53 ++ Will install libappindicator3-1 
01.26@10:53 ++ Will install libappindicator1 
01.26@10:53 ++ Will install libevdev2 
01.26@10:53 ++ Will install libinput-bin 
01.26@10:53 ++ Will install libinput10 
01.26@10:53 ++ Will install mintdrivers 
01.26@10:53 ++ Will install mint-mirrors 
01.26@10:53 ++ Will install mintsystem 
01.26@10:53 ++ Will install libsystemd0 
01.26@10:53 ++ Will install udev 
01.26@10:53 ++ Will install libudev1 
01.26@10:53 ++ Will install libnss-myhostname 
01.26@10:53 ++ Will install systemd-sysv 
01.26@10:53 ++ Will install libpam-systemd 
01.26@10:53 ++ Will install systemd 
01.26@10:53 ++ Will install libnss-systemd 
01.26@10:53 ++ Will install python3-distupgrade 
01.26@10:53 ++ Will install ubuntu-release-upgrader-core 
01.26@10:53 ++ Will install update-notifier-common 
01.26@10:53 ++ Will install wpasupplicant 
01.26@10:53 ++ Ready to launch synaptic 

(synaptic:7015): Gtk-CRITICAL **: 10:54:06.701: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
01.26@11:18 ++ Return code:0 
01.26@11:18 ++ Install finished 
01.26@11:18 ++ Starting refresh 
01.26@11:18 ++ System is up to date 
01.26@11:18 ++ Refresh finished 
01.26@11:58 ++ MintUpdate is in tray mode, performing auto-refresh 
01.26@11:58 ++ Starting refresh (including refreshing the APT cache) 
01.26@11:58 ++ Auto-refresh will happen in 0 minutes, 2 hours and 0 days 
01.26@11:58 ++ Error in checkAPT.py, could not refresh the list of updates 
01.26@12:46 ++ Starting refresh (including refreshing the APT cache) 
01.26@12:46 ++ Error in checkAPT.py, could not refresh the list of updates 
01.26@12:46 ++ Starting refresh (including refreshing the APT cache) 
01.26@12:46 ++ Error in checkAPT.py, could not refresh the list of updates 
01.26@12:46 ++ Starting refresh (including refreshing the APT cache) 
01.26@12:46 ++ Error in checkAPT.py, could not refresh the list of updates 
01.26@13:58 ++ MintUpdate is in tray mode, performing auto-refresh 
01.26@13:58 ++ Auto-refresh will happen in 0 minutes, 2 hours and 0 days 
01.26@13:58 ++ Starting refresh (including refreshing the APT cache) 
01.26@13:58 ++ Error in checkAPT.py, could not refresh the list of updates 
01.26@14:53 ++ Starting refresh (including refreshing the APT cache) 
01.26@14:53 ++ Error in checkAPT.py, could not refresh the list of updates 
01.26@14:53 ++ Install requested by user 
01.26@14:54 ++ Starting refresh 
01.26@14:54 ++ Error in checkAPT.py, could not refresh the list of updates 

**Additional context**
Add any other context about the problem you think might be relevant.

**Locale:**
Oh, I also attempted to switch to a local mirror. The problem didn't show up until Etcher was run on my PC.

**Comment by xenopeek** [comment]
This isn't a bug. For help with Linux Mint kindly make use of the support forums: https://forums.linuxmint.com/viewforum.php?f=47.

I assume from the 'echo' that you followed these instructions to add a .deb repository to your system: https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64. That 'echo' in your  /etc/apt/sources.list.d/balena-etcher.list file means you made a mistake with the command to add the repository. Delete that file (`sudo rm -v /etc/apt/sources.list.d/balena-etcher.list`) and try again. For further help use the support forums please.
