### ISSUE TITLE
Schedule on which days to do automatic updates

### ISSUE THREAD

**Issue by enigma131** [linuxmint/mintupdate#663]
Is it possible to have a feature I haven't see in other distros?
For example, at week times , I don't care about updates because I'm at work, i don't apply them at evening.
At the beginning of weekend , I apply manually all updates for past week.
Is it possible to schedule this automaticly, by adding a new line in preferences, automatic update, selecting day + time of week.
Quasi similar to #651
Thanks in advance.
BR

**Comment by clefebvre** [comment]
I think it becomes overkill at that point. The UI is there to make it easy, not give as much granularity as the underlying systemd timer. This can be tuned precisely via cron and/or systemd timers already which are designed specifically for that.

**Comment by enigma131** [comment]
Ok then, i will continue to apply updates manually every 1 or 2 weeks_ends. I haven't time to study cron alternative
