### ISSUE TITLE
Check AC Connect before doing automated upgrades

### ISSUE THREAD

**Issue by MidnightNerd** [linuxmint/mintupdate#667]
The automated updates shouldn't be applied when the computer is in battery mode. 

A solution would be to check whether cat /sys/class/power_supply/AC/online returns 1. 
as Python bool: open("/sys/class/power_supply/AC/online").read()[0]=='1'

If battery mode is checked in automatic_upgrades script, the problem is, that the script isn't executed again, when the computer is connected with a power supply.

Thank You.

**Comment by clefebvre** [comment]
That's a good point. @MidnightNerd could you turn this into a PR?

**Comment by clefebvre** [comment]
I think the problem you mentioned would be OK, since upgrades happen every day. There would be no need to react to power coming back, we'd just skip days when power is on battery.

**Comment by Lurux** [comment]
@clefebvre Eh, I think this could be a problem. I have a laptop that I use primarily on battery, so having the laptop plugged in and powered on at the specific update check time would be pretty rare. (I would not enable automatic updates on such a laptop in the first place, but that's not the point).

Does the update manager at least still show a tray icon when automatic updates are enabled, but they are ignored or fail to run ? That would be a simple fix for both this and #669.

**Comment by MidnightNerd** [comment]
I could add a notification to show when updates aren't applied due to run on battery. However i think some people find this behaviour annoying as notifications are very visible.
Additionally i would also check whether the connection is metered before applying updates.

**Comment by Lurux** [comment]
If the tray icon still indicates available updates if automatic updates are skipped (whether due to battery or other reasons), there is no need for additional notifications really.

I'm just thinking about it now, but maybe a setting to skip automatic updates _under a certain battery threshold_ would be a more flexible option ? Dunno if this would be worth the hassle though.

**Comment by MidnightNerd** [comment]
The tray icon is independent from the automatic upgrades script. So updates are indicated in tray if they are available. 
But there's no indication about the reason. So the tray icon only say "x updates available".
 I'm also no systemd expert, so i can't tell you whether systemd can trigger the service when power is connected.

A different solution would be using dbus. This would make it also possible to check whether the network connection is metered.
The Idea is to connect to "org.freedesktop.NetworkManager" and "org.freedesktop.UPower" 
PropertiesChanged signal and check whether the conditions to run automatic upgrades are fullfilled.

**Comment by Lurux** [comment]
Nah, not in the power options; this is a Mintupdate specific thing, not a general Cinnamon setting.

Ideally I think we'd want to hide the tray icon when automatic updates are enabled, unless said updates fail or are skipped. This would avoid confusion for users who don't know that the tray icon and automatic updates run on different schedules.

It would probably be useful in the case of automatic downloads, too. But that's probably a separate issue :slightly_smiling_face:

**Comment by Lurux** [comment]
I don't know about that. @clefebvre ?

Again, this problem isn't a possibility if we check the battery level instead, which IMO might be a better option (the chances of the updates kicking while the computer is on *and* charging seems pretty low, while updating when the battery is ie. above 50% seems perfectly reasonable to me)

**Comment by MidnightNerd** [comment]
@Lurux The battery level is sometimes no good solution. Think of someone who uses the computer for a longer time with no charger.
The energy could be too less at the end of the day due to updates. 

The best solution in my opinion is to connect to UPower via DBus and make the battery level configurable in MintUpdate. 
If there's a handler for the UPower "PropertiesChanged" signal this could be used also to apply updates when a power supply is attached.

**Comment by Lurux** [comment]
> The best solution in my opinion is to connect to UPower via DBus and make the battery level configurable in MintUpdate.

Yeah of course the battery level would be configurable, that makes sense.

> If there's a handler for the UPower "PropertiesChanged" signal this could be used also to apply updates when a power supply is attached.

That would be epic !

Btw, sorry i can't help much with this but I'm not too technical with Linux yet so for now I'll stick to working on the GUI side of things :smile:

**Comment by MidnightNerd** [comment]
I wrote a script that uses dbus to connect to UPower and NetworkManager. This enables
Can someone take a look at the script?

[automatic_upgrades.py.txt](https://github.com/linuxmint/mintupdate/files/6452028/automatic_upgrades.py.txt)

If you have questions please ask.

**Comment by Lurux** [comment]
Sorry I can't help with that, you'll probably need to see this with clefebvre or mtwebster :slightly_smiling_face:
