### ISSUE TITLE
Download progress is misleading and incorrect

### ISSUE THREAD

**Issue by aaronmdjones** [linuxmint/mintupdate#671]
**Describe the bug**
When expanding the details in the update download dialog, all downloads start out with the status "Done".

**To Reproduce**
1. Begin an update procedure (click the `Install Updates` button when presented with updates).
2. Click on `Show individual files` in the "Downloading Package Files" dialog.
3. Observe that all updates immediately say "Done" in their "Status" column, even though it has only just begun downloading them.

**Expected behavior**
1. All updates should start out with the status "Queued", not "Done".
2. The currently-downloading update should have a percentage.
3. Only when a download has completed should it transition to "Done".

**Distribution:**
- [X] Linux Mint

**Software version:**
MintUpdate 5.7.3

**Screenshots**
![updmgr1](https://user-images.githubusercontent.com/3105118/114249205-71939a00-9989-11eb-9242-129aac84082c.png)
![updmgr2](https://user-images.githubusercontent.com/3105118/114249213-75272100-9989-11eb-9ed2-f5d341276063.png)
![updmgr3](https://user-images.githubusercontent.com/3105118/114249216-78221180-9989-11eb-81fd-3534f3359120.png)
![updmgr4](https://user-images.githubusercontent.com/3105118/114249219-7bb59880-9989-11eb-8770-4b90c5f22b65.png)

**Comment by clefebvre** [comment]
This is an upstream component (in synaptic).
