### ISSUE TITLE
Hide mintUpdate status icon in certain cases

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/mintupdate#68]
Currently, mintUpdate's status icon is always shown. I think this is unnecessary in certain situations.
As an example, I don't need to know when everything's OK and my system is up2date. I want to know when something's NOT working or something important happens, e.g. a new update is released.

So I think the tray icon of mintupate should only be shown of necessary.
For me, necessary means:
- New update
- Updates are installing
- Some grave error ocurred

I don't think the icon needs to be shown when:
- System is up2date
- Checking for new updates
- APT is locked &rarr; will work when released, not important
- Package lists couldn't be loaded &rarr; usually network problem, needn't be notified otherwise.

I've already patched my updater with #67 and I'd like to see it in Linux Mint by default.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintupdate/commit/00a8f6dd3e26abd8a82bc9e51b32d80259158d97
