### ISSUE TITLE
'apt install python3-dev' fails on Linux Mint 20 (amd64)

### ISSUE THREAD

**Issue by holta** [linuxmint/mintupdate#680]
Very mysteriously this apt package is installable on Ubuntu but not on Mint.

It's certainly shown as installable on Linux Mint 20:

```
root@box:~# apt list python3-dev
Listing... Done
python3-dev/focal 3.8.2-0ubuntu2 amd64
python3-dev/focal 3.8.2-0ubuntu2 i386
```

But in the end it's not installable:

```
root@box:~# apt install python3-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-dev : Depends: libpython3-dev (= 3.8.2-0ubuntu2) but it is not going to be installed
               Depends: python3.8-dev (>= 3.8.2-1~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

System Context if it helps:

```
root@box:~# cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20
DISTRIB_CODENAME=ulyana
DISTRIB_DESCRIPTION="Linux Mint 20 Ulyana"
```

```
root@box:~# uname -a
Linux box.lan 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Three people have tried to make this work and have been unable: https://github.com/iiab/iiab/issues/2783

Any suggestions as to what we're overlooking?  Thanks!

**Comment by mtwebster** [comment]
Hi, can paste the output from:

```
apt policy python3 python3-dev python3.8 python3.8-dev
```

What happens if you try:
```
apt install python3-dev libpython3-dev python3.8-dev
```

**Comment by holta** [comment]
Thanks @mtwebster &mdash; here's the output to both commands:

```
root@box:~# apt policy python3 python3-dev python3.8 python3.8-dev
python3:
  Installed: 3.8.2-0ubuntu2
  Candidate: 3.8.2-0ubuntu2
  Version table:
 *** 3.8.2-0ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
python3-dev:
  Installed: (none)
  Candidate: 3.8.2-0ubuntu2
  Version table:
     3.8.2-0ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
python3.8:
  Installed: 3.8.5-1~20.04.2
  Candidate: 3.8.5-1~20.04.2
  Version table:
 *** 3.8.5-1~20.04.2 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
        100 /var/lib/dpkg/status
     3.8.2-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
python3.8-dev:
  Installed: (none)
  Candidate: 3.8.5-1~20.04.2
  Version table:
     3.8.5-1~20.04.2 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     3.8.2-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages

```

```
root@box:~# apt install python3-dev libpython3-dev python3.8-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpython3-dev : Depends: libpython3.8-dev (>= 3.8.2-1~) but it is not going to be installed
 python3.8-dev : Depends: libpython3.8-dev (= 3.8.5-1~20.04.2) but it is not going to be installed
                 Depends: libexpat1-dev but it is not going to be installed
                 Depends: zlib1g-dev but it is not going to be installed
                 Recommends: libc6-dev but it is not going to be installed or
                             libc-dev
E: Unable to correct problems, you have held broken packages.
```

Anything else I should try?

**Comment by mtwebster** [comment]
Can you run mintsources (Software Sources in the menu) - in Maintenance, check if you have any PPAs that may be interfering, and then check for foreign packages there.

**Comment by holta** [comment]
In the Start menu at the bottom-left of the screen, I clicked Administration > Software Sources > PPAs.  There are no PPA's listed there.

Then I clicked Software Sources > Maintenance > Remove foreign packages.  Removing these 5 seemed far too dangerous (and very much unrelated, I would assume) so I did not proceed click 'Remove' :

- linux-headers-5.4.0-56
- linux-headers-5.4.0-56-generic
- linux-image-5.4.0-56-generic
- linux-modules-5.4.0-56-generic
- linux-modules-extra-5.4.0-56-generic

Anything else I should try?

**Comment by holta** [comment]
I decided to risk it, and went ahead removing the 5 above "foreign packages" (linux 5.4.0-56).

Then I did `apt update` and it fails in the usual way:

```
root@box:~# apt list python3-dev
Listing... Done
python3-dev/focal 3.8.2-0ubuntu2 amd64
python3-dev/focal 3.8.2-0ubuntu2 i386
```

```
root@box:~# apt install python3-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-dev : Depends: libpython3-dev (= 3.8.2-0ubuntu2) but it is not going to be installed
               Depends: python3.8-dev (>= 3.8.2-1~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by xenopeek** [comment]
From the mention of libc6-dev in your apt install output this might be cause by you having libc6 version 2.31-0ubuntu**9.3** installed. Ubuntu published that version but later removed it from its servers because it broke Snap programs. Until Ubuntu publishes that version (or newer) again it leaves users that installed it before it was removed with [broken dependencies](https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1926918).

Run command `apt version libc6` to check your libc6 version. If it is 2.31-0ubuntu**9.3** I suggest downgrading it to 2.31-0ubuntu**9.2**. That will likely solve your issue. You will have to downgrade all related packages (any packages you have installed built from [glibc](https://packages.ubuntu.com/source/focal-updates/glibc)).

You can do that manually or you can run this command to do it in one go:

```
apt install $(dpkg -l | egrep '(libc|locales|nscd).* 2.31-0ubuntu9.3 ' | cut -d' ' -f3 | paste -sd ' ' | sed -r 's/( |$)/=2.31-0ubuntu9.2 /g')
```

It will prompt you with what it will do. Before you continue check that it will ONLY downgrade packages and WON'T remove anything!

**Comment by holta** [comment]
@xenopeek miraculously that worked, Thank You !

I ran your long command and it downgraded these 4 packages: (from 2.31-0ubuntu9.3 to 2.31-0ubuntu9.2)

- libc6-dbg:amd64
- libc6:amd64
- locales
- libc-bin

As verified by:

```
root@box:~# apt version libc6
2.31-0ubuntu9.2
```

`apt install python3-dev` then worked!

(Others might still experience this, but at least we can tell them to do a fresh install of Linux Mint 20...to hopefully avoid the entire adventure ;-)

**Comment by xenopeek** [comment]
> (Others might still experience this, but at least we can tell them to do a fresh install of Linux Mint 20...to hopefully avoid the entire adventure ;-)

I hope you meant to tell others to **not** do a fresh install? Downgrading glibc packages is sufficient, until Ubuntu does the necessary.

**Comment by holta** [comment]
> Downgrading glibc packages is sufficient, until Ubuntu does the necessary.

Right.  In our use case, most everyone is doing a fresh OS install right before they install [Internet-in-a-Box](http://internet-in-a-box.org/) and then ship it out to schools/libraries/clinics in a developing world country.  So we can guide them to either option (fix an old install of Linux Mint 20, or grab a brand new OS!)  But yes, you're absolutely right in most/normal circumstances nobody wants to reinstall their OS (:

_Thanks Again!  The crux being what you wrote earlier:_

> Ubuntu published that version but later removed it from its servers because it broke Snap programs. Until Ubuntu publishes that version (or newer) again it leaves users that installed it before it was removed with broken dependencies.
