### ISSUE TITLE
Evolution being removed on latest upgrade

### ISSUE THREAD

**Issue by dm2912** [linuxmint/mintupdate#681]
**Describe the bug**
Updating evolution in mint update is instead removing evolution

**Screenshots**
![image](https://user-images.githubusercontent.com/25871666/120518302-58c3c580-c3c9-11eb-8e4a-dc7d74a0ac43.png)

**To Reproduce**
1. Go to update
2. Try to update evolution
 
Also reported on forums that it is actually removed completely following "update"

https://forums.linuxmint.com/viewtopic.php?f=47&t=350266&p=2022325#p2022325

If you via apt upgrade then its holding it back from the upgrade

![image](https://user-images.githubusercontent.com/25871666/120518449-83158300-c3c9-11eb-9c9f-2716285cd484.png)

**Comment by xenopeek** [comment]
On a fresh (updated) install of Mint 20.1 it installs without issue. Can you please run the command `apt install evolution` on the terminal and share the output here? That will likely provide clues as to what is going on. You can copy text from the terminal through its Edit menu; do Select All and then Copy.

**Comment by dm2912** [comment]
Evolution is still installed on my system, I did not proceed with the update as others reported that Evolution was no longer accessible and could no longer be installed. 

However, even with evolution currently installed, apt install is returning

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  evolution-common evolution-data-server evolution-data-server-common
  gir1.2-camel-1.2 gir1.2-ebackend-1.2 gir1.2-ebook-1.2
  gir1.2-ebookcontacts-1.2 gir1.2-edatabook-1.2 gir1.2-edataserver-1.2
  libcamel-1.2-62 libcamel1.2-dev libebackend-1.2-10 libebackend1.2-dev
  libebook-1.2-20 libebook-contacts-1.2-3 libebook-contacts1.2-dev
  libebook1.2-dev libecal-2.0-1 libedata-book-1.2-26 libedata-book1.2-dev
  libedata-cal-2.0-1 libedataserver-1.2-24 libedataserver1.2-dev
  libedataserverui-1.2-2 libevolution
Suggested packages:
  evolution-ews evolution-plugins-experimental
Recommended packages:
  evolution-plugins evolution-plugin-bogofilter
  | evolution-plugin-spamassassin evolution-plugin-pstimport
The following packages will be upgraded:
  evolution evolution-common evolution-data-server
  evolution-data-server-common gir1.2-camel-1.2 gir1.2-ebackend-1.2
  gir1.2-ebook-1.2 gir1.2-ebookcontacts-1.2 gir1.2-edatabook-1.2
  gir1.2-edataserver-1.2 libcamel-1.2-62 libcamel1.2-dev libebackend-1.2-10
  libebackend1.2-dev libebook-1.2-20 libebook-contacts-1.2-3
  libebook-contacts1.2-dev libebook1.2-dev libecal-2.0-1 libedata-book-1.2-26
  libedata-book1.2-dev libedata-cal-2.0-1 libedataserver-1.2-24
  libedataserver1.2-dev libedataserverui-1.2-2 libevolution
26 to upgrade, 0 to newly install, 0 to remove and 10 not to upgrade.
Need to get 6,406 kB of archives.
After this operation, 73.7 kB disk space will be freed.
Do you want to continue? [Y/n] 

`

**Comment by dm2912** [comment]
it looks like the issue has been rectified overnight. 

Evolution-data is now showing in the available updates, and its no longer prompting that evolution will be removed.
