### ISSUE TITLE
LaunchPad has no source text to translate

### ISSUE THREAD

**Issue by vegam57** [linuxmint/mintupdate#685]
**Describe the bug**
LaunchPad has no source text to translate
mintUpdate5.7.6 on LM20.2Beta

**Screenshots**
If applicable, add screenshots to help explain your problem, you can just drag & drop them here.
![スクリーンショット 2021-06-18 10-11-14](https://user-images.githubusercontent.com/78515193/122491157-737b7880-d01e-11eb-87a2-3c6cdf93483e.png)

**Software version:**
mintUpdate5.7.6 on LM20.2Beta

**Comment by clefebvre** [comment]
POT reuploaded to LP. Sorry, I'm not sure what happened, I must have missed it somehow at the time.
