### ISSUE TITLE
Go to

### ISSUE THREAD

**Issue by Daahir1** [linuxmint/mintupdate#699]
**Describe the bug**

**Screenshots**
If applicable, add screenshots to help explain your problem, you can just drag & drop them here.

**To Reproduce**

**Expected behavior**

**Distribution:**
- [ ] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
See Help > About in Update Manager.

**Logs:**
Copy & paste the log output from Update Manager > View > Information here.

**Crash report:**
If you are reporting a crash, please run `mintupdate` from a terminal window, reproduce the crash and copy & paste any output from the terminal window here.

**Additional context**
Add any other context about the problem you think might be relevant.

**Locale:**
If the problem is with text not getting displayed correctly, paste the output of the terminal command `locale`.

**Comment by Daahir1** [comment]
no

**Comment by xenopeek** [comment]
You have entered none of the requested information for reporting a bug, or any information at all. Assuming you made a mistake and closing this.
