### ISSUE TITLE
Allow accepting new packages with enter key

### ISSUE THREAD

**Issue by sinistersnare** [linuxmint/mintupdate#700]
**Is your feature request related to a problem? Please describe.**

When packages are updated, sometimes new packages must be installed. At the moment the dialog that pops up with the new packages needs to be clicked with a mouse, there is no way to accept the dialog with the keyboard

**Describe the solution you'd like**

When that dialog comes up, allow the 'enter' key to accept the dialog (much like after you type a password you can hit enter)

**Describe alternatives you've considered**

Maybe determine the packages that need to be added beforehand and show that in the update-list UI in the first place, instead of having a pop-up.

**Additional context**

Only happens when a package update adds new packages to be installed.

**Comment by sbadux** [comment]
I can't test what you are describing, but installing by pressing only the "Enter" key may be not the best solution because the user may press it unintentionally.
Maybe the pre-selected key should be "Cancel" but the users should be allowed to switch to the "Confirm" using the arrow keys

**Comment by sinistersnare** [comment]
You can test it when there is a kernel update, when new packages need to be installed on top of the current set. It seems you can scroll through the items, and then reach the cancel/ok dialog after all, but a more intuitive control of that would be great.

**Comment by sbadux** [comment]
I've tested this today, with the last kernel updated. You can accept with the keyboard pressing TAB twice and the Enter. This works and may solve your issue

**Comment by sinistersnare** [comment]
Yeah, I just noticed that too. I was pretty sure it didn't work like this before, but it works now at least!

Thanks.
