### ISSUE TITLE
LMDE4 has an upgrade of mintinstall which has missing dependencies

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/mintupdate#711]
**Describe the bug**
A package in LMDE4 - `mintinstall` is shown for upgrade, but it has missing dependencies.

**Screenshots**

![Screenshot from 2021-11-26 15-15-59](https://user-images.githubusercontent.com/52585119/143602326-a2505ba9-0939-4a2b-b350-3fc372fe61d0.png)

**To Reproduce**

See (for example, Synaptic)

**Expected behavior**

All packages should either be installable or not, if offered for installation.

**Distribution:**
- [ ] Linux Mint
- [  X ] LMDE
- [ ] Other (please specify)

**Software version:**
See Help > About in Update Manager = 5.7.8

**Additional context**

Suggest that the problem is due to the absence of several `girl1.2*` packages.

Also, an APT package should **not** be suggesting that Flatpak be installed.

**Comment by clefebvre** [comment]
hi @Jeremy7701 which dep is missing?

**Comment by Jeremy7701** [comment]
Hi @clefebvre,

I ran a `apt-cache showpkg mintinstall`
This shows that the new version of mininstall [8.0.9] has a dependency on `ca-certificates (>=20210101)`
The current version of mintinstall [8.0.8] has no dependency on `ca-certificates`
Also, the current version of `ca-certificates is 20200601~deb10u2`

BTW It all works OK in Mint 20.2, but LMDE is my main machine. ;)

**Comment by Jeremy7701** [comment]
I missed out a large part of the command `apt-cache showpkg mintinstall` - this may be significant:-

Package: mintinstall
Versions: 
8.0.9 (/var/lib/apt/lists/linux-mint.froonix.org_dists_debbie_main_binary-amd64_Packages) (/var/lib/apt/lists/linux-mint.froonix.org_dists_debbie_main_**binary-i386_Packages**)
 Description Language: 
                 File: /var/lib/apt/lists/linux-mint.froonix.org_dists_debbie_main_binary-amd64_Packages
                  MD5: 66f10cb8a0093e5a59b612a5cb38ad34
 Description Language: 
                 File: /var/lib/dpkg/status
                  MD5: 66f10cb8a0093e5a59b612a5cb38ad34

8.0.8 (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/linux-mint.froonix.org_dists_debbie_main_**binary-amd64_Packages**
                  MD5: 66f10cb8a0093e5a59b612a5cb38ad34
 Description Language: 
                 File: /var/lib/dpkg/status
                  MD5: 66f10cb8a0093e5a59b612a5cb38ad34


Reverse Depends: 
  mint-meta-core,mintinstall
[...]

**Comment by clefebvre** [comment]
I think we might need to backport http://ftp.debian.org/debian/pool/main/c/ca-certificates/ca-certificates_20210119_all.deb

**Comment by Jeremy7701** [comment]
Thanks - that worked (had to use `wget ftp.debian.org/debian/pool/main/c/ca-certificates/ca-certificates_20210119_all.deb` because firefox believes ftp is insecure).

`mintinstall` also updated successfully.

**Comment by clefebvre** [comment]
ca-certificates backported into debbie.
