### ISSUE TITLE
Change from the Telekom Romania server in the Orange Romania server

### ISSUE THREAD

**Issue by DorianB2017** [linuxmint/mintupdate#729]
For several months, Telekom Romania was bought by Orange and for several days the deposit server was changed from `http://mint.mirrors.telekom.ro/repos/` to `http://mint.mirrors.orange.ro/repos/`.
The old Telekom server is closed.
Please put the new server in "mintupdate" (Update Manager).
Thank you!

**Comment by xenopeek** [comment]
Thanks for reporting! We had been made aware earlier and we'll change the mirror list shortly. However for systems currently configured with this mirror it will require a manual intervention. I have put that on the forums here: https://forums.linuxmint.com/viewtopic.php?f=42&t=371386
