### ISSUE TITLE
Update Manager could not download all repository indexes

### ISSUE THREAD

**Issue by dntc0x** [linuxmint/mintupdate#743]
**Describe the bug**
Update Manager could not download all repository indexes
- I am not a software developer, but a user who keeps getting the following error from Update Manager in Linux Mint 20.2. Please forgive me if this is not the proper place to get help on this issue. 

**Screenshots**
If applicable, add screenshots to help explain your problem, you can just drag & drop them here.
![image](https://user-images.githubusercontent.com/109041512/178159602-ec1b8086-f92b-40cd-b138-fb96e3cf5620.png)

**To Reproduce**

**Expected behavior**

**Distribution:**
- [x] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
See Help > About in Update Manager.
- 5.8.4
**Logs:**
Copy & paste the log output from Update Manager > View > Information here.
07.10@14:41 ++ Launching Update Manager
07.10@14:41 ++ Changes to the package cache detected, triggering refresh
07.10@14:41 ++ Starting refresh (local only)
07.10@14:41 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 10 minute(s)
07.10@14:41 ++ System is up to date
07.10@14:41 ++ Refresh finished
07.10@14:42 ++ Starting refresh (retrieving lists of updates from remote servers)
07.10@14:51 ++ Update Manager window is open, skipping initial refresh
07.10@14:51 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 48 minute(s)
07.10@15:28 ++ Refreshing available Cinnamon updates from the server
07.10@15:28 ++ System is up to date
07.10@15:28 ++ Refresh finished
07.10@15:38 ++ Starting refresh (retrieving lists of updates from remote servers)
07.10@15:43 ++ Refreshing available Cinnamon updates from the server
07.10@15:43 ++ System is up to date
07.10@15:43 ++ Refresh finished
**Crash report:**
If you are reporting a crash, please run `mintupdate` from a terminal window, reproduce the crash and copy & paste any output from the terminal window here.
- No crash, just a recurring error

**Additional context**
Add any other context about the problem you think might be relevant.

**Locale:**
If the problem is with text not getting displayed correctly, paste the output of the terminal command `locale`.

**Comment by xenopeek** [comment]
If you need help with troubleshooting this please use the user support forums: https://forums.linuxmint.com/

If you followed the Brave installation instructions https://brave.com/linux/ you should not be getting this error. This error indicates the brave-browser-archive-keyring.gpg file is not installed or is not configured correctly for the Brave software repository. Update Manager is not the cause. The file is required for your package management system to be able to verify the integrity and authenticity of downloads from the Brave software repository.
