### ISSUE TITLE
unable to update - novice - help!

### ISSUE THREAD

**Issue by claregaiasophia** [linuxmint/mintupdate#776]
Ciao Github community.... I hope someone might be able to help: I am new to Ubuntu, etc, and have a problem where my updates are not updating - an error message comes across:

E: dpkg è stato interrotto. È necessario eseguire "dpkg --configure -a" per correggere il problema. 
E: _cache->open() failed, please report.

In English this means - 
"E: dpkg was interrupted. It is necessary to run "dpkg --configure -a" to correct the problem."
I am not sure how to do this, or how to report the problem....

**Comment by claregaiasophia** [comment]
PS I tried to use the black box on the desktop to run the command, but got this response: 
"dpkg: errore: l'operazione richiesta necessita dei privilegi di super-utente" Which means that the operation requires the privileges of a super-user. I am not sure how to proceed.

**Comment by carlosmintfan** [comment]
Try to run:
sudo dpkg --configure -a

eg. prefix the command with "sudo" to get super-user privileges.

**Comment by claregaiasophia** [comment]
Then it said this:
"/etc/kernel/postinst.d/zz-update-grub:
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/50_linuxmint.cfg'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.15.0-56-generic
Found initrd image: /boot/initrd.img-5.15.0-56-generic
Found linux image: /boot/vmlinuz-5.15.0-53-generic
Found initrd image: /boot/initrd.img-5.15.0-53-generic
Found linux image: /boot/vmlinuz-5.15.0-52-generic
Found initrd image: /boot/initrd.img-5.15.0-52-generic
Found linux image: /boot/vmlinuz-5.15.0-50-generic
Found initrd image: /boot/initrd.img-5.15.0-50-generic
Found linux image: /boot/vmlinuz-5.15.0-48-generic
Found initrd image: /boot/initrd.img-5.15.0-48-generic
Found linux image: /boot/vmlinuz-5.15.0-47-generic
Found initrd image: /boot/initrd.img-5.15.0-47-generic
Found linux image: /boot/vmlinuz-5.15.0-41-generic
Found initrd image: /boot/initrd.img-5.15.0-41-generic
Warning: os-prober will be executed to detect other bootable partitions.
Its output will be used to detect bootable binaries on them and create new boot entries.
done"

**Comment by claregaiasophia** [comment]
How fabulous - it is now updating perfectly - MANY thanks - I will try to make a note of this and make sense of it over time... still very new to Linux Mint! Blessings on your day.
