### ISSUE TITLE
prevent sleeping during updates

### ISSUE THREAD

**Issue by Koladweep** [linuxmint/mintupdate#780]
**Is your feature request related to a problem? Please describe.**
I was gone for a while during a lengthy update. I came back only to find the computer in the sleep mode. It turns out I had set power management app to put it into sleep after 10 minutes of disuse.

**Describe the solution you'd like**
The apps should communicate to each other about priority and precedence. For example, in this instance, system update is of higher precedence and the computer is not actually inactive as the power management app percieved it to be. So if there is some flag of activity or inactivity, mintupdate could take care of it.

**Describe alternatives you've considered**
Power management can be configured to better. 
**Additional context**
Add any other context or screenshots/illustrations about the feature request here.

**Comment by Lurux** [comment]
I suggest changing the title to "Inhibit power management during updates", this would be more descriptive.

**Comment by Koladweep** [comment]
@Lurux. Good idea. I had another issue. I had stupidly deleted some restore points to save hard drive space. When I used the timeshift a month later, I had forgotten that the restore point I was choosing from the catalog didn't exist anymore. Without checking the existence of the files that it planned to restore, timeshift proceeded zip through the deletion and then whoa! No icons no font and on rebooting , no operating system. It will be some time before I play around the linux powerhouse again. I got zapped pretty bad. Linux is not for toothless kids. I give it to Linux Mint. It is the one distro I used the longest 27 days. Would have used more had I read the documentation and had I not entered an hectic academic term. (other distros- Debian approx 1-2 weeks an others less than a week)

**Comment by Lurux** [comment]
@Koladweep sorry about that ! Tbf, this wouldn't have been a problem if you had deleted said backup from the Timeshift application instead of the file manager (which is what I assume you did here).

Also FYI if you enable automatic backups you can set the maximum number of backups Timeshift will keep before deleting the older ones.

**Comment by Koladweep** [comment]
Yes I agree, It would have been fine that way. Linux mint is the most wonderful implementation of Linux I have ever seen on a personal computer which is at the same time just as powerful as any server Linux.

I was being cocky and playing around with admin privileges without taking the time to learn how things work. Better to spend time learning than damage control. Lesson well learnt; I hope. No use moping over spoilt milk. I just mop it up.

**Comment by Koladweep** [comment]
Thanks. I opened a feature request. I think I and anyone using Linux should not use it like a Windows or a Mac. One should know what they are getting into and plan in advance to take the time to learn the nitty gritties of the working of the computers below the comfortable abstraction layer of the GUI world.

**Comment by Lurux** [comment]
@Koladweep Tbf this issue was alright, not sure why you closed it. Also I don't think this issue is specific to XFCE, so a more general title like "prevent sleeping during updates" might be better. You can edit it by clicking the "edit" button near the title.

**Comment by Koladweep** [comment]
@Lurux, Thanks. I'm new to Github reporting. The title you suggest is better.

**Comment by Lurux** [comment]
:tada:

**Comment by Koladweep** [comment]
Thanks.
