### ISSUE TITLE
after upgrade to latest mint, upgrade manager has overflow error when refreshing list

### ISSUE THREAD

**Issue by zolstarym** [linuxmint/mintupdate#782]
After upgrading to mint 21.1, the upgrade manager says could not refresh the list of updates. apt update works fine.

12.20@09:56 ++ Launching Update Manager
12.20@09:56 ++ Changes to the package cache detected, triggering refresh
12.20@09:56 ++ Starting refresh (local only)
12.20@09:56 ++ Initial refresh will happen in 3 day(s), 0 hour(s) and 10 minute(s)
12.20@09:56 -- Exception occurred in the refresh thread: <class 'OverflowError'>
12.20@09:56 ++ Starting refresh (retrieving lists of updates from remote servers)
12.20@09:56 ++ Refreshing available Cinnamon updates from the server
12.20@09:56 ++ Refreshing available Flatpak updates
12.20@09:57 -- Exception occurred in the refresh thread: <class 'OverflowError'>
12.20@09:57 ++ Starting refresh (local only)
12.20@09:57 -- Exception occurred in the refresh thread: <class 'OverflowError'>
12.20@09:57 ++ Starting refresh (retrieving lists of updates from remote servers)
12.20@09:57 ++ Refreshing available Cinnamon updates from the server
12.20@09:57 ++ Refreshing available Flatpak updates
12.20@09:57 -- Exception occurred in the refresh thread: <class 'OverflowError'>
12.20@09:57 ++ Starting refresh (retrieving lists of updates from remote servers)
12.20@09:58 ++ Refreshing available Cinnamon updates from the server
12.20@09:58 ++ Refreshing available Flatpak updates
12.20@09:58 -- Exception occurred in the refresh thread: <class 'OverflowError'>

(synaptic:7605): Gtk-CRITICAL **: 09:58:28.370: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
12.20@09:58 ++ Starting refresh (local only)
12.20@09:58 -- Exception occurred in the refresh thread: <class 'OverflowError'>

$ sudo apt update
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Ign:2 http://packages.linuxmint.com vera InRelease                             
Hit:3 https://dl.winehq.org/wine-builds/ubuntu jammy InRelease                 
Hit:4 http://packages.linuxmint.com vera Release                               
Hit:5 https://download.virtualbox.org/virtualbox/debian jammy InRelease        
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease                         
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease                 
Hit:9 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu kinetic InRelease
Hit:10 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease          
Hit:12 http://ppa.launchpad.net/libretro/stable/ubuntu jammy InRelease     
Hit:13 http://ppa.launchpad.net/ubuntuhandbook1/apps/ubuntu jammy InRelease
Reading package lists... Done                        
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

**Describe the bug**

**Screenshots**
If applicable, add screenshots to help explain your problem, you can just drag & drop them here.

**To Reproduce**

**Expected behavior**

**Distribution:**
- [ ] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
See Help > About in Update Manager.

**Logs:**

**Comment by Isolator70** [comment]
Same issue here. Update was done via Update Manager. Fast servers from Germany selected after reboot.
Now red exclamation mark of update manager is visible in status bar and error message "Aktualisierungsliste konnte nicht aufgefrischt werden" (Update list could not be refreshed)
apt update in terminal shows no problems.

**Comment by ursatgithub** [comment]
Exactly the same issue. apt (commandline) works, Update Manager gets class OverflowError.

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/mintupdate/commit/271e58ad840c9255cfd853df008aaed305046fb3
