### ISSUE TITLE
mintUpdate 5.9.6 had some problem to update two flatpak items

### ISSUE THREAD

**Issue by estudiochapunov** [linuxmint/mintupdate#783]
I updated my Mint from 20.3 first to Vanessa, then immediately to Vera. 

After all the restarts, mintUpdate attempted to update Flatpaks items, one was a theme for GTK, as I can remember.

I tried two and three times to update, it completed the update as usual, but after the "update", both items still appeared in the  window as "updateable". 

Both were marked.

So, i unmarked one of them, and clicked on the Install button for the update to start. And, this time, it updated ok and the updated item dissapeared of the window.

Then, I marked the other item, ant clicked on the Install button for the update to start and again, it updated ok and the updated item disappeared also, as normally would happen.

I didn't took a screenshot of the situation but I am sending now attached a screenshot of the Update History of the mintUpdate.

In the screenshot it appears as the mintUpdate attempted to make the previous Flatpak updates but failed, and when worked ok was when I marked only one at a time... Strange.

I remember this same issue happening to me with the Cinnamon extensions a pair of times some months ago, but I didn't noticed to report that failure.

![Captura de pantalla de 2022-12-31 15-21-44](https://user-images.githubusercontent.com/10598754/210152682-1fe3472b-ea67-4401-8103-0ac92f882fb6.png)

**To Reproduce**
1. Go to mintUpdate
2. If there are more than one Flatpak items to update, with all of them marked, click on Install button.
3. It will appear to install all of them but... don't
4. See error as they after the "update" still are there as updateable items.
5. If you mark one at a time to update, it should work ok.

**Expected behavior**
It should update all of Flatpak items at once, without need to mark one at a time and install one at a time. Same thing maybe with Cinnamon extensions, check also.

**Distribution:**
- [ ] Linux Mint 21.1 Cinnamon "Vera"

**Software version:**
System:
  Kernel: 5.15.0-56-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.5
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME B450M-A v: Rev X.0x serial: <superuser required>
    UEFI-[Legacy]: American Megatrends v: 2006 date: 11/13/2019
CPU:
  Info: quad core model: AMD Ryzen 3 2200G with Radeon Vega Graphics bits: 64 type: MCP arch: Zen
    rev: 0 cache: L1: 384 KiB L2: 2 MiB L3: 4 MiB
  Speed (MHz): avg: 3136 high: 3304 min/max: 1600/3850 boost: disabled cores: 1: 3116 2: 3097
    3: 3304 4: 3030 bogomips: 30799
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Raven Ridge [Radeon Vega Series / Radeon Mobile Series] vendor: ASUSTeK PRIME
    driver: amdgpu v: kernel pcie: speed: 8 GT/s lanes: 16 ports: active: HDMI-A-1
    empty: DP-1,DVI-D-1 bus-ID: 08:00.0 chip-ID: 1002:15dd
  Device-2: Microdia Integrated Camera type: USB driver: uvcvideo bus-ID: 1-2:2
    chip-ID: 0c45:64ab
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: HDMI-A-0 mapped: HDMI-A-1 model: Samsung S22D300 res: 1920x1080 dpi: 102
    diag: 547mm (21.5")
  OpenGL: renderer: AMD Radeon Vega 8 Graphics (raven LLVM 13.0.1 DRM 3.42 5.15.0-56-generic)
    v: 4.6 Mesa 22.0.5 direct render: Yes
Audio:
  Device-1: AMD Raven/Raven2/Fenghuang HDMI/DP Audio vendor: ASUSTeK PRIME B450M-A
    driver: snd_hda_intel v: kernel pcie: speed: 8 GT/s lanes: 16 bus-ID: 08:00.1 chip-ID: 1002:15de
  Device-2: AMD Family 17h HD Audio vendor: ASUSTeK PRIME B450M-A driver: snd_hda_intel
    v: kernel pcie: speed: 8 GT/s lanes: 16 bus-ID: 08:00.6 chip-ID: 1022:15e3
  Sound Server-1: ALSA v: k5.15.0-56-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Wireless 7265 driver: iwlwifi v: kernel pcie: speed: 2.5 GT/s lanes: 1
    bus-ID: 04:00.0 chip-ID: 8086:095a
  IF: wlp4s0 state: up mac: <filter>
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ASUSTeK PRIME B450M-A
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: f000 bus-ID: 07:00.0
    chip-ID: 10ec:8168
  IF: enp7s0 state: down mac: <filter>
Bluetooth:
  Device-1: Intel type: USB driver: btusb v: 0.8 bus-ID: 1-9:5 chip-ID: 8087:0a2a
  Report: hciconfig ID: hci0 rfk-id: 1 state: up address: <filter> bt-v: 2.1 lmp-v: 4.2
    sub-v: 1100
Drives:
  Local Storage: total: 1.4 TiB used: 200.78 GiB (14.0%)
  ID-1: /dev/sda vendor: Kingston model: SA400S37240G size: 223.57 GiB speed: 6.0 Gb/s
    serial: <filter>
  ID-2: /dev/sdb vendor: Seagate model: ST1000DM010-2EP102 size: 931.51 GiB speed: 6.0 Gb/s
    serial: <filter>
  ID-3: /dev/sdc vendor: Western Digital model: WDS240G2G0B-00EPW0 size: 223.58 GiB
    speed: 6.0 Gb/s serial: <filter>
  ID-4: /dev/sdd type: USB model: MXT-USB Storage Device size: 57.98 GiB serial: <filter>
Partition:
  ID-1: / size: 219 GiB used: 195.67 GiB (89.3%) fs: ext4 dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile
Sensors:
  System Temperatures: cpu: N/A mobo: N/A gpu: amdgpu temp: 46.0 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: 3380 note: see --pkg apt: 3353 flatpak: 10 snap: 17
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list
    1: deb [arch=amd64] https: //packages.microsoft.com/repos/vscode stable main
  Active apt repos in: /etc/apt/sources.list.d/brave-browser-beta.list
    1: deb [signed-by=/usr/share/keyrings/brave-browser-beta-archive-keyring.gpg arch=amd64] https: //brave-browser-apt-beta.s3.brave.com/ stable main
  Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list
    1: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https: //brave-browser-apt-release.s3.brave.com/ stable main
  Active apt repos in: /etc/apt/sources.list.d/google.list
    1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //mint.zero.com.ar/mintpackages vera main upstream import backport
    2: deb http: //ubuntu.unc.edu.ar/ubuntu jammy main restricted universe multiverse
    3: deb http: //ubuntu.unc.edu.ar/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //ubuntu.unc.edu.ar/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/teamviewer.list
    1: deb [signed-by=/usr/share/keyrings/teamviewer-keyring.gpg] https: //linux.teamviewer.com/deb stable main
  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [arch=amd64,arm64,armhf] http: //packages.microsoft.com/repos/code stable main
Info:
  Processes: 294 Uptime: 5h 50m Memory: 13.58 GiB used: 2.41 GiB (17.7%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.3.0 alt: 11/9 Client: Cinnamon v: 5.6.5 inxi: 3.3.13

**Logs:**
Copy & paste the log output from Update Manager > View > Information here.
12.31@09:44 ++ Launching Update Manager
12.31@09:44 ++ Changes to the package cache detected, triggering refresh
12.31@09:44 ++ Starting refresh (local only)
12.31@09:44 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 10 minute(s)
12.31@09:45 ++ Found 2 software updates
12.31@09:45 ++ Refresh finished
12.31@09:47 ++ Install requested by user
12.31@09:48 ++ Starting refresh (local only)
12.31@09:48 ++ Found 2 software updates
12.31@09:48 ++ Refresh finished
12.31@09:50 ++ Changes to the package cache detected, triggering refresh
12.31@09:50 ++ Starting refresh (local only)
12.31@09:50 ++ Found 2 software updates
12.31@09:50 ++ Refresh finished
12.31@09:53 ++ Starting refresh (retrieving lists of updates from remote servers)
12.31@09:53 ++ Refreshing available Cinnamon updates from the server
12.31@09:53 ++ Refreshing available Flatpak updates
12.31@09:53 ++ Found 2 software updates
12.31@09:53 ++ Refresh finished
12.31@09:53 ++ Install requested by user
12.31@09:54 ++ Starting refresh (local only)
12.31@09:54 ++ Found 2 software updates
12.31@09:54 ++ Refresh finished
12.31@09:54 ++ Update Manager window is open, skipping initial refresh
12.31@09:54 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 58 minute(s)
12.31@09:56 ++ Install requested by user
12.31@09:56 ++ Starting refresh (local only)
12.31@09:56 ++ Found 1 software updates
12.31@09:56 ++ Refresh finished
12.31@09:57 ++ Install requested by user
12.31@09:57 ++ Starting refresh (local only)
12.31@09:57 ++ System is up to date
12.31@09:57 ++ Refresh finished
12.31@11:53 ++ Update Manager window is open, delaying recurring refresh by 60s
12.31@11:54 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
12.31@11:55 ++ Update Manager window is open, delaying recurring refresh by 60s
12.31@11:56 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
12.31@11:57 ++ Update Manager window is open, delaying recurring refresh by 60s
12.31@11:58 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
12.31@11:59 ++ Update Manager window is open, delaying recurring refresh by 60s
12.31@12:00 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
12.31@12:01 ++ Update Manager window is open, delaying recurring refresh by 60s
12.31@12:02 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
12.31@12:03 ++ Update Manager window is open, delaying recurring refresh by 60s
12.31@12:04 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
12.31@12:05 ++ Update Manager window is open, delaying recurring refresh by 60s
12.31@12:06 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
12.31@12:07 ++ Update Manager window is open, delaying recurring refresh by 60s
12.31@12:08 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
12.31@12:09 ++ Update Manager window is open, delaying recurring refresh by 60s
12.31@12:10 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
12.31@12:11 ++ Update Manager window is open, delaying recurring refresh by 60s
12.31@12:12 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
12.31@12:13 ++ Update Manager is in tray mode, performing recurring refresh
12.31@12:13 ++ Starting refresh (retrieving lists of updates from remote servers)
12.31@12:13 ++ Refreshing available Cinnamon updates from the server
12.31@12:13 ++ Refreshing available Flatpak updates
12.31@12:13 ++ System is up to date
12.31@12:13 ++ Refresh finished
12.31@12:13 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)
12.31@13:13 ++ Changes to the package cache detected, triggering refresh
12.31@13:13 ++ Starting refresh (local only)
12.31@13:13 ++ System is up to date
12.31@13:13 ++ Refresh finished
12.31@14:13 ++ Update Manager is in tray mode, performing recurring refresh
12.31@14:13 ++ Starting refresh (retrieving lists of updates from remote servers)
12.31@14:13 ++ Refreshing available Cinnamon updates from the server
12.31@14:13 ++ Refreshing available Flatpak updates
12.31@14:13 ++ System is up to date
12.31@14:13 ++ Refresh finished
12.31@14:13 ++ Recurring refresh will happen in 0 day(s), 1 hour(s) and 59 minute(s)

**Comment by mtwebster** [comment]
This could be related to the fact that you had just updated, or possibly by mis-handling of end-of-life'd flatpak runtimes (this should be [fixed](https://github.com/linuxmint/mintcommon/commit/8ddcdd27ce5417f285754ed4f268fbb62166f74d) now.

Regardless it doesn't seem to be something that can be reproduced currently, we can re-open this if necessary later (or just file a new bug).
