### ISSUE TITLE
Accessing Help > Contents returns Document not found

### ISSUE THREAD

**Issue by Topperfalkon** [linuxmint/mintupdate#79]
Environment:
- LM17
- mintUpdate 4.7.7

Reproduction steps
- Open Update Manager
- Select Help > Contents or press the F1 key
- The help page browser loads with the error:
 
> Document Not Found
The URI ‘help:linuxmint/software-updates’ does not point to a valid page.

**Comment by clefebvre** [comment]
Install mint-user-guide-<your-edition>.
