### ISSUE TITLE
Update from LM 20.1 to 20.3 breaks Firefox site data deletion

### ISSUE THREAD

**Issue by Scharsach** [linuxmint/mintupdate#800]
After updating from LM 20.1 Cinnamon to 20.3, I got the LM version of Mozilla Firefox 110.0.1 (mint-001 - 1.0). It appears the LM version 110.0.1 has a different behaviour when compared to Mozilla Firefox 110.0.1 downloaded from the Mozilla site. For example, when trying to "Clear Data" under "Privacy & Security"/"Cookies and Site Data", no cookies or site data were deleted (no error message). I noticed something similar when using the "Manage Data" option. I am not aware of other unexplained behaviour, but is this as expected? Can anybody confirm or explain this?

**Comment by mtwebster** [comment]
Not sure why this would be -

We start with the same tar.gz file from their website - all our packaging does is put the firefox folder in /usr/lib, and a few other things (desktop file, binfiles, icons.. ) in their appropriate locations. There shouldn't be any difference in how it deals with user profiles.

On my machine here, deleting specific site data (Manage Data) works fine with Mint's version.

**Comment by Scharsach** [comment]
I restarted LM firefox 110.0.1 (mint version), and this time  it worked as expected deleting all site data . I suspect there is a bug related to firefox, but I don't know what.
