### ISSUE TITLE
Can't load kernel from UI

### ISSUE THREAD

**Issue by Zaharid** [linuxmint/mintupdate#81]
I have the latest available 3.16 kernel. I wanted to try the recommended 3.13 so I clicked "install" to download it and set it up. However there is no way to mark it as "loaded" the GUI and my compute starts with the 3.16 kernel. I wish the updater also knew how to set up grub to load a specific kernel.

**Comment by xenopeek** [comment]
The kernel package itself has a post-install script which calls update-grub. That script that will create the new grub menu configuration. It puts the newest kernel as the entry to boot Linux Mint on the main menu and puts all the older kernels in a submenu "Advanced options for Linux Mint".

After the kernel package is installed mintupdate could edit the new grub menu configuration and swap kernel versions around but as users can also customize the scripts used to build the grub menu configuration, I think this is a complex feature request.
