### ISSUE TITLE
Mint Update will install applets/desklets without authentication.  

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/mintupdate#817]
I just got an update for sound150 applet.  Hitting install did the update without any authentication (root pw).
It's not too bad as a single item, but when multiple system updates are included with the applet/desklets, they all get done together.   
The latter issue **I** feel is a possible security issue.

Another issue with applets/desklets is that if there are many, it seems to only do one at a time.  It just means you have to click install several times.   (Without authentication is not so bad, I guess that's a plus on the other side of the coin).

**Distribution:**
Linux mint cinnamon 21.1
Update manager 5.9.8
Kernel: Linux 5.15.0-72-generic
DE: Cinnamon 5.6.8

@clefebvre

**Comment by JosephMcc** [comment]
Well xlets are installed in the /home directory and can be installed/removed/updated without authentication. Have you ever had it happen where other things updated alongside xlets without asking for a password? I'm pretty sure that can't happen.
