### ISSUE TITLE
21.2 Version is the commit hash instead of number

### ISSUE THREAD

**Issue by Tibladar** [linuxmint/mintupdate#821]
**Describe the bug**
Previously in Mint 21.1 the old and new version stated the flatpak version if possible and when not available the commit hash.
Now it always shows the commit hash.
This reduces usability

![image](https://github.com/linuxmint/mintupdate/assets/52620063/19dd0b85-b19c-49c7-8738-a231c42f6a34)

**To Reproduce**
1. Open mintupdate on Mint 21.2
2. Have an update for Firefox or other apps
3. See only commit hashes instead of e.g. 104.0 -> 104.0.1

**Distribution:**
- [X] Linux Mint

**Software version:**
6.0.1

**Comment by mtwebster** [comment]
https://github.com/linuxmint/mintcommon/issues/56, caused by a bug in the appstream-glib package, an update for it is pending.

**Comment by Reno-Sifana** [comment]
> [linuxmint/mintcommon#56](https://github.com/linuxmint/mintcommon/issues/56), caused by a bug in the appstream-glib package, an update for it is pending.

This Morning i got an update appstream-glib package. I can't confirm this updates already fixed incorrect name bug in flatpak. 
![Screenshot from 2023-06-20 08-26-13](https://github.com/linuxmint/mintupdate/assets/68702583/cccbb687-c49f-4d43-bece-f4be46f971e3)
