### ISSUE TITLE
Mismatched names and descriptions for updates containing several packages

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#83]
Examples:
firefox - English language pack for Firefox
libreoffice - HSQLDB SDBC driver for LibreOffice

// mintUpdate 4.7.9, Mint 17.1 MATE 32-bit

**Comment by zorbama** [comment]
Same for me. Here's a picture:
![bugtoreport-morespecific](https://cloud.githubusercontent.com/assets/6951677/6390483/6e5f0682-bdb5-11e4-9154-258ff17b5986.png)

**Comment by clefebvre** [comment]
There could be special cases and these will need aliases, but for most updates, this is now fixed by https://github.com/linuxmint/mintupdate/commit/070bf0b91b11936030c2062adc81bc4a94c46eec
