### ISSUE TITLE
Can't sort or search for apps to update.

### ISSUE THREAD

**Issue by kacperpaczos** [linuxmint/mintupdate#830]
**Describe the bug**
I have a few updates; I need to search one of these apps for something (for lock it, for example), but I can't do this. When I'm typing, I always get the first app from the top; this is not what I want.

mintupdate:5.9.8

**Screenshots**
![image](https://github.com/linuxmint/mintupdate/assets/23406555/5a5cbc41-739c-471e-80cc-fb79f68016cf)

**Comment by mtwebster** [comment]
This works ok for me - 

Can you File->Quit mintupdate and then run it from a terminal?
```
mintupdate
```
And then attempt a search? I'm curious if there's an error, or possibly some localization issue with package names and search text.

Also, the interactive search will not reduce the visible list of results. Instead it limits what you can select  (an using the arrow keys will jump between matches). It works similarly in nemo.

**Comment by kacperpaczos** [comment]
Ok, after makes update (5.9.8 ~> 6.0.3) it works. I close this issue.
