### ISSUE TITLE
Mintupdate description pane is too narrow

### ISSUE THREAD

**Issue by Reno-Sifana** [linuxmint/mintupdate#831]
**Describe the bug**
By Default after clean install the Linux Mint the description pane is too narrow. I have must resize the pane manually to fit the window.

**Screenshots**
![Screenshot from 2023-07-19 20-34-53](https://github.com/linuxmint/mintupdate/assets/68702583/d68a4eaa-0474-4052-90ac-3fc050139fde)

**To Reproduce**
1. Go to mintupdate in notification area
2. Click on refresh buton
3. and wait untif check for update finishes (if there an update available)
4. See the bug

**Expected behavior**
the description pane in mintupdate should fit the window by default.

**Distribution:**
- [x] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
6.0.3.

**Logs:**
Copy & paste the log output from Update Manager > View > Information here.

**Crash report:**
If you are reporting a crash, please run `mintupdate` from a terminal window, reproduce the crash and copy & paste any output from the terminal window here.

**Additional context**
Add any other context about the problem you think might be relevant.

**Locale:**
If the problem is with text not getting displayed correctly, paste the output of the terminal command `locale`.

**Comment by mtwebster** [comment]
What is the resolution of your monitor?

**Comment by Reno-Sifana** [comment]
> What is the resolution of your monitor?

as i recall 1366x768. monitor size 14 inches.

**Comment by mtwebster** [comment]
I added something to keep the lower pane a bit taller initially, but really it's going to have limited effect. The window remembers its size and the position of that pane, so once you fix it to your liking, you shouldn't have to adjust it again.
