### ISSUE TITLE
Add support for Flatpak yes/no actions

### ISSUE THREAD

**Issue by applecuckoo** [linuxmint/mintupdate#836]
**Is your feature request related to a problem? Please describe.**
Yes/no prompts which come through in the terminal don't come through via mintupdate.

**Describe the solution you'd like**
Preferably these yes/no prompts would come through mintupdate.

**Additional context**
The flatpak for [NewsFlash](https://flathub.org/apps/io.gitlab.news_flash.NewsFlash) had changed its ID. This meant that Flatpak had to reconfigure the NewsFlash flatpak and that required a yes/no response. This didn't show up in mintUpdate as it hanged on 'Getting metadata', so I had to cancel and update via the command line.

**Comment by zehkira** [comment]
[Looks like it was fixed](https://github.com/linuxmint/mintcommon/commit/8ddcdd27ce5417f285754ed4f268fbb62166f74d). Should be in the latest release.

**Comment by applecuckoo** [comment]
Hmm, we'll see. Closing for now.
