### ISSUE TITLE
mime-support package showing name/description of other packages in the updates

### ISSUE THREAD

**Issue by AlbertJP** [linuxmint/mintupdate#84]
The top-most package in the updates is mime-support, but its name does not appear. Instead other packages appear, changing when moving the mouse over the package or clicking it. Restarting mintupdate did not help. Mint 17.1 Cinnamon 32-bit.
![screenshot from 2015-01-07 21 51 32](https://cloud.githubusercontent.com/assets/1248033/5653119/9e9c90d2-96b7-11e4-8a1b-06c8c43aad80.png)
![screenshot from 2015-01-07 21 51 37](https://cloud.githubusercontent.com/assets/1248033/5653120/a10b9638-96b7-11e4-82df-045c85aade7a.png)
↑ In this picture I moved the mouse over the package.
![screenshot from 2015-01-07 21 51 44](https://cloud.githubusercontent.com/assets/1248033/5653122/a2d86e64-96b7-11e4-9ed3-1a171a4a6864.png)

May be a duplicate of #83

**Comment by clefebvre** [comment]
Not a duplicate but I believe this was fixed.
