### ISSUE TITLE
"Apply updates automatically' ignores blacklist and automatically updates all packages anyway (including blacklisted ones)

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mintupdate#848]
**Describe the bug**
When you have "Apply updates automatically" enabled, it will completely ignore the blacklist and will instead automatically update all packages (including blacklisted ones).

**Screenshots**
How about a video demonstration instead?  If you don't want to baby-sit the whole 93 minutes then, when you reach the 5 minute mark, you can skip ahead to exactly the 90-minute mark (or the 91 minute mark if you're fine missing the moment when the updates get automatically installed but before the mouse cursor moves again):

[422 10bit @ quality 61.webm](https://github.com/linuxmint/mintupdate/assets/11896003/5cf56f6e-f2be-40e4-a689-98ef07621e70)

If the video quality is too potato (blame github's 10MB file limit), then you can see a much higher-quality encoding of the very same video over on archive.org:
- https://archive.org/details/mintupdate-v6.0.5-apply-updates-automatically-ignores-blacklist-and-automaticall

**To Reproduce**

0. Watch the above video
1. Boot a live ISO of Mint 21.3 or LMDE 6
2. Make note of the stock version number for Firefox (or Thunderbird if using LMDE 6)
3. Add the packages `firefox` and `firefox*` to mintUpdate's blacklist (`thunderbird` and `thunderbird*` also works if using LMDE 6)
4. Enable "Apply updates automatically"
5. Make sure the PC will not enter S3 suspend
6. Log out and log back in
7. Wait a while (take a shower? go buy groceries? make dinner?)
8. Eventually, updates will be installed automatically and you will find that, despite Firefox and/or Thunderbird being on the blacklist in our example, they will still have been updated.

**Expected behavior**
Packages on the blacklist should not be updated when "Apply updates automatically" is enabled.

**Distribution:**
- Linux Mint
- LMDE

**Software version:**
6.0.5 (stock LMDE 6)
6.0.9 (Mint 21.3 as of 2024-02-01)

**Additional context**
I found out about this issue the difficult way on an actual installation of Linux Mint, and then promptly used a live ISO of the newly-released LMDE 6 to verify this behavior (what you see in the above video) **2024-02-01 UPDATE** And have double-checked that it still occurs on the Mint 21.3 live ISO.

**Comment by NintendoManiac64** [comment]
I have just found out that the `hold` terminal command basically works *exactly* like mintUpdate's blacklist (even resulting in the given packages not being listed in mintUpdate) except that it ***also*** works with automatic updates (and also packages that you've applied `hold` to are not listed in the blacklist):

- https://forums.linuxmint.com/viewtopic.php?t=412976

To be honest, it almost kind of looks like the blacklist is just "reinventing the wheel" but with a worse result compared to the `hold` command, making me wonder why the blacklist isn't just a GUI front-end for this hold command in the first place...?  Heck, the `hold` command even supports wildcards just like the blacklist does...

**Comment by NintendoManiac64** [comment]
It would seem that a function got added to "Update Manager" on its "Automation" tab that is even present in the 21.3 live ISO to export your blacklist to /etc/mintupdate.blacklist in order for automatic updates to actually "see" it, yet this here still-open bug report of mine was never touched nor referenced and so I never even caught wind that this is now a thing... what the heck?

Well then I guess I'll just close this issue myself...

**Comment by budmanz1** [comment]
I have no idea of what this is about.
