### ISSUE TITLE
Update Level 5 Displays Despite Settings

### ISSUE THREAD

**Issue by zorbama** [linuxmint/mintupdate#85]
Hello!

In Mintupdate 4.8.0, on Linux Mint 17.1 Cinnamon 32-bit, a level 5 update for the "linux" package is displayed in the main update window, despite my settings to not show such updates.

When changing the settings to display level 5 updates, more level 5 updates are visible. When turning them back off, only the "linux" update remains.

I'm going to hide this update from my update list specifically, but it seems to me like a bug that should be reported.

-Amir

**Comment by clefebvre** [comment]
There's an option for security updates to always show (or not) no matter what their level is.

**Comment by zorbama** [comment]
Found it. Thanks. :)
