### ISSUE TITLE
mintupdate cant run

### ISSUE THREAD

**Issue by alen-sherif** [linuxmint/mintupdate#86]
alen@alen-LinuxMint ~ $ mintupdate
(mintUpdate.py:5541): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:5541): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:5541): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:5541): libglade-WARNING **: unknown attribute `swapped' for <signal>.
Attempt to unlock mutex that was not locked

**Comment by muzena** [comment]
I have this problem too, can't run mint update

sinisa@sinisa-gigabyte ~ $ 
(mintUpdate.py:13729): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:13729): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:13729): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:13729): libglade-WARNING **: unknown attribute `swapped' for <signal>.
Attempt to unlock mutex that was not locked

**Comment by monsta** [comment]
See https://github.com/linuxmint/mintinstall/issues/82#issuecomment-73022841
