### ISSUE TITLE
Deselect all updates

### ISSUE THREAD

**Issue by timur-g** [linuxmint/mintupdate#861]
Sometimes, we get a long list of updates (also may come from user added repos). 
We may want to update just a few packages, skipping for example the whole office package update for few days. 
There is the button Select All but there is no Deselect All. 
Please add or make Select All toggle with Deselect All.

**Comment by Xmetalfanx** [comment]
while not a critical addition ... I too think this would be a nice "feature" to add ... say there are a few updates i'd want to do but at that moment i wanted NOT to a kernel or flatpak update ... easier to hit deselect all then check like 3-4 updates then to uncheck say 12 updates, one by one

**Comment by mtwebster** [comment]
Clear = Deselect all

**Comment by timur-g** [comment]
Thanks, should have been "clear" but somehow I used Clear only for manual changes.
