### ISSUE TITLE
Flatpak: incorporate Flatpak runtime dependencies

### ISSUE THREAD

**Issue by mlavi** [linuxmint/mintupdate#864]
After reviewing all updates in Update Manager, I would like the install the updates (inclusive of Flatpak runtimes) with one click.

When a Flatpak update requires a upgraded dependency, such as Flatpak runtimes, they are listed in the "Flatpaks" dialog (see attached), and the user can Cancel or Continue. 

![update-manager_flatpaks](https://github.com/linuxmint/mintupdate/assets/5642075/11f46558-d73f-4f3f-949f-6cdd6cefcaa5)

Update Manager includes all of the apt dependencies for review, but the Flatpak dependency experience isn't analogous. Flatpak runtime dependencies require a second confirmation and "an extra click," which slows updates. I barely look at the runtime dependencies and have never cancelled because they are implicitly required. In my opinion, this extra click is friction that degrades the upgrade experience.

I'd like the Flatpak runtime dependencies to be listed with all of software updates (apt and Flatpak), bypassing the "Flatpaks" runtime upgrade confirmation dialog, accomplishing `flatpak update --assumeyes`.  If a user deselects the Flatpak runtime upgrades, it should trigger the existing experience.

In the past, I've upgraded Flatpaks via CLI, but I appreciate Upgrade Manager incorporating Flatpak so much that I want to achieve more upgrades with less friction and a single click.

**Comment by DocBrown101** [comment]
I can fully agree with that. After a while it gets pretty annoying and it has to be done. There is no choice.
