### ISSUE TITLE
Updating Firefox not working correctly

### ISSUE THREAD

**Issue by Synix4Life** [linuxmint/mintupdate#867]
**Describe the bug**
Hi, i have a problem while updating Firefox through the Update Manager.
In general, the Update Manager works fine and installs applications with an exceptional speed, but not Firefox. Firefox takes ages to install, most of the times with < 10 kByte/s and then often fails with an error. All other applications, even when they are installed in the same process as Firefox, download with the usual speed and no Problems occur. I've tried everything so far what I know, like restarting, clearing cache and so on, but it still doesn't work.

**Screenshots**
![1](https://github.com/linuxmint/mintupdate/assets/116163789/36c4db16-8e9e-4013-a3dd-66576067a07c)

**To Reproduce**
Unfortunately, I can't really give you an explanation on reproduction, because i don't even know why it is happening

**Expected behavior**
Well, it should install with the same speed as all other applications

**Distribution:**

- [ ]  Linux Mint 21.3 Cinnamon
- [ ]  Package Version 6.0.4
- [ ]  Linux Kernel 5.15.0-94-generic

**Software version:**
6.0.9

**Logs:** (Not the full Log, but everything associated with the bug)
02.21@13:54 ++ Inhibited power management
02.21@13:54 ++ Install requested by user
02.21@13:54 ++ Will install firefox-locale-en
02.21@13:54 ++ Will install firefox
02.21@13:54 ++ Ready to launch synaptic

(synaptic:4766): Gtk-CRITICAL **: 13:54:54.032: gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
02.21@14:20 ++ Return code:0
02.21@14:20 ++ Install failed
02.21@14:20 ++ Resumed power management
02.21@14:20 ++ Inhibited power management

**Additional context**
I've had two different Linux Mint installations on my device as of now, and it occurred in both, so i don't think it has anything to do with a failed install.
The installations have also both been from different Mirror websites

**Comment by Guergeiro** [comment]
Okay, it seems that this is general issue.
![image](https://github.com/linuxmint/mintupdate/assets/39097691/495bf565-65e7-4226-8f17-e189ffed2550)
