### ISSUE TITLE
Mintupdate freezes the system

### ISSUE THREAD

**Issue by WillemsenGithub** [linuxmint/mintupdate#868]
**Describe the bug**
Mintupdate freezes the system completely

**Screenshots**
Cant, after freeze

**To Reproduce**
Mint Xfce all latest, launch Mintupdate as user of root. 
Worked until few days ago

**Expected behavior**

**Distribution:**
- [x] Linux Mint, Xfce all latest

**Software version:**
609, 605

**Logs:**
No logs available, cant open app, and systemlogs empty

**Crash report:**
Cant, app freezes system

**Additional context**
Maybe related to latest Flatpak updates

**Locale:**
EN, NL

**Comment by WillemsenGithub** [comment]
Addition, 
After some tries: 
Errors like "mintupdate produces .xsession-errors Gdk.threads_init is deprecated"

Tried
In SofwareSources, disabled all added packages and keys, refresh, same issue: freeze system
Renamed /usr/lib/linuxmint/mintUpdate and -Upgrade
Running from Terminal with user or root: same issue: no show and system freeze with error like that
Sudo mintupdate-cli works fine

**Comment by WillemsenGithub** [comment]
Update:
Reinstalled xfce4 (from Cinnamon, which I used previously)
Removed recently added PPA and keys
Reinstalling several Flatpaks from commandline (many "pinned", not sure ow to deal with that yet)
Used Synaptic to reinstall several python libraries 

Mintupdate seems to work again. 
Cant pinpoint  any more detailed

Can close this bug, Ill open new one when needed

**Comment by WillemsenGithub** [comment]
Closing this bug, Ill open new one when needed

**Comment by ra50** [comment]
Did you ever figure out what system change may have caused this?

**Comment by WillemsenGithub** [comment]
Sorry, cant pinpoint it .. (ever since I keep Track-Change, as it should)

In may have been related some broken PPA/certificate. Remember it started when adding PPA in different ways (from command line while Mintupdate open) 

While MU was broken, Synaptic worked on Xfce (and this uses same repository right?)
Mintupdate from Cinnamon worked as well. 

After updating stuff as described above, clearing PPA/re-adding PPA the MintUpdate stabilized.

**Comment by ra50** [comment]
From your description, this is definitely the same issue I'm experiencing here: https://github.com/linuxmint/mintupdate/issues/869

What do you mean by Track-Change?

I have no PPAs enabled and can't figure out what other package change may have caused this.

If you have any other hints or recollections of specific actions you took please send along.
