### ISSUE TITLE
No notification when an update to a flatpak occurs due to low disk space

### ISSUE THREAD

**Issue by mdpenguin** [linuxmint/mintupdate#872]
**Describe the bug**
When updating a flatpak, if there is not enough disk space to download the update file then mintUpdate refreshes as though it has completed but continues to list the flatpak that didn't update.  No error messages are displayed.

**To Reproduce**
1. Create an environment with a large flatpak program installed (e.g. GIMP or Firefox) and low available disk space
2. Run update
3. Note that update appears to complete but flatpaks are still listed to be updated once it refreshes

**Expected behavior**
Display any error messages from the flatpak update procedure

**Distribution:**
- [x] Linux Mint

**Software version:**
Version 6.0.9

**Comment by mtwebster** [comment]
https://github.com/linuxmint/mintupdate/commit/545f7bd300263c58b0be060aeae02c5e064da6cf
