### ISSUE TITLE
l10n Ukrainian: one small correction

### ISSUE THREAD

**Issue by yvs2014** [linuxmint/mintupdate#892]
**Describe the bug**
I think there's forgotten (or automatically inserted) double quotation marks for "Update manager" in Ukrainian translation

**Screenshots**
| with double quotes | without |
| ------------- | ------------- |
| ![w_q2marks](https://github.com/user-attachments/assets/619c6b51-c0f1-4542-a0b8-c1b324d64de1) | ![wo_q2marks](https://github.com/user-attachments/assets/3f94b646-f5de-4b6d-ab72-3c8932d950e6) |

**To Reproduce**
set language interface to Ukrainian, click on Start menu button, choose Administration, and look at "Update manager" element

**Expected behavior**
Uniform menu list (for example like https://github.com/yvs2014/mintupdate/commit/4b53bf1a04b70a9bcde697409565c8c6f087cfd8)

**Distribution:**
- [ x] Linux Mint

**Software version:**
MintUpdate 6.1.5

**Locale:**
LANG=uk_UA.UTF-8
LANGUAGE=uk_UA
LC_CTYPE="uk_UA.UTF-8"
LC_NUMERIC=uk_UA.UTF-8
LC_TIME=uk_UA.UTF-8
LC_COLLATE="uk_UA.UTF-8"
LC_MONETARY=uk_UA.UTF-8
LC_MESSAGES="uk_UA.UTF-8"
LC_PAPER=uk_UA.UTF-8
LC_NAME=uk_UA.UTF-8
LC_ADDRESS=uk_UA.UTF-8
LC_TELEPHONE=uk_UA.UTF-8
LC_MEASUREMENT=uk_UA.UTF-8
LC_IDENTIFICATION=uk_UA.UTF-8
LC_ALL=

**Comment by carlosmintfan** [comment]
You can use Launchpad to contribute to translations; see https://linuxmint-translation-guide.readthedocs.io/en/latest/

**Comment by yvs2014** [comment]
It's fixed in scope of https://github.com/linuxmint/mintupdate/commit/1018d285fcdee350fd17f1a030f86e0a12cf06eb update

Thank you
