### ISSUE TITLE
Incorrect word spelling in "restart to take effect" message in Russian

### ISSUE THREAD

**Issue by JustChickNugget** [linuxmint/mintupdate#895]
**Describe the bug**
There is a typo after updating package that requires system restart.

**Screenshots**
(Can't reproduce this right now but I found the typo in source: "po/mintupdate-ru.po")
![Снимок экрана от 2024-10-04 15-20-31](https://github.com/user-attachments/assets/07852f86-4062-4a0a-ac2d-f0584906846d)

**To Reproduce**
1. Switch to russian language (if needed);
2. Update package that requires system restart to take effect;
3. See message in the update manager.

**Expected behavior**
Correct word spelling.
UPD: instead of "перезагурзите" - "перезагрузите"

**Distribution:**
- [ ] Linux Mint
- [x] LMDE
- [ ] Other (please specify)

**Software version:**
6.1.5

**Logs:**
```
10.04@15:13 ++ Launching Update Manager
10.04@15:13 ++ Changes to the package cache detected; triggering refresh
10.04@15:13 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 10 minute(s)
10.04@15:13 ++ Inhibited power management
10.04@15:13 ++ Starting refresh (local only)
10.04@15:13 ++ System is up to date
10.04@15:13 ++ Refresh finished
10.04@15:13 ++ Resumed power management
10.04@15:13 ++ Inhibited power management
10.04@15:13 ++ Starting refresh (local only)
10.04@15:13 ++ System is up to date
10.04@15:13 ++ Refresh finished
10.04@15:13 ++ Resumed power management
10.04@15:23 ++ Update Manager window is open; skipping initial refresh
10.04@15:23 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
```

**Crash report:**
-

**Additional context**
-

**Locale:**
```
LANG=ru_RU.UTF-8
LANGUAGE=
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```

**Comment by mtwebster** [comment]
It would need to be fixed here:
https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/ru/+translate?batch=10&show=all&search=you+have+installed

Interestingly, the other translation there is correct (I think that's part of older mintupdate versions). The punctuation was changed at some point, and the mis-spelling added.
