### ISSUE TITLE
Flatpaks not shown in update manager if can't uninstall EOL flatpak runtime

### ISSUE THREAD

**Issue by pssandhu** [linuxmint/mintupdate#896]
**Describe the bug**
If an EOL flatpak runtime can't be uninstalled because a flatpak app is still depending on it, the flatpak-update-worker hangs and exceeds the timeout from the call from update manager. This results in no flatpak updates being shown in the UI.

**To Reproduce**
1. Have an end of life flatpak with at least one flatpak app that uses it and other flatpaks that have updates available
2. Open mintupdate or press Refresh
3. Wait for updates to fetch
4. No flatpak updates shown

**Expected behavior**
Flatpak updates should still be shown. `flatpak update` is still able to update other apps despite this warning. At least an error should be shown to the user rather than silently failing to show flatpak updates.

**Distribution:**
Linux Mint 21.1

**Software version:**
5.9.8

**Logs:**
Running `/usr/lib/linuxmint/mintUpdate/flatpak-update-worker.py --fetch-updates`

```
(flatpak-update-worker.py:71383): As-WARNING **: 15:53:45.587: net.krafting.SemantiK.Lang.English was of type addon but had no extends
(flatpak-update-worker.py:71383): As-WARNING **: 15:53:46.618: net.krafting.SemantiK.Lang.English was of type addon but had no extends
mint-common (WARN): runtime/org.freedesktop.Platform/x86_64/22.08 is EOL (org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.). Replacing with None
mint-common (WARN): runtime/org.freedesktop.Platform.GL32.default/x86_64/22.08-extra is EOL (org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.). Replacing with None
flatpak-update-worker (WARN): fetch error Can't uninstall org.freedesktop.Platform/x86_64/22.08 which is needed by com.github.wwmm.pulseeffects/x86_64/stable
```

**Additional context**
Uninstalling or updating the app depending on the EOL runtime removes this issue but this can't be done from mintupdate

**Comment by mtwebster** [comment]
This should have been fixed by https://github.com/linuxmint/mintcommon/commit/8ddcdd27ce5417f285754ed4f268fbb62166f74d (starting in mint-common 2.3.1).

I think you'd need to update to at least 21.2 to get that and a more recent mintupdate also.
