### ISSUE TITLE
why is `celluloid` on `Linux Mint 22` still using version 0.21?

### ISSUE THREAD

**Issue by candrapersada** [linuxmint/mintupdate#901]
why is `celluloid` on `Linux Mint` 22 non `flatpak` still using version 0.21?

**Comment by clefebvre** [comment]
Linux Mint 22 (all editions) supports the ability for the user to choose a GTK theme. After moving to libAdwaita, recent versions of Celluloid no longer integrate with the GTK theme.

This is considered a blocker bug which prevents celluloid from being part of the default software selection in Linux Mint 22.

From there Mint 22 had to replace Celluloid with an alternative, an earlier version or a fork. The earlier version still worked perfectly so it was chosen.

**Comment by candrapersada** [comment]
but why is there still Celluloid when installing Linux Mint 22?

**Comment by clefebvre** [comment]
> From there Mint 22 had to replace Celluloid with an alternative, an earlier version or a fork. The earlier version still worked perfectly so it was chosen.

**Comment by candrapersada** [comment]
will `Celluloid` stay, be replaced, removed, or move to `flatpak`?

**Comment by clefebvre** [comment]
No change in the upcoming 22.1.

No plan to ship with Flatpak apps by default in the foreseeable future.

We'll probably start forking GNOME apps, but this hasn't started yet.

**Comment by Samueru-sama** [comment]
> We'll probably start forking GNOME apps, but this hasn't started yet.

Btw please I beg you, fork zenity gtk3. I'm so done with the gtk4 version giving me flashbangs and Steam depends on it. 😭
