### ISSUE TITLE
Mintupdate Kernel Module Can't List Kernel 4.0.x

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintupdate#91]
Mintupdate kernel module can not list new kernel 4.0.x versions. Could you fix following lines on checkKernels.py file.

if package.startswith("linux-image-3") and package.endswith("-generic"):

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintupdate/commit/6bb43000fd66dd2276e951ec2bbde601afe7efcb
