### ISSUE TITLE
Add an option to close/leave-open window after updates are applied

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mintupdate#92]
Add an option to close/leave-open window after updates are applied

**Comment by gordon-morehouse** [comment]
Why closed?

**Comment by JosephMcc** [comment]
Closed because of this: https://github.com/linuxmint/mintupdate/commit/b43078bb40b6bf51c743586eb8652ab0aee40bb5

**Comment by gordon-morehouse** [comment]
Thanks! I'd been watching this issue because it was bugging me (no pun intended). :)

**Comment by burianvlastimil** [comment]
How do I use the feature Close after updates?

**Comment by JosephMcc** [comment]
Go to Edit->Preferences and choose "Hide the update manager after applying updates".
