### ISSUE TITLE
Custom python installation breaks mintupdate

### ISSUE THREAD

**Issue by tm45** [linuxmint/mintupdate#94]
After I built and installed Python 2.7.9 into /usr/local/bin, mintupdate stopped working. When I removed a /usr/local/bin/python, mintupdate started working again. It is obvious that in its code mintupdate relies on just "python", but should explicitly rely on system python - "/usr/bin/python".

**Comment by darealshinji** [comment]
Does it work if you change all the shebangs in the python scripts to `#!/usr/bin/python2` even if your custom version is still installed in /usr/local/bin?

**Comment by tm45** [comment]
I restored /usr/local/bin/python and the mintUpdate icon dissapeared from the tray. I tried to launch mintUpdate in terminal - it didn't launch and produced the following message: 
No module named gtk
No module named pygtk
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintUpdate/mintUpdate.py", line 59, in <module>
    gettext.install("mintupdate", "/usr/share/linuxmint/locale")
NameError: name 'gettext' is not defined

Then I replaced the line "#!/usr/bin/env python" by "#!/usr/bin/python" and tried to launch the application - it started normally and its icon appeared in the tray.

**Comment by monsta** [comment]
Fixed by https://github.com/linuxmint/mintupdate/issues/96.
