### ISSUE TITLE
Doesnt function if synaptic doesnt run

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintupdate#99]
For some strange reason, synaptic wasnt running on my machine due to libept not being installed but when i tried to use mintupdate, installing updates or refreshing the packages would result in no action being taken and no error message being shown, so it would be good for an error message to appear in mintupdate if synaptic doesnt function.

**Comment by xenopeek** [comment]
The mintupdate package has synaptic as a required dependency, which in turn has libapt as a required dependency. The only way to have mintupdate and synaptic installed without also having libapt installed is if you have a system with broken dependencies.
